= Organizing Documentation for Antora
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

Antora is designed to work with a consistent project structure.
The benefits of a standard project structure are:

* interoperability with author, IDE, migration, and validation tools
* input source to input source cross references that can span repositories and be automatically updated by Antora when a source's name or location changes
* faster contributor orientation

We call a collection of documentation files that are organized together using Antora's standard project structure a [.term]_documentation component_.

When you use documentation components, you can take advantage of the open source tools, plugins, and automated processes built to integrate with the Antora pipeline.

== Documentation component overview

A documentation component is a standardized organization structure used by Antora.
A component consists of a collection of related AsciiDoc text files and their assets, such as images, and a component descriptor file.
All of the documentation in a component should follow the same versioning scheme and be versioned together.
Your site can be generated using just one or as many documentation components as you want.

When Antora receives instructions from your playbook to scan a specific repository, its first objective is to find a component descriptor file in that repository.
The component descriptor file is named `antora.yml`.

Once Antora finds this file, it assumes that that directory and all of its subsequent subdirectories and their files are a documentation component and organized in the structure laid out below.

.Component directory hierarchy
....
antora.yml
modules/
  ROOT/
    assets/
      attachments/
      images/
    examples/
    nav.adoc
    pages/
      _partials/
      user-named-topic/
  user-named-module/
    assets/
      images/
    nav.adoc
    pages/
....
// Replace block with component illustration

The component illustrated in the above image contains required and reserved directories and files as well as a few examples of optional directories you can create if needed.
When Antora encounters these folders and files in a properly structured component, it automatically assigns preset behavior and metadata to them.

.Component preset legend
****
*Required* - Must be present in the documentation component.

*Optional* - Doesn't need to be created if the directory, file, or content type isn't applicable to the component or module.

*Reserved* - Directory or file is associated with specific pipeline operations.
The contents of a directory or file using a reserved name must adhere to certain requirements.
****

xref:antora_yml.adoc[antora.yml] ::
_Required_; _Reserved_
+
The component descriptor file tells Antora that the contents of the directory are a documentation component.
This file contains crucial xref:antora_yml.adoc[metadata about the documentation component].

xref:module.adoc[modules/] ::
_Required_; _Reserved_
+
Except for [.path]_antora.yml_, all of the files in a component reside in this directory.

xref:module.adoc#root[ROOT/] ::
_Required_; _Reserved_
+
Directory that contains the xref:module.adoc#root[mandatory ROOT module].
The directory name must be written in all uppercase letters.

xref:module.adoc#assets-dir[assets/] ::
_Optional_; _Reserved_
+
Directory where multimedia and supplemental files are organized by content type.

xref:module.adoc#attachments-dir[attachments/] ::
_Optional_; _Reserved_
+
Directory that contains supplemental materials, such as PDFs or ZIP files, that readers can download via a link created in a page using the xref:page-assets.adoc#insert-attachment[AsciiDoc link macro].

xref:module.adoc#images-dir[images/] ::
_Optional_; _Reserved_
+
Directory that contains photographs, screenshots, diagrams, and other graphics files that are displayed in a page using the xref:page-assets.adoc#insert-image[AsciiDoc image macro].

examples/ ::
_Optional_; _Reserved_
+
Directory that contains source, literal, listing, or example block snippets that are inserted into that module's pages.

xref:navigation:linked.adoc[nav.adoc] ::
_Optional_; _Reserved_
+
A xref:navigation:linked.adoc[linked navigation file] that contains a single, unordered, AsciiDoc list.
Unlike an xref:aspect.adoc#register[aspect navigation file], the linked navigation file in a module is enlisted automatically by Antora and doesn't have to be registered in a playbook.
However, to control the order in which each module's navigation file is displayed when they're assembled into a site, you'll need to enter them into the component's xref:antora_yml.adoc#nav-key[nav key].

xref:module.adoc#pages-dir[pages/] ::
_Optional_; _Reserved_
+
Directory that contains all of a module's AsciiDoc files.
These files are automatically enlisted by Antora and converted to standalone HTML pages.

xref:module.adoc#partials-dir[_partials/] ::
_Optional_; _Reserved_
+
Directory that contains AsciiDoc files that can be inserted into the files stored directly under [.path]_pages/_.
These files are *not* converted to HTML by Antora unless they are explicitly called by an xref:page-partials.adoc[include directive] in another page.

user-named module/ ::
_Optional_
+
Additional modules ...

//We know the structure in the example above represents a documentation component because of the presence of an [.path]_antora.yml_ file.
