= Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
// URIs
:uri-node: https://nodejs.org
:uri-git: https://git-scm.com
:uri-git-dl: {uri-git}/downloads
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-yarn: https://yarnpkg.com

This page describes:

* [x] What prerequisites are needed to bootstrap Antora.
* [x] How to set up Antora on your computer.

If you've never set up Antora before, you'll need to complete the steps on this page before you can configure a playbook and generate a site.

To set up Antora, you'll need:

* git
* nvm (optional, but strongly recommended)
* Node.js
* Yarn

== git

You need basic git skills and {uri-git}[git] (command: `git`) installed on your machine in order to pull down project repositories and push updates to them.

Check to see if you have git installed.

 $ git --version

If that command doesn't return any information, {uri-git-dl}[download and install] the git package for your system.

== Node 8.x

Antora is built on {uri-node}[Node.js] (aka Node) (command: `node`), but you don't need to know how to program in JavaScript in order to use Antora.
You just need to install Node on your machine.

The minimum required version of Node is 8.0.0, though we recommend using the latest release in the 8.x series.

To see what version of Node you have installed, if any, open a terminal and type:

 $ node --version

If `node --version` doesn't return any information, you don't have Node installed.
Skip directly to <<install-nvm,install nvm and Node>> for instructions.

If `node --version` returns a version < 8.0.0 and you have nvm installed, go directly to <<upgrade-node,upgrade and alias Node with nvm>> for instructions.

If `node --version` returns a version >= 8.0.0, just set Node 8 as the default.
Type the following command in your terminal, then jump to the instructions for <<yarn,installing Yarn>>.

 $ nvm alias default 8

[#install-nvm]
=== Install nvm and Node

TIP: Many CI environments use nvm to install the version of Node used for the build job.
By using nvm, you can closely align your setup with the environment that is used to generate and publish your production site.

We strongly recommend using {uri-nvm}[nvm] (Node Version Manager) to manage your Node installations.
Follow the {uri-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node 8 using:

 $ nvm install 8

The above command will install the latest version of Node 8.

The `nvm install` command automatically sets the latest Node 8 version as the default alias, so you can skip the next section and go directly to the instructions for <<yarn,installing Yarn>>.

[#upgrade-node]
=== Upgrade and alias Node with nvm

If you have nvm installed but your Node version is < 8.0, type the following command in your terminal:

 $ nvm install 8

The above command will install the latest version of Node 8.

Next, set Node 8 as the default for any new terminal.
Define the default alias as follows:

 $ nvm alias default 8

The above command will set the latest version of Node 8 as your default.

[#yarn]
== Yarn

{uri-yarn}[Yarn] (command: `yarn`) is the preferred package manager and script runner for the Node ecosystem.
You'll need Yarn to download Antora and manage its dependencies as new versions are released.

Install Yarn globally with the following command:

 $ npm install -g yarn

(You got access to the `npm` command when you installed Node.)

Next, verify Yarn is installed by checking the version:

 $ yarn --version

If you see a version, you are all set.
If your Yarn installation failed, see xref:troubleshoot-yarn-nodegit.adoc[Troubleshooting Yarn and NodeGit].

Now that you have Node and Yarn installed, you're ready to xref:playbook:set-up-existing-playbook-project.adoc[clone and initialize an Antora playbook project].
