= Yarn and NodeGit Troubleshooting
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
// URIs
:uri-nodegit: http://www.nodegit.org
:uri-nodegit-dev: http://www.nodegit.org/guides/install/from-source

Some Node packages used by Antora require certain development libraries, such as a C compiler, to be available on your machine.
If you've already been using your machine for development, it's highly likely you already have these tools installed.
However, if your Yarn installation fails, these libraries are the most probable culprit.

== NodeGit

Antora interfaces with git repositories using {uri-nodegit}[NodeGit] (JavaScript bindings for libgit2).
You *don't* need to install NodeGit because it is pulled in as a dependency by Yarn.

However, in order for Yarn to install NodeGit, you need to have the development tools (i.e., a C compiler) installed on your machine.
Details about how to get these libraries can be found in the *Installing Dependencies* section of the page {uri-nodegit-dev}[Building NodeGit from source].
