= Antora Redirect Producer

The redirect producer is the component in Antora responsible for producing redirects (HTTP redirections) to a given page from its registered aliases.
These redirects are derived from alias entries in the content catalog.

This component can produce redirects using different facilities.
If the deployment environment does not offer redirect capabilities, Antora can output static HTML redirect pages (for client-side redirection).
If redirect capabilities are available in the deployment environment, such as rewrite rules in nginx, Antora can output a suitable server configuration file (for server-side redirection).

https://antora.org[Antora] is a modular static site generator designed for creating documentation sites from AsciiDoc documents.
Its site generator pipeline aggregates documents from versioned content repositories and processes them using https://asciidoctor.org[Asciidoctor].

== Copyright and License

Copyright (C) 2017-2019 https://opendevise.com[OpenDevise Inc.] and the https://antora.org[Antora Project].

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
