language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: setup
      script:
        - yarn install
        - npm install gulp-cli
        - ./node_modules/.bin/jsdoc scripts/*.js -d jsdoc
    - stage: verify
      script: gulp lint
    # - script: gulp test
    - stage: deploy
      script: antora ./test_cicd_playbook/antora_playbook.yml
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GitHubToken  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./out
        on:
          all_branches: true


