language: node_js
node_js:
  - 12
  - 10

cache:
  yarn: true
  directories:
    - "node_modules"
    - "docs"

jobs:
  include:
    - stage: setup
      script:
        - yarn install
        - npm install gulp-cli
        - ./node_modules/.bin/jsdoc scripts/*.js -d docs
    - stage: verify
      script: gulp lint
      - node_js: 10
        script: gulp test -e "Run on node js 10"
      - node_js: 12
        script: gulp test -e "Run on node js 12"
    - stage: deploy
      script: antora ./test_cicd_playbook/antora_playbook.yml
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GitHubToken  # Set in the settings page of your repository, as a secure variable
        local_dir: ./docs
        verbose: true
        on:
          all_branches: true


