language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: setup
      script: yarn install
    - script: npm install gulp-cli
    - script: npm install jsdoc
    - script: ./node_modules/.bin/jsdoc jsdoc scripts/*.js
    - stage: verify
      script: gulp lint
    # - script: gulp test
    - stage: deploy
      script: antora ./test_cicd_playbook/antora_playbook.yml
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GitHubToken  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./out
        on:
          all_branches: true


