language: node_js
node_js:
  - 12

cache:
  yarn: true

jobs:
  include:
    - stage: setup
      script: yarn install
    - stage: verify
      script: gulp lint
      script: gulp test
    # - stage: deploy
    #   script: ./deploy


