language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: setup
      script:
        - yarn install
        - npm install gulp-cli
        - ./node_modules/.bin/jsdoc scripts/*.js -d docs
    - stage: verify
      - language: node_js
        node_js: 12
        script: gulp lint -e "Run on node js 12"
      - language: node_js
        node_js: 11
        script: gulp lint -e "Run on node js 11"
    # - script: gulp test
    - stage: deploy
      script: antora ./test_cicd_playbook/antora_playbook.yml
      deploy:
        provider: pages
        cleanup: true
        token: $GitHubToken  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./docs
        on:
          all_branches: true


