language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - "node_modules"
    - "docs"

jobs:
  include:
    - stage: setup
      node_js: 10
      script:
        - yarn install
        - npm install gulp-cli
        - ./node_modules/.bin/jsdoc scripts/*.js -d docs

    - stage: verify
      name: "Test 10"
      node_js: 10
      script:
        - yarn install
        - npm install gulp-cli
        - gulp lint
        - gulp test
        
    - name: "Test 12"
      node_js: 12
      script:
        - yarn install
        - npm install gulp-cli
        - gulp lint
        - gulp test

    - stage: deploy
      script: antora ./test_cicd_playbook/antora_playbook.yml
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GitHubToken  # Set in the settings page of your repository, as a secure variable
        local_dir: ./docs
        verbose: true
        on:
          all_branches: true


