language: node_js
node_js: 12

cache:
  yarn: true
  directories:
    - "node_modules"

stage:
 - setup
 - verify
 - deploy

jobs:
  include:
    - stage: setup
      node_js: 12
      script:
        - yarn install
        - npm install gulp-cli
        #- ./node_modules/.bin/jsdoc scripts/*.js -d docs

    - stage: verify
      name: "Test 10"
      node_js: 10
      script:
        - gulp lint
        - gulp test

    - stage: verify
      name: "Test 12"
      node_js: 12
      script:
        - gulp lint
        - gulp test
        
    - stage: deploy
      script:
        - antora ./test_cicd_playbook/antora_playbook.yml
        - pwd
        - ls docs
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GitHubToken
        local_dir: ./docs
        verbose: true
        on:
          all_branches: true


