language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: setup
      script: yarn install
    - script: npm install gulp-cli
    - stage: verify
      script: gulp lint
    # - script: gulp test
    - stage: deploy
      script: antora ./docs/antora_playbook.yml


