language: node_js
node_js:
  - 12

cache:
  yarn: true

jobs:
  include:
    - stage: setup
      script:
        - yarn install
        - npm install gulp-cli
    - stage: verify
      before_script:
        - rm -rf coverage .nyc_output node_modules/.cache/nyc
      script: 
        - gulp lint
        - gulp test
    # - stage: deploy
    #   script: ./deploy


