= Antora Changelog

This document provides a summary of all notable changes to the core Antora components by release.
For a detailed view of what's changed, refer to the repository's https://gitlab.com/antora/antora/commits/master[commit history].

This project utilizes semantic versioning.

== Unreleased

=== Changed

* *content-aggregator*: Make transfer progress callback asynchronous so progress bar updates don't affect transfer

== 1.0.0-beta.1 (2018-03-07)

=== Added

* *content-aggregate*: Allow content to be aggregated from tags in a content repository
* *content-classifier*: Add ContentCatalog#getSiteStartPage method
* *page-composer*: Set `site.homeUrl` variable in UI model if site start page is set
* *page-composer*: Set `page.home` variable in UI model; true if page is site start page (page URL matches `site.homeUrl`)

=== Changed

* *content-aggregate*: Don't select all branches if branch pattern is undefined
* *content-aggregate*: Use blob action instead of edit action in `src.editUrl` for files taken from tag
* *content-aggregate*: Pass tag patterns to selectRefs (read from `tags` on content source or shared content key)
* *content-aggregate*: Rename selectBranches function to selectRefs and change return value of selectRefs to include ref type

== 1.0.0-alpha.9 (2018-03-06)

=== Added

* *playbook-builder*: Add key to playbook schema to control how HTTP redirects are produced (`urls.redirect_facility`)
* *content-aggregate*: Honor `runtime.quiet` and `runtime.silent` flags if set in playbook (don't show progress bars)
* *content-aggregate*: Add progress bar for all git operations using multi-progress (only activate when running in a tty)
* *content-classifier:* Add support for alias files (family=alias) in content catalog
* *content-classifier:* Add ContentCatalog#registerPageAlias method for adding an alias for a page
* *document-converter*: Register aliases defined in page-aliases document attribute with content catalog
* *redirect-producer:* Add component responsible for generating HTTP redirects to a page from its registered aliases

=== Changed

* *content-aggregator*: Require runtime property to be set in playbook in content aggregator
* *content-classifier*: Move parsePageId function from asciidoc-loader to content-classifier
* *content-classifier*: Move resolvePage function from asciidoc-loader to content-classifier
* *content-classifier*: Add ContentCatalog#resolvePage method (delegates to resolvePage function)
* *content-classifier*: Move computation of pub and out properties to ContentCatalog#addFile
* *content-classifier*: Skip files in aggregate which cannot be classified
* *content-classifier*: Use ContentCatalog#resolvePage to resolve start page for component version and site
* *content-classifier*: Store select settings from playbook in ContentCatalog (htmlUrlExtensionStyle)
* *contnet-classifier*: Rename ContentCatalog#registerComponentVersion to ContentCatalog#addComponentVersion
* *content-classifier*: Move resolveStartPageUrl logic into ContentCatalog#addComponentVersion
* *content-classifier*: Don't call getById in ContentCatalog#resolvePage if component not found
* *site-mapper*: Rename generateSitemaps function to mapSite function in site mapper component
* Clean up tests and add additional coverage

=== Fixed

* *content-aggregate*: Report URL of repository when component descriptor is missing or invalid
* *content-classifier*: Use fallback URL for component version if implicit start page is missing (and no start page has been set)
* *content-classifier*: Report location of file when attempt is made to add duplicate file to catalog
* *playbook-builder*: Remove obsolete keys

== 1.0.0-alpha.8 (2018-02-27)

=== Added

* *content-aggregator*: Make cache directory configurable; default to antora folder in user cache directory
* *ui-loader*: Make cache directory configurable; default to antora folder in user cache directory
* *playbook-builder*: Add `runtime.cache_dir` property to playbook schema; can be set using `ANTORA_CACHE_DIR` environment variable
* *cli*: Add `--cache-dir` CLI option for setting the cache directory
* *document-converter*: Introduce convertDocuments function to encapsulate conversion of documents from AsciiDoc to embeddable HTML

=== Changed

* Allow paths in playbook to be anchored to various locations
 ** Expand leading `.` segment to directory of playbook file
 ** Expand leading `~` segment to user home directory
 ** Expand leading `~+` segment to current working directory
 ** BREAKING: Resolve unanchored path relative to current working directory
* Delegate to new @antora/expand-path-helper module to expand relative path to absolute path
* *content-aggregator*: Add dependency on @antora/expand-path-helper and cache-directory
* *ui-loader*: Add dependency on @antora/expand-path-helper and cache-directory
* *site-publisher*: Add dependency on @antora/expand-path-helper
* Set NODE_ENV=test when running tests
* Document extra package requirement for installing on Alpine

=== Fixed

* *content-aggregator*: Make URI and drive letter regular expressions more accurate so SSH URIs aren't mistaken for local directory paths
* *cli*: Don't show default value for CLI option if value is object

== 1.0.0-alpha.7 (2018-02-20)

=== Added

* *playbook-builder*: Allow global AsciiDoc attributes to be defined via the playbook (`asciidoc.attributes`)
* *playbook-builder*: Allow global and scoped AsciiDoc extensions to be defined via the playbook (`asciidoc.extensions`)
* *cli*: Add support for defining global AsciiDoc attributes using a CLI option (`--attribute`)
* *cli*: Add a CLI option for preloading scripts or node modules (`--require`)
* *asciidoc-loader*: Introduce resolveConfig function to resolve AsciiDoc configuration object from playbook
* *asciidoc-loader*: Define API on extension functions (`register(registry, context)`) to allow extensions to self-register
* *asciidoc-loader*: Register scoped extensions defined in playbook with the extension registry (per processor instance)
* *site-publisher*: Add architecture guidebook
* *site-mapper*: Add architecture guidebook
* Define and document the software versioning and maintenance policy

=== Changed

* *asciidoc-loader*: Modify loadAsciiDoc function to accept AsciiDoc configuration object
* *asciidoc-loader*: Reorder parameters of convertDocument function; fold opts into AsciiDoc config
* *asciidoc-loader*: Use public Asciidoctor.js API where possible
* *document-converter*: Modify convertDocument function to accept AsciiDoc configuration object
* *document-converter*: Reorder parameters of convertDocument function
* *document-converter*: Reorder parameters of buildNavigation function
* *navigation-builder*: Modify buildNavigation function to accept AsciiDoc configuration object
* *navigation-builder*: Use public Asciidoctor.js API where possible
* *site-generator-default*: Add dependency on asciidoc-loader component
* *site-generator-default*: Use AsciiDoc loader to resolve AsciiDoc configuration object
* *site-generator-default*: Pass AsciiDoc configuration object through pipeline instead of raw AsciiDoc attributes
* *site-generator-default*: Remove unnecessary async keywords
* *playbook-builder*: Move definition of custom formats in playbook schema to dedicated function
* *cli*: Show full stacktrace if site generator fails to load and --stacktrace option is specified
* *cli*: Delegate to function to exit with error message
* Write all regular expressions using shorthand notation
* Set cache directory for nyc explicitly
* Upgrade dependencies

=== Fixed

* *playbook-builder*: Remove warning about coffee-script when installing the default site generator package
* When requiring modules, only pass starting paths (with node_modules as last segment) to require.resolve

== 1.0.0-alpha.6 (2018-02-09)

=== Added

* *docs:* Add Getting Help section to README
* *content-aggregator:* Assign src.editUrl property on file if applicable
* *page-composer:* Pass defined site.keys to UI model (as site.keys)
* *page-composer:* Pass edit URL for page to UI model (as page.editUrl)
* *playbook-builder:* Add ui.supplemental_files property to playbook schema
* *ui-loader:* Append supplemental files to UI bundle

=== Changed

* *docs:* Prepare documentation for initial publication to docs.antora.org
* *content-aggregator:* Report accurate messages if local directory doesn't exist or isn't a git repository (@benignbala)
* *content-aggregator:* Move src.origin.git property to src.origin with type qualifier property
* *content-aggregator:* Share src.origin data between files taken from the same branch
* *content-aggregator:* Set src.origin.url to absolute repository path if remote url can't be resolved
* *content-aggregator:* Add src.origin.worktree flag for files taken from worktree
* *content-aggregator:* Force set remote name to 'origin' when using repository from cache
* *content-aggregator:* Use async operation to remove cached repository directory
* *content-aggregator:* Remove local branch created by nodegit in cached (bare) repository
* *ui-loader:* Improve how UI bundle is loaded

=== Fixed

* *asciidoc-loader:* Output correct href value for self-referencing page reference (with and without fragment)
* *content-aggregator:* Prefer remote branches over local branches in a bare repository
* *site-generator-default:* Await function calls properly to avoid unhandled promise rejections

== 1.0.0-alpha.5 (2018-02-01)

=== Added

* *site-mapper:* First release of component
* *site-generator-default:* Add support for site start page defined in playbook (redirect from index.html)

=== Changed

* Resolve relative paths in playbook relative to directory of playbook file (playbook.dir)
* *content-aggregator:* Append .git to the bare repository folder in the content cache
* *content-classifier:* Don't set pub.absoluteUrl property on virtual content files
* *asciidoc-loader:* Default to latest version of component when resolving a page reference
* *playbook-builder:* Set file and dir properties on playbook model
* *playbook-builder:* Make playbook file optional (still required by CLI)
* Switch Gulp build from minimist to yargs-parser for parsing CLI arguments

=== Fixed

* *content-aggregator:* Clean value of start path on content source data
* *content-aggregator:* Make URI and drive letter regular expressions more accurate

== 1.0.0-alpha.4 (2018-01-28)

=== Changed

* Fixed release process to publish README in correct format

== 1.0.0-alpha.3 (2018-01-28)

=== Added

* *site-publisher:* First release of component
* *content-aggregator:* Recognize HEAD and . in playbook as placeholder for current branch
* Update installations instructions in README to cover Windows
* Add AppVeyor CI build for testing on Windows
* Configure CI to automate releases
* Document in README how to use serve package to preview site through local web server
* Document the base build tools required on Linux and macOS in README

=== Changed

* *content-aggregator:* Only select git references which are branches
* *ui-loader:* Switch from download to got
* Replace chai-as-promised with async/await in test suite

=== Fixed

* Make code portable to Windows
* Compute correct URL path for self-referencing index page

== 1.0.0-alpha.2 (2018-01-28)

* Release failed to complete

== 1.0.0-alpha.1 (2018-01-12)

* Initial alpha release
