= Antora Changelog

This document provides a summary of all notable changes to the core Antora components by release.
For a detailed view of what's changed, refer to the repository's https://gitlab.com/antora/antora/commits/master[commit history].

This project utilizes semantic versioning.

== 1.0.0-alpha.6 (2018-02-09)

=== Added

* *docs:* Add Getting Help section to README
* *content-aggregator:* Assign src.editUrl property on file if applicable
* *page-composer:* Pass defined site.keys to UI model (as site.keys)
* *page-composer:* Pass edit URL for page to UI model (as page.editUrl)
* *playbook-builder:* Add ui.supplemental_files property to playbook schema
* *ui-loader:* Append supplemental files to UI bundle

=== Changed

* *docs:* Prepare documentation for initial publication to docs.antora.org
* *content-aggregator:* Report accurate messages if local directory doesn't exist or isn't a git repository (@benignbala)
* *content-aggregator:* Move src.origin.git property to src.origin with type qualifier property
* *content-aggregator:* Share src.origin data between files taken from the same branch
* *content-aggregator:* Set src.origin.url to absolute repository path if remote url can't be resolved
* *content-aggregator:* Add src.origin.worktree flag for files taken from worktree
* *content-aggregator:* Force set remote name to 'origin' when using repository from cache
* *content-aggregator:* Use async operation to remove cached repository directory
* *content-aggregator:* Remove local branch created by nodegit in cached (bare) repository
* *ui-loader:* Improve how UI bundle is loaded

=== Fixed

* *asciidoc-loader:* Output correct href value for self-referencing page reference (with and without fragment)
* *content-aggregator:* Prefer remote branches over local branches in a bare repository
* *site-generator-default:* Await function calls properly to avoid unhandled promise rejections

== 1.0.0-alpha.5 (2018-02-01)

=== Added

* *site-mapper:* First release of component
* *site-generator-default:* Add support for site start page defined in playbook (redirect from index.html)

=== Changed

* Resolve relative paths in playbook relative to directory of playbook file (playbook.dir)
* *content-aggregator:* Append .git to the bare repository folder in the content cache
* *content-classifier:* Don't set pub.absoluteUrl property on virtual content files
* *asciidoc-loader:* Default to latest version of component when resolving a page reference
* *playbook-builder:* Set file and dir properties on playbook model
* *playbook-builder:* Make playbook file optional (still required by CLI)
* Switch Gulp build from minimist to yargs-parser for parsing CLI arguments

=== Fixed

* *content-aggregator:* Clean value of start path on content source data
* *content-aggregator:* Make URI and drive letter regular expressions more accurate

== 1.0.0-alpha.4 (2018-01-28)

=== Changed

* Fixed release process to publish README in correct format

== 1.0.0-alpha.3 (2018-01-28)

=== Added

* *site-publisher:* First release of component
* *content-aggregator:* Recognize HEAD and . in playbook as placeholder for current branch
* Update installations instructions in README to cover Windows
* Add AppVeyor CI build for testing on Windows
* Configure CI to automate releases
* Document in README how to use serve package to preview site through local web server
* Document the base build tools required on Linux and macOS in README

=== Changed

* *content-aggregator:* Only select git references which are branches
* *ui-loader:* Switch from download to got
* Replace chai-as-promised with async/await in test suite

=== Fixed

* Make code portable to Windows
* Compute correct URL path for self-referencing index page

== 1.0.0-alpha.2 (2018-01-28)

* Release failed to complete

== 1.0.0-alpha.1 (2018-01-12)

* Initial alpha release
