= Antora Changelog

This document provides a summary of all notable changes to the core Antora components by release.
For a detailed view of what's changed, refer to the repository's https://gitlab.com/antora/antora/commits/master[commit history].

This project utilizes semantic versioning.

== Unreleased

=== Added

* *page-composer*: Make latest page version accessible from UI model (#307)
* *asciidoc-loader*: Assign site-url and site-title AsciiDoc attributes if url and title are set in playbook, respectively (#304)
* *asciidoc-loader*: Assign page-version attribute as alias for page-component-version

=== Changed

* *asciidoc-loader*: Assign global built-in attributes in resolveConfig instead of loadAsciiDoc

=== Fixed

* *content-classifier*: Allow a page alias to reference any component or component version (#303)
* *asciidoc-loader*: Fix memory leak caused by Asciidoctor converter extension (#306)

== 1.1.0 (2018-08-28)

=== Added

* *content-aggregator*: Compute edit URLs for pages sourced from repositories hosted at pagure.io (#283)
* *content-classifier*: Look for partial files in the partials folder directly under the module folder (in addition to pages/_partials) (#254)
* *content-classifier*: Add additional methods to content catalog: getComponentsSortedBy(), getComponentMap(), getComponentMapSortedBy() (#253)
* *content-classifier*: Add ContentCatalog#getComponentVersion(component, version) method (#287)
* *content-classifier*: Allow display version to be set in component descriptor using `display_version` key; assign `displayVersion` property to component version object (#288)
* *content-classifier*: If the `prerelease` key is set in component descriptor and the display version is not set, automatically compute display version and assign to `displayVersion` property on component version object (#288)
* *content-classifier*: Add parseResourceId function to parse resource ID (`version@component:module:family$path`) (#226)
* *content-classifier*: Add resolveResource function and ContentCatalog#resourceResource method to resolve resource file object from resource ID (#226)
* *content-classifier*: Remove parsePageId and resolvePage functions (replaced by parseResourceId and resolveResource, respectively) (#226)
* *asciidoc-loader*: Allow resource ID to be specified in target of include directive (unless target begins with `\{partialsdir}` or `\{examplesdir}`) (#226)
* *asciidoc-loader*: Attach context of current file to file property on Asciidoctor reader (#226)
* *navigation-builder*: Attach navigation (set) to each component version object to make it accessible via UI template (#281)
* *page-composer*: Pass the source origin information for a page to the UI model as `page.origin` (#293)
* *cli*: Add `--generator` option to specify a custom site generator library or script (#178)

=== Changed

* *content-aggregator*: Set component title to component name if title is not defined
* *content-classifier*: Skip component version flagged as prerelease when determining latest version unless all versions are prereleases (#287)
* *content-classifier*: Rename ContentCatalog#addComponentVersion(...) method to ContentCatalog#registerComponentVersion(...) (#287)
* *content-classifier*: Change arguments of ContentCatalog#registerComponentVersion(...) to `name, version, { title, prerelease, startPage } = {}` (#287)
* *content-classifier*: Rename latestVersion property on component version to latest; add alias for latestVersion (#287)
* *page-composer*: Set canonicalUrl to qualified URL of latest page version unless version is a prerelease (#287)
* *page-composer*: Look up page version using ContentCatalog#getById(resourceId) instead of ContentCatalog#findBy(critiera) (#287)
* *page-composer*: Assign components to `site.components` as a map instead of an array (#253)

=== Fixed

* *content-aggregator*: Coerce component name to a string

== 1.0.3 (2018-08-07)

=== Fixed

* *navigation-builder*: Preserve list items in navigation tree that are siblings of open blocks (#265)

== 1.0.2 (2018-08-06)

=== Improved

* *content-aggregator*: Include start path and name of reference in error messages that pertain to antora.yml (#267)
* *content-aggregator*: Honor HEAD branch name when using remote URL (resolves to default branch) (#272)
* *content-aggregator*: Use worktree when branch is HEAD and repository is not on a branch (#279)
* *content-aggregator*: Show informative message when start path in content repository doesn't exist or isn't a directory (#274)
* *navigation-builder*: Allow navigation sublists to be enclosed in open blocks (#265)
* *cli*: Recommend adding the --stacktrace option when the CLI exits with an error (#273)
* *playbook-builder*: Upgrade convict and remove workarounds for environment isolation and parsing custom data formats
* *redirect-producer*: Add directory redirects to Netlify redirect config for URLs ending in /index.html when using default HTML URL extension style (#278)
* Upgrade dependencies

=== Fixed

* *content-aggregator*: CLI --attribute option updates map of attributes defined in playbook file instead of replacing it (#250)
* *content-aggregator*: Fix crash when resolving HEAD reference by copying branches array before modifying it (#261)
* *content-aggregator*: Convert ref patterns (branches and tags) defined in playbook to strings (#262)
* *content-aggregator*: Remove authentication credentials from repository URL when used in error messages (#270)
* *content-aggregator*: Fetch all tags when the runtime pull option is enabled (#271)

=== Documented

* A .nojekyll file must be used to publish an Antora-generated site to GitHub Pages (#194)
* Explain how to use private content repositories with Antora (#139)
* Share trick to prevent Antora from using the worktree for a local URL (#236)
* Branches remain enabled even when tags are set
* Packages required to install/recompile nodegit on RHEL

== 1.0.1 (2018-05-06)

=== Improved

* *asciidoc-loader*: Upgrade to Asciidoctor.js from 1.5.6-rc.1 to 1.5.6 (final)
* *asciidoc-loader*: Don't register include in catalog (to avoid mangling page references)
* *content-aggregator*: Add support for basic authentication tokens in a git URL (#238)
* *ui-loader*: Allow keys in the UI descriptor to be written in snake_case (#245)
* *page-composer*: Add entry for current page to breadcrumbs when page is discrete (a page not present in navigation tree) (#243)

=== Fixed

* *playbook-builder*: Recognize .yaml as a valid YAML extension for a playbook file (when specified explicitly) (#229)
* *content-aggregator*: Don't select branches that match the name of internal properties (store branches in a Map) (#241)
* *page-composer*: Ignore fragment in URL of navigation entry when comparing URLs to resolve breadcrumb path (#244)

== 1.0.0 (2018-03-31)

* First stable release!

=== Changed

* *site-publisher*: The publishSite function returns an array of report objects collected from calling the destination providers
* *site-publisher*: The destination provider functions are expected to return a report object
* *site-publisher*: The built-in destination providers (fs and archive) return a report object that contains publishing information

== 1.0.0-rc.2 (2018-03-30)

=== Added

* *ui-loader*: Use outputDir specified in ui.yml of bundle if ui.outputDir is not specified in playbook

=== Changed

* *playbook-builder*: Remove automatic migration of legacy ui keys in playbook data
* *content-classifier*: Change compareVersion function to compare non-semantic versions as strings
* *content-classifier*: Change compareVersion function to always prefer a non-semantic version over a semantic version
* *content-classifier*: Change compareVersion function to take into account prerelease identifiers
* *content-classifier*: Don't publish underscore files (files with a filename that starts with an underscore or files below a directory that starts with an underscore)
* *content-classifier*: Don't drop _attributes.adoc files found inside pages directory from content catalog
* *asciidoc-loader*: Lock version of Asciidoctor.js to 1.5.6-rc.1
* *document-converter*: Don't convert documents that are not published (don't have an out property)
* *site-mapper*: Change mapSite to accept a collection of pages (virtual files) instead of the content catalog
* Lock version of image used for CI job to prevent future CI outages
* Remove commitlint

=== Fixed

* *content-classifier*: Only fail to register a component version if version number is an exact match of a registered version

=== Documentation

* *redirect-producer*: Add architecture guidebook for redirect producer component
* Document how to register Asciidoctor extensions
* Document the `page-partial` attribute and including standard pages and example files
* Document ability to set AsciiDoc page attributes in the playbook and via the CLI
* Expand documentation for content navigation, including assembly, file structure, functionality, and registration

== 1.0.0-rc.1 (2018-03-27)

=== Added

* *asciidoc-loader*: Pass information from src property on page available to AsciiDoc document via document attributes
* *page-composer*: Make environment variables available to UI templates by assigning to `env` variable of UI model

=== Changed

* *playbook-builder*: Allow Google Analytics key to be set using GOOGLE_ANALYTICS_KEY environment variable
* *page-composer*: Move antoraVersion property from site to top-level variable in UI model
* *page-composer*: Prepare a sparse UI model for the 404 page
* *site-generator-default*: Create and compose a 404 page if the `site.url` key is set in the playbook
* *site-generator-default*: Remove unhandled rejection listener; move to CLI, but leave disabled

== 1.0.0-beta.3 (2018-03-23)

=== Added

* *content-aggregator*: Interpret string branches and tags patterns defined on a content source as CSV (e.g., `master,v*`)
* *page-composer*: Bind Antora version to antoraVersion variable in UI model
* *default-ui*: Add support for additional languages in highlight.js configuration (Kotlin, Scala, Haskell, and nix)
* *demo*: Upgrade playbook for demo site to use the latest Antora features
* *demo*: Create two versions in Demo Component B to demonstrate the component selector drawer and page version selector in default UI

=== Changed

* *content-aggregator*: Name folder of cloned repository using pattern <basename>-<sha1>.git
* *content-aggregator*: No longer necessary to posixify path from git tree
* *asciidoc-loader*: Upgrade to Asciidoctor.js 1.5.6-rc.1 and switch to public API where possible
* Upgrade dependencies

=== Fixed

* *content-aggregator*: Only clone each remote content source once (group operations that share the same URL)
* *cli*: Fix duplicate error prefix when site generator is not found
* *default-ui*: Isolate expand/collapse state for each nav menu
* *default-ui*: Fix Google Tag Manager (gtag) script
* *default-ui*: Link to correct component version in root navigation and breadcrumb entries
* Correct `site.start_page` and component descriptor `start_page` page IDs in documentation examples
* Correct `sources.branches` key YAML syntax; when branch names are in a comma-separated list, the list must be enclosed in square brackets (`[]`)

== 1.0.0-beta.2 (2018-03-13)

=== Added

* *playbook-builder*: Add `runtime.pull` key to playbook schema to control whether remote resources are pulled
* *playbook-builder*: Map `runtime.pull` playbook key to `--pull` CLI flag
* *redirect-producer*: Add Netlify redirect facility to redirect producer (activate by setting `urls.redirect_facility` to `netlify`)

=== Changed

* *playbook-builder*: Remap `ui.bundle` key to `ui.bundle.url`
* *playbook-builder*: Remap `ui.start_path` key to `ui.bundle.start_path`
* *playbook-builder*: Update description of `urls.html_url_extension_style` key
* *playbook-builder*: Update description of `asciidoc.attributes` key
* *content-aggregator*: Only run fetch operation on cached repository if runtime pull option is enabled
* *content-aggregator*: Move all but first argument to openOrCloneRepository function to option hash
* *content-aggregator*: Make transfer progress callback asynchronous so progress bar updates don't affect transfer
* *ui-loader*: Always download UI bundle from URL if runtime pull option is enabled and bundle is marked as a snapshot
* *ui-loader*: Read bundle URL from `ui.bundle.url` key in playbook
* *ui-loader*: Read bundle start path from `ui.bundle.start_path` key in playbook
* *cli*: Rename `--ui-bundle` option to `--ui-bundle-url`

=== Fixed

* *content-aggregator*: Show friendly error message along with repository URL when clone fails

== 1.0.0-beta.1 (2018-03-07)

=== Added

* *content-aggregator*: Allow content to be aggregated from tags in a content repository
* *content-classifier*: Add ContentCatalog#getSiteStartPage method
* *page-composer*: Set `site.homeUrl` variable in UI model if site start page is set
* *page-composer*: Set `page.home` variable in UI model; true if page is site start page (page URL matches `site.homeUrl`)

=== Changed

* *content-aggregator*: Don't select all branches if branch pattern is undefined
* *content-aggregator*: Use blob action instead of edit action in `src.editUrl` for files taken from tag
* *content-aggregator*: Pass tag patterns to selectRefs (read from `tags` on content source or shared content key)
* *content-aggregator*: Rename selectBranches function to selectRefs and change return value of selectRefs to include ref type

== 1.0.0-alpha.9 (2018-03-06)

=== Added

* *playbook-builder*: Add key to playbook schema to control how HTTP redirects are produced (`urls.redirect_facility`)
* *content-aggregator*: Honor `runtime.quiet` and `runtime.silent` flags if set in playbook (don't show progress bars)
* *content-aggregator*: Add progress bar for all git operations using multi-progress (only activate when running in a tty)
* *content-classifier*: Add support for alias files (family=alias) in content catalog
* *content-classifier*: Add ContentCatalog#registerPageAlias method for adding an alias for a page
* *document-converter*: Register aliases defined in page-aliases document attribute with content catalog
* *redirect-producer*: Add component responsible for generating HTTP redirects to a page from its registered aliases

=== Changed

* *content-aggregator*: Require runtime property to be set in playbook in content aggregator
* *content-classifier*: Move parsePageId function from asciidoc-loader to content-classifier
* *content-classifier*: Move resolvePage function from asciidoc-loader to content-classifier
* *content-classifier*: Add ContentCatalog#resolvePage method (delegates to resolvePage function)
* *content-classifier*: Move computation of pub and out properties to ContentCatalog#addFile
* *content-classifier*: Skip files in aggregate which cannot be classified
* *content-classifier*: Use ContentCatalog#resolvePage to resolve start page for component version and site
* *content-classifier*: Store select settings from playbook in ContentCatalog (htmlUrlExtensionStyle)
* *content-classifier*: Rename ContentCatalog#registerComponentVersion to ContentCatalog#addComponentVersion
* *content-classifier*: Move resolveStartPageUrl logic into ContentCatalog#addComponentVersion
* *content-classifier*: Don't call getById in ContentCatalog#resolvePage if component not found
* *site-mapper*: Rename generateSitemaps function to mapSite function in site mapper component
* Clean up tests and add additional coverage

=== Fixed

* *content-aggregator*: Report URL of repository when component descriptor is missing or invalid
* *content-classifier*: Use fallback URL for component version if implicit start page is missing (and no start page has been set)
* *content-classifier*: Report location of file when attempt is made to add duplicate file to catalog
* *playbook-builder*: Remove obsolete keys

== 1.0.0-alpha.8 (2018-02-27)

=== Added

* *content-aggregator*: Make cache directory configurable; default to antora folder in user cache directory
* *ui-loader*: Make cache directory configurable; default to antora folder in user cache directory
* *playbook-builder*: Add `runtime.cache_dir` property to playbook schema; can be set using `ANTORA_CACHE_DIR` environment variable
* *cli*: Add `--cache-dir` CLI option for setting the cache directory
* *document-converter*: Introduce convertDocuments function to encapsulate conversion of documents from AsciiDoc to embeddable HTML

=== Changed

* Allow paths in playbook to be anchored to various locations
 ** Expand leading `.` segment to directory of playbook file
 ** Expand leading `~` segment to user home directory
 ** Expand leading `~+` segment to current working directory
 ** BREAKING: Resolve unanchored path relative to current working directory
* Delegate to new @antora/expand-path-helper module to expand relative path to absolute path
* *content-aggregator*: Add dependency on @antora/expand-path-helper and cache-directory
* *ui-loader*: Add dependency on @antora/expand-path-helper and cache-directory
* *site-publisher*: Add dependency on @antora/expand-path-helper
* Set NODE_ENV=test when running tests
* Document extra package requirement for installing on Alpine

=== Fixed

* *content-aggregator*: Make URI and drive letter regular expressions more accurate so SSH URIs aren't mistaken for local directory paths
* *cli*: Don't show default value for CLI option if value is object

== 1.0.0-alpha.7 (2018-02-20)

=== Added

* *playbook-builder*: Allow global AsciiDoc attributes to be defined via the playbook (`asciidoc.attributes`)
* *playbook-builder*: Allow global and scoped AsciiDoc extensions to be defined via the playbook (`asciidoc.extensions`)
* *cli*: Add support for defining global AsciiDoc attributes using a CLI option (`--attribute`)
* *cli*: Add a CLI option for preloading scripts or node modules (`--require`)
* *asciidoc-loader*: Introduce resolveConfig function to resolve AsciiDoc configuration object from playbook
* *asciidoc-loader*: Define API on extension functions (`register(registry, context)`) to allow extensions to self-register
* *asciidoc-loader*: Register scoped extensions defined in playbook with the extension registry (per processor instance)
* *site-publisher*: Add architecture guidebook
* *site-mapper*: Add architecture guidebook
* Define and document the software versioning and maintenance policy

=== Changed

* *asciidoc-loader*: Modify loadAsciiDoc function to accept AsciiDoc configuration object
* *asciidoc-loader*: Reorder parameters of convertDocument function; fold opts into AsciiDoc config
* *asciidoc-loader*: Use public Asciidoctor.js API where possible
* *document-converter*: Modify convertDocument function to accept AsciiDoc configuration object
* *document-converter*: Reorder parameters of convertDocument function
* *document-converter*: Reorder parameters of buildNavigation function
* *navigation-builder*: Modify buildNavigation function to accept AsciiDoc configuration object
* *navigation-builder*: Use public Asciidoctor.js API where possible
* *site-generator-default*: Add dependency on asciidoc-loader component
* *site-generator-default*: Use AsciiDoc loader to resolve AsciiDoc configuration object
* *site-generator-default*: Pass AsciiDoc configuration object through pipeline instead of raw AsciiDoc attributes
* *site-generator-default*: Remove unnecessary async keywords
* *playbook-builder*: Move definition of custom formats in playbook schema to dedicated function
* *cli*: Show full stacktrace if site generator fails to load and --stacktrace option is specified
* *cli*: Delegate to function to exit with error message
* Write all regular expressions using shorthand notation
* Set cache directory for nyc explicitly
* Upgrade dependencies

=== Fixed

* *playbook-builder*: Remove warning about coffee-script when installing the default site generator package
* When requiring modules, only pass starting paths (with node_modules as last segment) to require.resolve

== 1.0.0-alpha.6 (2018-02-09)

=== Added

* *docs*: Add Getting Help section to README
* *content-aggregator*: Assign src.editUrl property on file if applicable
* *page-composer*: Pass defined site.keys to UI model (as site.keys)
* *page-composer*: Pass edit URL for page to UI model (as page.editUrl)
* *playbook-builder*: Add ui.supplemental_files property to playbook schema
* *ui-loader*: Append supplemental files to UI bundle

=== Changed

* *docs*: Prepare documentation for initial publication to docs.antora.org
* *content-aggregator*: Report accurate messages if local directory doesn't exist or isn't a git repository (@benignbala)
* *content-aggregator*: Move src.origin.git property to src.origin with type qualifier property
* *content-aggregator*: Share src.origin data between files taken from the same branch
* *content-aggregator*: Set src.origin.url to absolute repository path if remote url can't be resolved
* *content-aggregator*: Add src.origin.worktree flag for files taken from worktree
* *content-aggregator*: Force set remote name to 'origin' when using repository from cache
* *content-aggregator*: Use async operation to remove cached repository directory
* *content-aggregator*: Remove local branch created by nodegit in cached (bare) repository
* *ui-loader*: Improve how UI bundle is loaded

=== Fixed

* *asciidoc-loader*: Output correct href value for self-referencing page reference (with and without fragment)
* *content-aggregator*: Prefer remote branches over local branches in a bare repository
* *site-generator-default*: Await function calls properly to avoid unhandled promise rejections

== 1.0.0-alpha.5 (2018-02-01)

=== Added

* *site-mapper*: First release of component
* *site-generator-default*: Add support for site start page defined in playbook (redirect from index.html)

=== Changed

* Resolve relative paths in playbook relative to directory of playbook file (playbook.dir)
* *content-aggregator*: Append .git to the bare repository folder in the content cache
* *content-classifier*: Don't set pub.absoluteUrl property on virtual content files
* *asciidoc-loader*: Default to latest version of component when resolving a page reference
* *playbook-builder*: Set file and dir properties on playbook model
* *playbook-builder*: Make playbook file optional (still required by CLI)
* Switch Gulp build from minimist to yargs-parser for parsing CLI arguments

=== Fixed

* *content-aggregator*: Clean value of start path on content source data
* *content-aggregator*: Make URI and drive letter regular expressions more accurate

== 1.0.0-alpha.4 (2018-01-28)

=== Changed

* Fixed release process to publish README in correct format

== 1.0.0-alpha.3 (2018-01-28)

=== Added

* *site-publisher*: First release of component
* *content-aggregator*: Recognize HEAD and . in playbook as placeholder for current branch
* Update installations instructions in README to cover Windows
* Add AppVeyor CI build for testing on Windows
* Configure CI to automate releases
* Document in README how to use serve package to preview site through local web server
* Document the base build tools required on Linux and macOS in README

=== Changed

* *content-aggregator*: Only select git references which are branches
* *ui-loader*: Switch from download to got
* Replace chai-as-promised with async/await in test suite

=== Fixed

* Make code portable to Windows
* Compute correct URL path for self-referencing index page

== 1.0.0-alpha.2 (2018-01-28)

* Release failed to complete

== 1.0.0-alpha.1 (2018-01-12)

* Initial alpha release
