= Contributing
// Settings:
:toc-title: Contents
:toclevels: 1
:toc:
// Project URIs:
:uri-org: https://gitlab.com/antora
:uri-project: {uri-org}/antora-direct
:uri-repo: {uri-project}.git
:uri-issue-board: {uri-project}/boards/368796
:uri-issue-labels: {uri-project}/labels
// External URIs:
:uri-git: https://git-scm.com
:uri-git-dl: {uri-git}/downloads
:uri-gulp: https://gulpjs.com
:uri-node: https://nodejs.org
:uri-nodegit: http://www.nodegit.org
:uri-nodegit-dev: http://www.nodegit.org/guides/install/from-source
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-yarn: https://yarnpkg.com
:uri-mocha: https://mochajs.org/
:uri-chai: http://chaijs.com/api/bdd/
:uri-istanbul: https://istanbul.js.org/
:uri-chai-as-promised: https://github.com/domenic/chai-as-promised
:uri-chai-spies: https://github.com/chaijs/chai-spies

== You're Invited

In the spirit of open source software, *everyone* is welcome to contribute to this project!

We believe strongly that developing software in the open produces the best outcome.
In order for that to work, the project relies on your support.
We have big goals for the project and we need a variety of talent to achieve those goals.

The best way to get involved is to just show up and make yourself heard.
We pride ourselves on having a very friendly and encouraging culture.

Whether you're a user, writer, designer, developer, architect, devops, system administrator, advocate, project manager, or just someone with an idea about how to improve the project, we welcome your participation.
In return, you'll have better software to use that we built together as a community and a great sense of pride for having been a part of making it.

We want your choice to participate in the Antora project to be the start of an exciting and rewarding journey.
From all of us to you, welcome!

== Project Host

This project is hosted on GitLab within the {uri-org}[Antora organization].
This is the official home of the project and all development is done here.

=== Project Resources

The GitLab project provides the following resources for the project:

* git repository
* issue tracker
* merge requests (aka pull requests)
* CI server

=== Permissions Required

You do not need a GitLab.com account to view or clone the issue tracker, read the issues, browse the merge requests, or view the CI results.
However, you do need a https://gitlab.com/users/sign_in[GitLab.com account] to file an issue, submit a merge request, or--if you're a member of the project--push code to the repository.

=== Issue Tracker, Board, and Labels

If you discover an error or omission in the main application code, tests, or documentation, don't hesitate to submit an issue so we can correct it or submit a patch (via a merge request) for review.

A merge request should always addressing an open issue.
If an issue does not yet exist for the change you're submitting, please create one first.
Use the following commit message template when submitting a fix:

....
resolves #issue_number summarize the issue

* explanation of change if necessary
* more explanation of change if necessary
....

Please study the {uri-issue-labels}[issue labels] to understand what they mean and how to apply them.
Issues are organized into categories, represented by the part of the label text in brackets.

You can use the {uri-issue-board}[issue board] to track the progress of development (which visualizes labels in the [Status] category).
Issues move across the board from left (Backlog) to right (Done).

== Project Organization

Antora Direct is a JavaScript project organized and packaged as a Node.js module.
This section describes the organization of the project at a high level so you know where to look for files.

=== Project Structure

Here are some of the files and directories you will see when developing this project:

....
package.json  <1>
yarn.lock     <2>
gulpfile.js   <3>
lib/          <4>
  index.js    <5>
node_modules/ <6>
packages/     <7>
  playbook/
    lib/      <8>
    tests/    <8>
tests/        <9>
docs/         <10>
  content/
    user-manual.adoc
  assets/
  samples/
....
<1> Defines project information and library dependencies.
<2> Tracks the version of resolved dependencies to ensure builds are reproducible.
<3> The Gulp build script that defines tasks used for development.
<4> The application code folder.
<5> The entry point of the application.
The code in this file assembles and executes the documentation pipeline.
<6> A local installation of Node.js modules used for the development of this project.
<7> Discrete software components used in the documentation pipeline.
These packages are located in this repository while incubating.
They will eventually graduate and migrate to their own repositories.
<8> The main and test code for the playbook component.
<9> Integration tests for the whole documentation pipeline.
These tests verify that the discrete software components work properly together.
<10> The documentation for Antora Direct.
Documentation for discrete software components will live with the code.

The application code is organized by component or function.
We want to avoid having folders that become dumping grounds for source files.
Instead, each source file should be located in a self-describing location.

Tests should mirror the structure of the application code to make it easy for developers to find the tests that correspond to the application code.

=== Incubating Packages

We envision that each software component will eventually graduate to become a package (i.e., Node.js module) hosted in a dedicated repository.
However, making this split too early can make it difficult to get started.
Therefore, we will incubate these packages in the packages folder inside this repository.
When a component is ready for a first release, we will graduate it to a separate repository and add it as a dependency to this project.

== Development

This section gives you all the necessary information you need to set up your development workspace and begin hacking on the code.

=== Prerequisites

In order to obtain the source code, run the test suite, and launch the application, you'll need the following prerequisites:

* git
* Node.js / npm
* Yarn
* Gulp (CLI only)
* Development libraries (e.g., a C compiler)

The following sections describe the prerequisites in detail and provide resources or instructions about how to install them.

==== git

The source code of the project is hosted in a git repository.
The first software you'll need on your machine is git (command: `git`).
You'll use git to obtain the source code and push updates to it.

First, check if you have git installed.

 $ git --version

If not, {uri-git-dl}[download and install] the git package for your system.

==== Node.js / npm

Antora is built on {uri-node}[Node.js] (herein Node) (command: `node`).
To work with the project, you must have Node installed on your machine.
The Node installation also provides npm (command: `npm`), which you'll use to install additional Node modules.

To see which version of Node you have installed, open a terminal and type:

 $ node --version

If `node --version` doesn't return any information, you don't yet have Node installed.

The minimum required version of Node is *v7.10.1*, as indicated in the [.path]_package.json_ file.
This is also the recommended version of Node for development.

.Why Node 7?
****
This project leverages the latest and greatest features of ECMAScript, namely ECMAScript 2016 (ES2016, or ES7 for short).
The main feature of ES7 this project depends on is the `await` keyword since it drastically simplifies asynchronous code.
That's why this project requires at least Node v7.10.1.

NOTE: We don't recommend using Node 8 at this time since it's not officially supported by one of the main dependencies of the project, NodeGit.
Nodegit is the git integration library used to fetch files form the content repositories.
Once Node 8 is officially supported by NodeGit, we'll consider bumping the recommended version of Node.
****

If you don't yet have Node installed, or the version of Node you have isn't Node 7, we strongly recommend using {uri-nvm}[nvm] (Node Version Manager) to manage your Node installations.
Follow the {uri-nvm-install}[nvm installation instructions] to set up nvm on your machine.

TIP: Many CI environments use nvm to install the version of Node used for the build job.
By using nvm, you can closely align your setup with the environment that is used to generate and publish the production site.

Once you've installed nvm, open a new terminal and install Node 7 using:

 $ nvm install 7

The above command will install the latest version of Node 7.


If you already have other Node versions installed, you can configure Node 7 as the default for any new terminal.

 $ nvm alias default 7

You can skip this step if you didn't previously have any Node versions installed because `nvm install` automatically adds the default alias to the first version of Node you install.

Verify the version of Node you have selected using:

 $ node --version

The rest of the software you need is installable from Node (specifically npm).

==== Yarn

{uri-yarn}[Yarn] (command: `yarn`) is the preferred package manager and script runner for the Node ecosystem.

You'll use the `npm` command (part of Node) to install Yarn.
You should install Yarn globally, which resolves to a location in your user directory if you're using nvm, using:

 $ npm install -g yarn

Verify Yarn is installed by checking the version:

 $ yarn --version

If you see a version, you're all set.

==== Gulp (CLI only)

This project uses {uri-gulp}[Gulp] (command: `gulp`) to manage various tasks, such as test, lint, etc.
These tasks are defined in [.path]_gulpfile.js_.

To launch these tasks, you need to install the CLI interface for Gulp using:

 $ yarn global add gulp-cli

The gulp-cli module provides the `gulp` command.
You can verify this command is on your path using:

 $ gulp --version

If you see a version, you're all set.

==== Development Libraries

Some Node packages require development libraries, such as a C compiler, to be available on your machine.
It's very likely you already have these libraries.
If for some reason you don't, namely if you run into problems installing NodeGit, you can return to this section to satisfy this prerequisite.

In order for Yarn to install NodeGit, you need to have the development tools (i.e., a C compiler) installed on your machine.
Details about how to get these libraries can be found in the *Installing Dependencies* section of the page {uri-nodegit-dev}[Building NodeGit from source].

=== Obtain the Source Code

The next step is to obtain the source code of the project, which you'll do by cloning the git repository.

Clone the source repository using:

[subs=attributes+]
 $ git clone {uri-repo} &&
   cd "`basename $_`"

You can copy and paste the above command directly into your terminal.
The command will clone the repository, then switch to the newly created project folder.

=== Install Dependencies

Initializing the project means downloading and installing the dependencies (i.e., the required software) for the project.
That's the job of Yarn.

In your terminal, execute the following command from the root folder of the project:

 $ yarn

The default command in Yarn is `install`, so running `yarn` by itself is the equivalent of running `yarn install`.
The install command uses dependency information defined in [.path]_package.json_ and [.path]_yarn.lock_ to resolve dependencies, which Yarn then installs inside the project under the [.path]_node_modules_ folder.

NOTE: If you run into problems while installing dependencies, return to <<Development Libraries>>.

=== Build the Project

To build this project, which means runs all the main tasks, use:

 $ gulp build

You can omit the `build` argument since it's the default command:

 $ gulp

=== Run the Test Suite

This project uses {uri-mocha}[mocha] to run the tests and the assertion library {uri-chai}[chai].
To run the test suite, use:

  $ yarn test

Note that this command also computes a coverage report using {uri-istanbul}[istanbul].
You can browse this report in a web browser by opening this HTML file: `coverage/index.html`.

You can run selective parts of the test suite by adding `.only` on `describe()` and/or `it()`.
You can find more details here: https://mochajs.org/#exclusive-tests

You can skip some parts of the test suite by adding `.skip` on `describe()` and/or `it()`.
You can find more details here: https://mochajs.org/#inclusive-tests

=== Expectations When Writing Tests

If you need to add a new test to the suite, you can use `test/capitalize-test.js` as a reference.
It already follows the structure of the project and contains various comments and hints to help you.
Be sure to follow the directions on what to require and the different traps to avoid.

Apart from the classic {uri-chai}[chai] assertions, two plugins are enabled, you'll find the documentation for their APIs here:

* {chai-as-promised}[chai-as-promised] to test promises
* {chai-spies}[chai-spies] to create and test spies on callbacks

If you're working on tests or refactoring tested code, you can run the test suite continuously, using:

  $ yarn run test-watch

This will run the test suite each time you modify the code or the test

=== Fork the Project

WRITEME

=== Submit a Merge Request

WRITEME

=== Coding Style: Guidelines and Expectations

WRITEME
