= Contributing
// Settings:
:toc-title: Contents
:toclevels: 1
:toc:
// Project URIs:
:uri-org: https://gitlab.com/antora
:uri-project: {uri-org}/antora
:uri-repo: {uri-project}
:uri-issue-tracker: {uri-project}/issues
:uri-issue-board: {uri-project}/boards/368796
:uri-issue-labels: {uri-project}/labels
:uri-ci-pipelines: {uri-project}/pipelines
:uri-adrs: {uri-project}/tree/master/docs/modules/architecture/documents/adr
:uri-adr-0001: {uri-project}/blob/master/docs/architecture/content/adr/0001-minimum-node-version.adoc
:uri-asciidoc-loader-arch: {uri-project}/blob/master/packages/asciidoc-loader/devdocs/architecture-guidebook.adoc
:uri-content-aggregator-arch: {uri-project}/blob/master/packages/content-aggregator/devdocs/architecture-guidebook.adoc
:uri-content-classifier-arch: {uri-project}/blob/master/packages/content-classifier/devdocs/architecture-guidebook.adoc
:uri-document-converter-arch: {uri-project}/blob/master/packages/document-converter/devdocs/architecture-guidebook.adoc
:uri-page-generator-arch: {uri-project}/blob/master/packages/page-generator/devdocs/architecture-guidebook.adoc
:uri-playbook-builder-arch: {uri-project}/blob/master/packages/playbook-builder/devdocs/architecture-guidebook.adoc
:uri-ui-loader-arch: {uri-project}/blob/master/packages/ui-loader/devdocs/architecture-guidebook.adoc
// External URIs:
:uri-async-func: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
:uri-git: https://git-scm.com
:uri-git-dl: {uri-git}/downloads
:uri-gulp: https://gulpjs.com
:uri-node: https://nodejs.org
:uri-nodegit: http://www.nodegit.org
:uri-nodegit-dev: http://www.nodegit.org/guides/install/from-source
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-yarn: https://yarnpkg.com
:uri-mocha: https://mochajs.org/
:uri-chai: http://chaijs.com/api/bdd/
:uri-istanbul: https://istanbul.js.org/
:uri-chai-as-promised: https://github.com/domenic/chai-as-promised
:uri-chai-spies: https://github.com/chaijs/chai-spies
:uri-standardjs: https://standardjs.com/
:uri-standardjs-rules: https://standardjs.com/rules.html
:uri-eslint-ide: https://eslint.org/docs/user-guide/integrations#editors
:uri-prettier: https://github.com/prettier/prettier

== You're Invited!

In the spirit of open source software, *everyone* is welcome to contribute to this project!

We believe strongly that developing software in the open produces the best outcome.
In order for that to work, the project relies on your support.
We have big goals for the project and we rely on a variety of talent to achieve those goals.

The best way to get involved is to just show up and make yourself heard.
We pride ourselves on having a very friendly and encouraging culture.

Whether you're a user, writer, designer, developer, architect, devops, system administrator, advocate, project manager, or just someone with an idea about how to improve the project, we welcome your participation.
In return, you'll get to use better software that we built together as a community and a great sense of pride for having been a part of making it.

We want your choice to participate in the Antora project to be the start of an exciting and rewarding journey.
From all of us to you, welcome!

== Project Host

This project is hosted on GitLab under the {uri-org}[Antora organization].
This is the official home of the project.
All development, project and issue management, and continuous integration is done here.

////
=== Project Resources

The GitLab project provides the following resources for the project:

* git repository
* issue tracker
* merge requests (MR)
* CI server
////

== Permissions

You do not need a GitLab.com account to browse the issues and merge requests, read the source code and documentation, or view the CI results.
However, you do need a https://gitlab.com/users/sign_in[GitLab.com account] to file an issue and submit a merge request.

//Issue Tracker and Board
//== Have an Idea? Found an Error?
== Have something to report?

Do you have an idea?
Have you found an error?

*Antora is an issue-driven project.*

If you have an idea for an improvement or have discovered an error or omission, head over to the {uri-issue-tracker}[issue tracker].
Review the list of issues to check if someone has already filed an issue about that subject.
If an issue already exists, we welcome you to join the conversation.
If an issue doesn't exist, please don't hesitate to create a new one.

If you want to help complete an issue by contributing code, documentation, or other enhancements, review our <<contribution-workflow,contribution workflow>>, then submit a merge request (MR) for review.


////
A merge request (MR) must close an issue!
Please study the {uri-issue-labels}[issue labels] to understand what they mean and how to apply them.
Issues are organized into categories, represented by the part of the label text in brackets.

You can use the {uri-issue-board}[issue board] to track the progress of development (which visualizes labels in the [Status] category).
Issues move across the board from left (Backlog) to right (Done).
////

[#contribution-workflow]
== Contribution Workflow

*Since Antora is an issue-driven project, a merge request (MR) should always complete an open issue.*

. Review the issue tracker to see if we're already discussing your idea or problem.
.. If you don't see an issue that fits your scenario, then create a new one.
. If you'd like to submit code, documentation or other enhancements for an issue, review the following information first.
.. Antora's <<project-rq,fork-branch-commit-MR rules>>
.. <<code-workflow,Code workflow and requirements>>
.. Applicable <<arch-gb,architecture guidebooks>>
.. Applicable <<adr,ADRs>>
. Fork the project and name your branch after its issue.
.. If you're contributing code, you'll want to <<set-up-workspace,set up your development workspace>>.
. Write, code, tinker, and have fun!
.. Don't forget to <<lint-rq,lint>> and <<test-rq,test>> your code.
. When you're ready for feedback, open a MR.

[#project-rq]
== Fork, Branch, Commit, and Merge Request Rules

To contribute to the project:

. *Fork the project*.
We do not accept merge requests that do not come from a fork and dedicated branch.

. *Create a dedicated branch in your fork for your changes*.
Name the branch after the issue number it fixes along with a short textual hint.
Here's an example of a branch name for issue #2, which was to initiate the Gulp build:
+
 issue-2-init-gulp-build

. In the issue tracker, mark the issue as *[Status] In Progress* and make sure you're assigned to it so that the rest of the team knows you're working on it.

. *Write concise but explicit commit messages*.
Write the commit message as though the person reading it cannot see the code change.
 .. Write the message in lowercase and imperative tense.
 .. Put the subject on the first line of the commit message (required).
 .. Separate the subject line from the body using a blank line.
 .. The body lines should be structured as an unordered list (Markdown syntax).
 .. In each body line, succinctly identify an important change and/or explain why the change was made (optional).
+
----
rename component descriptor filename to antora.yml

- rename component descriptor from docs-component.yml to antora.yml
- promote component descriptor filename to a constant
----

. Prior to submitting a MR, *rebase your branch against the latest master*, then push the branch to your fork.

. *Create an MR from your branch* (using the URL shown in the terminal when you push).
.. *Begin the title of the MR with the issue it resolves* followed by a restatement of the issue.
+
 resolves #2 initialize gulp build

.. If you're still working on your branch and want feedback on it before it is complete, start the MR with WIP (e.g., `WIP: resolves #2 initialize gulp build`).
When the MR is ready for final review, you can remove `WIP:` from the MR title using the button in the interface.
.. In some select cases, the implementation of an issue might be broken up into separate commits if they can be tested and work in isolation.
This is why only the MR subject mentions the issue being resolved and not the subject of the commit.

. In the issue tracker, mark the issue as *[Status] Merge Requested*.

. *Your MR must pass the CI pipeline*.
If it fails, update your MR once you've corrected any problems.

. *A project member will be assigned to your MR and review it*.
.. During review, a project member may request changes to your MR, either in a comment on the MR or the associated issue.
.. Checkout the <<mr-approval,MR approval guidelines>> if you want to see how your MR will be evaluated.

. *Append a new commit or rewrite an existing commit*, depending on what you think is most appropriate, if you need to incorporate changes into your MR after you've pushed it.

. When your MR is approved, a project member will merge it using a merge commit with semi-linear history.
.. The maintainer may decide to squash review commits, or request for you to do so.
Only original work is guaranteed to be preserved in the commit history.

.Future: Commit message linting
****
We're experimenting with the wording and structure of our commit messages and plan to implement a set of commit message rules in the future.
****

[#code-workflow]
== Coding Requirements and Workflow

. Set up your <<set-up-workspace,development workspace>>.
. Review any applicable <<arch-gb,architecture guidebooks>>.
. Make sure you're not violating any <<adr,ADRs>>.
. Make sure you've forked the project and <<project-rq,named your branch after the issue you're working on>>.
. Add your code and tests.
.. Make sure your code adheres to the <<lint-rq,JavaScript standard style and the custom project styles>>.
.. Make sure your tests adhere to the <<test-rq,test requirements>>.
. Update the API documentation.
. Update the applicable architecture guidebooks if your code significantly changes a package's inputs, outputs or primary functionality.
. Run the <<run-tests,test suite>> (which also lints the code) and correct any errors.
. Commit your changes.
. <<run-prettier,Run prettier>>.
+
WARNING: Prettier's format task will modify your files, so be sure to commit your changes before running it so you can review and rollback if necessary.

. Commit any formatting changes completed by prettier.
. Push to your fork and open a merge request.

[#adr]
=== Architecture Decisions Records

Significant project and technology decisions are outlined in our architecture decision records (ADRs).

The {uri-adrs}[ADRs] are numbered in the order they were proposed.

A new ADR should be proposed prior to adding, removing, upgrading or significantly changing software dependencies, frameworks, tools, environments, infrastructure, or CI, CD, and release processes.
A new ADR should also be proposed when considering major administrative, resource, and scope changes to the Antora organization.

[#arch-gb]
=== Component Architecture Guidebooks

Each Antora component has an architecture guidebook.
A guidebook provides an overview of why the component is important and why it's structured as it is.
It outlines:

* the problem a component solves
* its high-level functionality
* its inputs and outputs
* important code, API, and data model requirements
* the consequences of the functions and requirements on the Antora pipeline

Before contributing to a component, make sure you are familiar with its guidebook.
If you make a significant modification to a package, you should also update the guidebook if applicable.

.List of Architecture Guidebooks
[%hardbreaks]
{uri-playbook-builder-arch}[Playbook Builder]
{uri-content-aggregator-arch}[Content Aggregator]
{uri-content-classifier-arch}[Content Classifier]
{uri-asciidoc-loader-arch}[AsciiDoc Loader]
{uri-document-converter-arch}[Document Converter]
{uri-ui-loader-arch}[UI Loader]
{uri-page-generator-arch}[Page Generator]

[#lint-rq]
=== Code structure and style expectations

We read code more than we edit it, so it's important to have consistency throughout the code base.

Antora's JavaScript code must adhere to the {uri-standardjs}[JavaScript Standard Style].
We've modified a few of the standard style rules (e.g., max-len) and added some custom ones (e.g., comma-dangle, arrow-parens).
The style rules are enforced using eslint with a tailored StandardJS profile.
The code is formatted using prettier, which applies fixes for the standard style rules as well as a few of its own.

==== eslint and prettier

You can find a {uri-standardjs-rules}[list of rules] on the standard JS site.
We don't use the StandardJS command line tool.
We use its rules and configuration through ESLint.
There are {uri-eslint-ide}[text editor plugins for ESLint] that you can use, if that's what you prefer.
We have modified some of the standard rules and added custom rules, which are documented in [.path]_.eslintrc_.

While not enforced by eslint yet, your code should also comply with the following rules:

* Use SCREAMING_SNAKE_CASE for constant names (not any `const` declaration, but rather a formal constant).
// * we might consider defining all constants for a package in lib/constants.js
* Keep all require declarations together at the top of the file (no blank lines), and sort them alphabetically, unless there's a reason they can't be.
* Functions should be defined using the `function` keyword in main code and using `const` with a function shorthand `const fn = () => {}` in tests.
// * TODO enforce `fn () { }` (see https://eslint.org/docs/rules/func-style)
* Functions should be defined at the top of the source file and exports at the bottom.

When you <<run-tests,run the test suite>>, it will automatically lint (i.e., style check) your JavaScript code first.

If you ever want to run the linter separately, you can use the following gulp task:

 $ gulp lint

While ESLint checks for syntax, it doesn't cover all the aesthetics of a code style.
We employ {uri-prettier}[prettier] to automatically format the code.
Run prettier *after* you commit all your code changes as the format task will modify your files.

To run prettier, enter the following gulp task:

 $ gulp format

[#test-rq]
=== Test structure and coverage expectations

Tests should mirror the structure of the application code to make it easy for developers to find the tests that correspond to the application code.

If you need to add a new test to the suite, you can use [.path]_test/example-test.js_ as a reference.
It already follows the structure of the project and contains various comments and hints to help you.
Be sure to follow the directions on what to require and various traps to avoid.

Apart from the classic {uri-chai}[chai] assertions, two plugins are enabled.
You'll find the documentation for their APIs here:

* {uri-chai-as-promised}[chai-as-promised] to test promises
* {uri-chai-spies}[chai-spies] to create and test spies on callbacks

You can run the whole <<run-tests,test suite>> manually or continuously.
You can also select specific tests to run.

== Project Organization

Antora is a JavaScript project organized and packaged as a set of Node.js packages.
This section describes the organization of the project at a high level so you know where to look for files.

=== Project Structure

Here are some of the files and directories you will see when developing this project:

....
docs/         <1>
lib/          <2>
  index.js    <3>
lib-example/
  capitalize.js
node_modules/ <4>
packages/     <5>
  content-aggregator/ <6>
    devdocs/
      architecture-guidebook.adoc
    lib/
    node_modules/ <4>
    test/
    package.json
  content-classifier
  document-converter/
  navigation-builder/
  ...
tasks/
test/         <7>
gulpfile.js   <8>
package.json  <9>
yarn.lock     <10>
....
<1> The end user documentation for Antora.
<2> The application code folder.
<3> The entry point of the application.
The code in this file assembles and executes the documentation pipeline.
<4> A local installation of Node.js modules used for the development of this project.
<5> Discrete software components used in the documentation pipeline.
<6> The main code, test code, and architecture documentation for the content aggregator component.
Developer documentation for discrete software components lives with the code.
<7> Integration tests for the whole documentation pipeline.
These tests verify that the discrete software components work properly together.
<8> The Gulp build script that defines tasks used for development.
<9> Defines project information and library dependencies.
<10> Tracks the version of resolved dependencies to ensure builds are reproducible.

[#set-up-workspace]
== Development Workspace Setup

This section gives you all the information you need to set up your development workspace and begin hacking on the code.

=== Prerequisites

In order to obtain the source code, run the test suite, and launch Antora, you'll need the following prerequisites:

* git
* Node.js / npm
* Yarn
* Gulp (CLI only)
* Development libraries (e.g., a C compiler)

The following sections describe the prerequisites in detail and provide resources with additional instructions about how to install them.

==== git

The source code of the project is hosted in a git repository.
The first software you'll need on your machine is git (command: `git`).
You'll use git to obtain the source code and push updates to it.

First, check if you have git installed.

 $ git --version

If not, {uri-git-dl}[download and install] the git package for your system.

==== Node.js / npm

Antora is built on {uri-node}[Node.js] (herein Node) (command: `node`).
To work with the project, you must have Node installed on your machine.
The Node installation also provides npm (command: `npm`), which you'll use to install additional Node modules.

To see which version of Node you have installed, open a terminal and type:

 $ node --version

If `node --version` doesn't return any information, you don't yet have Node installed.

The minimum required version of Node is *8.0.0*, as indicated in [.path]_package.json_, though we recommend using the latest release in the 8.x series.
This is also the recommended version of Node for development.

.Why Node 8?
****
This project leverages the latest and greatest features of ECMAScript, namely ECMAScript 2017 (ES2017).
The main feature of ES2017 this project depends on is the {uri-async-func}[Async Function] (which introduced the `async` and `await` keywords).
This feature drastically simplifies our asynchronous code.

Node 8 is the first long-term support (LTS) release that provides this feature, which is why it's defined as the prerequisite.
You can read more about the decision to set Node 8 as the minimum required version in {uri-adr-0001}[ADR 0001: Minimum Node Version].
****

If you don't yet have Node installed, or the version of Node you have isn't Node 8, we strongly recommend using {uri-nvm}[nvm] (Node Version Manager) to manage your Node installations.
Follow the {uri-nvm-install}[nvm installation instructions] to set up nvm on your machine.

TIP: Many CI environments use nvm to install the version of Node used for the build job.
By using nvm, you can closely align your setup with the environment that is used to generate and publish the production site.

Once you've installed nvm, open a new terminal and install Node 8 using:

 $ nvm install 8

The above command will install the latest version of Node 8.

If you already have other Node versions installed, you can configure Node 8 as the default for any new terminal.

 $ nvm alias default 8

You can skip this step if you didn't previously have any Node versions installed because `nvm install` automatically adds the default alias to the first version of Node you install.

Verify the version of Node you have selected using:

 $ node --version

The rest of the software you need is installable from Node (specifically npm).

==== Yarn

{uri-yarn}[Yarn] (command: `yarn`) is the preferred package manager and script runner for the Node ecosystem.

You'll use the `npm` command (part of Node) to install Yarn.
You should install Yarn globally, which resolves to a location in your user directory if you're using nvm, using:

 $ npm install -g yarn

Verify Yarn is installed by checking the version:

 $ yarn --version

If you see a version, you're all set.

==== Gulp (CLI only)

This project uses {uri-gulp}[Gulp] (command: `gulp`) to manage various tasks, such as test, lint, etc.
These tasks are defined in [.path]_gulpfile.js_.

To launch these tasks, you need to install the CLI interface for Gulp using:

 $ npm install -g gulp-ci

The gulp-cli module provides the `gulp` command.
You can verify this command is on your path using:

 $ gulp --version

If you see a version, you're all set.

==== Development Libraries

Some Node packages require development libraries, such as a C compiler, to be available on your machine.
It's very likely you already have these libraries.
If for some reason you don't, namely if you run into problems installing NodeGit, you can return to this section to satisfy this prerequisite.

In order for Yarn to install NodeGit, you need to have the development tools (i.e., a C compiler) installed on your machine.
Details about how to get these libraries can be found in the *Installing Dependencies* section of the page {uri-nodegit-dev}[Building NodeGit from source].

=== Obtain the Source Code

The next step is to obtain the source code of the project, which you'll do by cloning the git repository.
*Remember to fork the repository.*

Clone the source repository using:

[subs=attributes+]
 $ git clone {uri-repo} &&
   cd "`basename $_`"

You can copy and paste the above command directly into your terminal.
The command will clone the repository, then switch to the newly created project folder.

=== Install Dependencies

Initializing the project means downloading and installing the dependencies (i.e., the required software) for the project.
That's the job of Yarn.

In your terminal, execute the following command from the root folder of the project:

 $ yarn

The default command in Yarn is `install`, so running `yarn` by itself is the equivalent of running `yarn install`.
The install command uses dependency information defined in [.path]_package.json_ and [.path]_yarn.lock_ to resolve dependencies, which Yarn then installs inside the project under the [.path]_node_modules_ folder.

NOTE: If you run into problems while installing dependencies, return to <<Development Libraries>>.

[#build-project]
=== Build the Project

To build Antora, which means running all the main tasks, use:

 $ gulp build

You can omit the `build` argument since it's the default command:

 $ gulp

[#run-tests]
=== Run the Test Suite

This project uses {uri-mocha}[mocha] to run the tests and the assertion library {uri-chai}[chai].
It's also automatically configured to lint your JavaScript code, which it does first when the suite is run.

To run the test suite, use:

 $ gulp test

If you don't want the `lint` task to run before running the tests, add `!` to the end of the task name:

 $ gulp test!

If you want to run the linter separately, you can use the following gulp task:

 $ gulp lint

//FIXME nyc is currently disabled
//This command also computes a coverage report using {uri-istanbul}[istanbul].
//You can browse this report in a web browser by opening the HTML file [.path]_coverage/index.html_.

You can run the test suite for a single package by passing the name of the package to the `--package` flag:

 $ gulp test --package=ui-loader

This filter works for all gulp tasks, including `lint` and `test:watch`, which are covered next.

If you're working on tests or refactoring tested code, you can run the test suite continuously, using:

 $ gulp test:watch

This command runs the test suite (using `test!`) each time you save the test or the code under test.

=== Select or Skip Tests

You can run select tests by appending `.only` to the `describe` and/or `it` method calls (e.g., `it.only()`.
You can read more about this feature in the https://mochajs.org/#exclusive-tests[mocha documentation].

You can skip tests by appending `.skip` to the `describe` and/or `it` method calls (e.g., `describe.skip()`).
You can read more about this feature in the https://mochajs.org/#inclusive-tests[mocha documentation].

[#run-prettier]
=== Run prettier

Prettier isn't automatically run as part of the CI pipeline yet, so you'll need to run it manually prior to pushing your code.
Run prettier *after* you commit all your code changes.
The format task will modify your files, and if you have to modify your code later, the formatting can make this tedious.
By committing your code updates, then running prettier and committing any changes it makes as a separate commit, it'll be easier to rollback the changes if you need to.

To run prettier, enter the following gulp task:

 $ gulp format

=== Continuous Integration

Both the linter and the test suite are run in a continuous integration (CI) environment on every commit to master and on every merge request.
A merge request cannot be merged unless the CI pipeline succeeds.

The CI pipeline is run in the https://docs.gitlab.com/ce/ci/[GitLab CI] environment using the https://store.docker.com/images/node[node:8] docker image.
The pipeline consists of the following stages:

* setup
* verify
 ** lint
 ** test

These stages, as well as any global configuration settings, are defined in the [.path]_.gitlab-ci.yml_ file at the root of the project.
The CI pipeline essentially boils down to these three commands:

* `yarn`
* `gulp lint`
* `gulp test!`

You can view the results of the pipelines on the {uri-ci-pipelines}[pipelines dashboard].

==== Skip the CI Pipeline

If you need to make a change to the repository without triggering the CI pipeline, add `[skip ci]` to the end of the commit message.
For example:

 fix typo in README [skip ci]

This flag is reserved for small, non-software changes, as suggested by the example.

== Project Maintainers

The project maintainers are responsible for:

* managing organization and project permissions
* managing the community and code of conduct
* setting ADR statuses
* merging requests into master
* managing and releasing the pipeline

[#mr-approval]
=== Merge Request Review and Approval Guidelines

Each merge request is assigned at least one reviewer.
The reviewer is responsible for making sure the MR meets the project and issue criteria, for answering questions the contributor may have regarding the MR, and for suggesting ways the MR can be improved if necessary.

*The MR should not be approved if*:

* it fails the CI pipeline
* it doesn't meet the project's workflow, code, test or documentation requirements
* it doesn't meet the acceptance criteria of its associated issue

*If the MR needs to be modified, notify the contributor and add helpful information to the MR or the issue*.
Once the contributor has modified the MR, evaluate it again.

When the MR meets the project and issue criteria, it can be merged into master.
*When the branch is ready to be merged into master*:

* Rebase the MR if necessary.
* Modify the commit message(s) if necessary.
* Check _remove source branch_.
* Don't squash the commits, except in especially messy-weird situations.
** The maintainer only guarantees to preserve the  original work in the MR.
* Modify the default merge commit message; it should only contain two lines.
** The first line should specify the merge number.
** The second line should be the MR subject submitted by the contributor.
For example:
+
----
merge !46

resolves #59 configure lerna and yarn workspaces
----
* Press _Merge_.
