= Antora
// Project URIs:
:uri-project: https://gitlab.com/antora/antora
:uri-ci-pipelines: {uri-project}/pipelines
:img-ci-status: {uri-project}/badges/master/pipeline.svg
// External URIs:
:uri-asciidoctor: http://asciidoctor.org

image:{img-ci-status}[CI Status (GitLab CI), link={uri-ci-pipelines}]

Antora is a modular documentation site generator built on Node and designed for users of {uri-asciidoctor}[Asciidoctor].

More specifically, Antora is a modular Asciidoctor documentation toolchain and workflow that empowers technical writing teams to create, manage, collaborate on, remix, and publish documentation sites sourced from a variety of versioned content repositories without needing expertise in web technologies, build automation, or system administration.

This project includes a predefined software pipeline to quickly get started creating documentation sites using Antora.

== Contributing

To learn how to contribute to this project, including how to link:contributing.adoc#set-up-workspace[set up a development workspace], link:contributing.adoc#build-project[build the project], and link:contributing.adoc#project-rq[submit a merge request], please refer to the link:contributing.adoc[contributing guide].

== Copyright and License

Copyright (C) 2017 OpenDevise Inc. and the Antora Project.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by OpenDevise Inc.
