= Releasing
ifdef::env-browser[]
:toc:
:toc-title: Contents
endif::[]

This document describes how releases of the packages (aka modules) in this repository are versioned and published.

== Quickstart

To publish a release, first make sure the <<Credentials,npm token>> is still valid and that the copyright year is current in README.adoc, packages/*/README.adoc, and docs/modules/ROOT/pages/project/copyright-and-license.adoc.
Then switch to the _releases_ branch, update the [.path]_releaserc_ file, and force push the branch to origin.
The CI job takes over from there.
See <<Release Trigger>> to find more details and step-by-step commands.

The remainder of this document describes how the release process works, including configuration, credentials, and process.

== Overview

Here's what happens when a release is made:

* The version property in [.path]_lerna.json_ and each [.path]_package.json_ file under [.path]_packages/_ is set to the new version.
* The Unreleased section title is in CHANGELOG.adoc is replaced with the release version and current date.
* The changes are committed to the git branch from which the release is made (only changed files are committed).
* An unsigned, annotated tag with the name of the version prefixed with "`v`" (i.e., v1.0.0) is added to the git repository.
* Each package under [.path]_packages/_ is packed and published to the @antora scope of the https://npmjs.com[npm registry].
 ** Publishing to the npm registry also makes the packages available in the https://yarnpkg.com[Yarn registry].
 ** The packages cannot be unpublished from the npm registry once published.
* The tag and corresponding commit on the branch from which the release is made are pushed to "`origin`" remote (i.e., the repository on GitLab).

If the CI pipeline succeeds, we can assume the release was successful.
The logs of the release activity are available through the GitLab CI interface.
The release logic will prevent the same CI job from making another release.

Keep in mind that the release does not update the entries in the CHANGELOG.
It only replaces the Unreleased section title with the release version and current date.
The entries must be added manually, prior to the release.

== Versioning

Version numbers are chosen for releases according to https://semver.org[semantic versioning] rules.
All packages in this repository are released together and thus share a common version.
Changes to the repository as a whole should be considered when selecting the version number for a release.

The current published version is tracked in the file [.path]_lerna.json_ at the root of this repository.
This value is used to generate the next version in the sequence (unless an explicit version is provided).

The version number (e.g., 1.1.0) or increment keyword (e.g., patch) for a release is set using the [.path]_releaserc_ file at the root of the project.
This process is described in detail later.

== Release Process

Releases are published from the CI pipeline by the release job.
The release job is defined in the file [.path]_.gitlab-ci.yml_.
The release job only runs on the "`releases`" branch.
It runs in a phase named "`deploy`" at the end of the CI pipeline.

The release job delegates to https://lernajs.io[Lerna] to perform the release.
The version of Lerna used by the release job is set in the file [.path]_lerna.json_ at the root of this repository.
The call to Lerna is managed by [.path]_scripts/release.sh_, which sets up and tears down the environment in which Lerna runs.

=== Credentials

In order to perform a release, Lerna must be able to:

* publish packages to https://www.npmjs.com[npmjs.com]
* push commits to this git repository

Lerna needs to be able to publish packages using npm.
The auth token for publishing to npmjs.com is stored in the RELEASE_NPM_TOKEN secret variable defined in the CI/CD configuration.
*Make sure this token is still valid before releasing!*
(You can check if the token is registered by running `npm token list`).
Lerna uses this token to authenticate as the release manager (currently https://www.npmjs.com/~mojavelinux[mojavelinux]).
This is done by writing the token to an [.path]_.npmrc_ file inside the folder of each package (e.g., [.path]_packages/cli/.npmrc_).

After the package is published, the tag and the corresponding commit to master must be pushed from the CI job to the git repository.
A dedicated SSH key (with no passphrase) has been generated for this purpose using `ssh-keygen -t rsa -b 4096 -C antora-releases -f antora-releases`.
The private SSH key is stored in the RELEASE_SSH_PRIV_KEY secret variable defined in the CI/CD configuration.
The corresponding public SSH key is registered as a deploy key in the repository configuration.
During the release job, an SSH agent session is started, initialized, and killed by [.path]_scripts/release.sh_.
The private key is read from the RELEASE_SSH_PRIV_KEY environment variable and added to the SSH agent session.
The git client is then configured to push the commits over SSH.

The RELEASE_GIT_NAME and RELEASE_GIT_EMAIL secret variables, also defined in the CI/CD configuration, are used to set the git user (name and email) for the release commits.
The values used are those of the release manager.

The secret variables described in this section are scoped to the releases environment.
The release job associates itself with the releases environment, allowing it to receive the secret variables.

Since we're publishing packages to a scope (i.e., @antora), we have to set `access=public` in [.path]_.npmrc_ in order to successfully publish new packages.
Otherwise, scoped packages are not public by default.

=== README Dance

The npmjs.com registry does not currently support READMEs written in AsciiDoc.
To complicate matters, the npm client doesn't allow the README to be specified explicitly when packaging, and it has an affinity for README.adoc.
Therefore, we have to do some fancy footwork to stuff a Markdown version of the README into the package that's being shipped off to the registry.
Thanks to lerna lifecycle hooks, this is possible.

The release script places two lifecycle scripts into the scripts folder of each package folder during the release process.
These scripts are wrappers that turn around and invoke the following two scripts:

* https://gitlab.com/antora/antora/blob/master/scripts/prepublish.js[prepublish.js]
* https://gitlab.com/antora/antora/blob/master/scripts/postpublish.js[postpublish.js]

In the *prepublish* script, the [.path]_README.adoc_ file is moved out of the way, its contents are transformed to Markdown and saved as [.path]_README.md_.
The packaging script then picks up the generated [.path]_README.md_ file and bundles it with the package (ignoring the hidden README.adoc).

The *postpublish* script restores the original state by removing the [.path]_README.md_ file and moving [.path]_README.adoc_ back into place.
As a result, the npm registry displays the Markdown version of the README, but we get to maintain the content in AsciiDoc format.

=== Version Selection

By default, Lerna is configured to select the next prerelease version in the sequence when selecting the version number.
This can be overridden using a [.path]_releaserc_ file.

The version number or increment keyword for a release can be set using the [.path]_releaserc_ file at the root of the project.
This value is specified by defining the RELEASE_VERSION shell variable.
For example:

.releaserc
[source,bash]
----
RELEASE_VERSION=patch
----

Lines containing other data, such as a date, are ignored, but may be added for informational purposes.

If the value assigned to the RELEASE_VERSION variable matches one of the increment keywords (major, minor, patch, premajor, preminor, prepatch, prerelease), that value is passed to Lerna's `--cd-version` option.
Consult the Lerna documentation for details about how these values determine the next version number.
Otherwise, the value is assumed to be an explicit version number, which is used as is by passing it to Lerna's `--repo-version` option.

If the RELEASE_NPM_TAG variable is set, its value is passed to Lerna's `--npm-tag` option.
This setting can be used to publish releases that do not get installed by default (e.g., prereleases).
If the RELEASE_NPM_TAG variable is not set, and the RELEASE_VERSION beings with `pre` or contains a hyphen, the RELEASE_NPM_TAG variable defaults to `testing`.
Otherwise, it defaults to `latest`.
To override these defaults, set the RELEASE_NPM_TAG shell variable in the [.path]_releaserc_ file.
For example:

.releaserc
[source,bash]
----
RELEASE_VERSION=2.0.0-alpha.1
RELEASE_NPM_TAG=preview
----

The [.path]_releaserc_ file can also control the branch from which the release will be cut.
But default, the release is cut from the master branch.
To override this default, set the RELEASE_BRANCH shell variable in the [.path]_releaserc_ file.
For example:

.releaserc
[source,bash]
----
RELEASE_VERSION=patch
RELEASE_BRANCH=1.x
----

CAUTION: If you release from a branch other than master, you'll need to carry over the change that the release scripts makes to the CHANGELOG to the master branch manually in order to retain a continuity of releases.

Modifying the [.path]_releaserc_ file is the central mechanism for triggering a release, as covered in the next section.

=== Release Trigger

A release is made from the release branch, which is the branch from which the release is being cut.
A branch named "`releases`" has been reserved for performing the release.
The release is triggered by pushing a new commit to the releases branch.

The steps to perform a release are as follows:

. Rebase the releases branch on top of the release branch (e.g., master).
. Update the [.path]_releaserc_ file, if necessary (typically to set the release version).
 ** The commit message on the release branch is arbitrary, but can be something like "`cut release`".
. Force push the branch.

The releases branch must be ahead of the release branch (the branch from which the release is being made).
In other words, the common fork point between the release branch and releases branches must be the HEAD of the release branch.
If this is not the case, the release job will refuse to publish the release.

(Unfortunately, that means the branch cannot be protected).

Here are the steps in the form of a commands:

 $ git fetch origin
   git rebase origin/master
   git commit --amend --date="$(date)" -m "cut release" releaserc
   git push --force origin releases

This commit activates the release job in the CI pipeline.
This job is configured to only run on the releases branch.
The release job immediately clones the release branch and performs the release from there.
Thus, the releases branch is merely a utility.

//NOTE: In the future, we may decide to add multiple release branches, one for each version line (e.g., 1.x, 2.x, master, etc.)

In summary, the releases branch is used to:

* trigger the CI pipeline
* pass release instructions via the [.path]_releaserc_ file
* track whether a release has already been performed from a given CI pipeline (by examining the fork point)
 ** this prevents the CI pipeline from being inadvertently run again

The CI job will publish the packages to npmjs.com at the end of the job execution.

=== Post Release Trigger

Once the release completes, the job to build the Docker image is automatically triggered.
The version of the Docker image matches the latest version of Antora.
The Docker image will be tagged `testing` if the release number contains a hyphen.
Otherwise, it will be tagged `latest` (the default version).

== Testing a Release

It's possible to test the release locally using a private npm registry.
This section briefly describes how.

=== Set Up a Private Npm Registry

You can run a private npm registry on your own machine using http://www.verdaccio.org[Verdaccio].

Verdaccio is available as an npm package.
To install Verdaccio, run the following command:

 $ npm i -g verdaccio

You'll then need to create a user for publishing packages.
First, start Verdaccio using the `verdaccio` command:

 $ verdaccio

Verdaccio runs at http://localhost:4873 by default.
You can visit this URL to see what packages have been installed.
(Of course, there's nothing there yet!)

Next, create a user using the `npm adduser` command (assuming the default port):

 $ npm adduser --registry http://localhost:4873

You'll never need to login as this user.
This just adds an auth token for localhost:4873 to the [.path]_~/.npmrc_ file that the npm client will use for publishing to this registry.

Next, we'll need to disable the proxy for the `@antora` scope so that we can test locally without interfering with or getting interference from the released packages.

First, stop Verdaccio.
Then, open the file [.path]_~/.config/verdaccio/config.yaml_, add the entry under the `packages:` key, and save it.

[source,yml]
----
  '@antora/*':
    access: $all
    publish: $authenticated
----

=== Run the Private Npm Registry

You must start Verdaccio in order to use it for publishing:

 $ verdaccio

=== Prepare the Clones

Now we need to prepare two clones so that they are configured as the release repository (test-release-from) and the upstream repository (test-release-to).
This ensures that you can perform a full publish without affecting the real repository.

Start by cloning the repository to use as the upstream target:

 $ git clone git@gitlab.com:antora/antora.git test-release-to
   cd test-release-to

Next, switch to another branch so the master branch can receive commits and we have something to come back to:

 $ git checkout -b current
   cd ..

Next, clone the repository from which you will perform the release:

 $ git clone git@gitlab.com:antora/antora.git test-release-from
   cd test-release-from

Next, change the remote origin to point to our local (fake) target:

 $ git remote set-url origin ../test-release-to

Confirm this is set up correctly by doing an empty push:

 $ git push origin master

=== Perform a Local Release

Now you are ready to perform a local release.
Switch to the [.path]_test-release-from_ repository and run:

 $ npm_config_registry=http://localhost:4873 \
   lerna publish --cd-version=prerelease --exact --force-publish=*

If you've set up everything correctly, this will not affect the official repository and won't publish anything to npmjs.com.

Verify that the packages have been published to the private npm registry by visiting http://localhost:4873.

=== Reverting a Release

The beauty of testing locally is that you can revert a release.
Here's how to do it.

Start by purging the packages from the private npm repository:

 $ for package in `find packages -mindepth 1 -maxdepth 1 -printf "%f\n"`; do
     npm --registry http://localhost:4873 unpublish --force @antora/$package
   done

Next, move to the [.path]_test-release-to_ repository and clean stuff up:

 $ git tag -d `git tag`
   git checkout master
   git reset --hard `git rev-parse current`
   git checkout current

Now, go back to the [.path]_test-release-from_ repository and sync with the local origin:

 $ git tag -d `git tag`
   git fetch origin
   git reset --hard origin/master

Now you should be all set to try the release again!

== Future Ideas

In the future, we may consider other ways to trigger a release aside from using a dedicated branch.

=== Pipeline Triggers

One possible approach is to use a https://docs.gitlab.com/ee/ci/triggers/[pipeline trigger] against the master branch.
The reason we decided to defer using this strategy is because there's no clear way to disable a job for a certain trigger or distinguish one trigger from another.
If we want to use pipeline triggers for other purposes, there's a risk we could inadvertently trigger a release.
Even with protections in place, such as checking for a special environment variable, the release job would still run on any trigger.

=== Commit Tags

Another way to trigger a release is to use a commit tag.
When pushing a commit to master, either directly or by merging an MR, we could use a special tag in the commit message to indicate that a release could follow.
For example, the commit message might look like:

 add a cool new feature [ci release]

The increment keyword could be specified as an optional qualifier:

 totally change the API [ci release major]

The upside to this approach is that it's very easy to control when a release is performed and to track what triggered it.
The downside is that it adds noise to commit messages.
