= Antora Project Roadmap
// Settings:
ifdef::env-browser[]
:toc-title: Contents
:toclevels: 3
:toc:
endif::[]
// Project URIs:
:uri-home: https://antora.org
:uri-org: https://gitlab.com/antora
:uri-repo: {uri-org}/antora
:uri-issues: {uri-repo}/issues
:uri-milestones: {uri-repo}/milestones
:uri-changelog: {uri-repo}/blob/master/CHANGELOG.adoc
:uri-demo-issues: https://gitlab.com/groups/antora/demo/-/issues
:uri-docs-site-issues: {uri-org}/docs.antora.org/issues
:uri-ui-repo: {uri-org}/antora-ui-default
:uri-ui-issues: {uri-ui-repo}/issues

This roadmap provides the current development direction and schedule for {uri-home}[Antora].
It is intended for informational purposes only.
The proposed features, their scope, and the release timeline are not firm commitments.

== Antora Core Components

For a detailed list of current development tasks, refer to the Core components {uri-issues}[issue tracker].

=== v1.1

*Release Timeframe*: 2018 Q2

* [ ] Set up API documentation and automatically publish as CI artifact
* [ ] Mark prereleases with next tag and recommended stable version with latest tag {uri-issues}/170[#170]
//* [ ] Pass algolia key in playbook
// * [ ] Upgrade to Asciidoctor.js 1.5.6 (see https://github.com/asciidoctor/asciidoctor/issues/2455#issuecomment-369465086[asciidoctor#2455])

=== Unscheduled

The capabilities and features in this section have been proposed and tentatively accepted as future work tasks.
They aren't slated for imminent development but are reviewed for possible scheduling after each release.

* [ ] Show the file URI where the site can be previewed offline {uri-issues}/220[#220]

* [ ] Generate a robots.txt file {uri-issues}/219[#219]

* [ ] Add context as second argument to ContentCatalog#addFile {uri-issues}/209[#209]

* [ ] Allow supplemental files to be fetched and added to the content catalog {uri-issues}/195[#195]

* [ ] Add (Apache) httpd redirect facility to redirect producer {uri-issues}/192[#192]

* [ ] Allow static redirect page to be customized using a UI template {uri-issues}/191[#191]

* [ ] Allow page alias to be an explicit URL pathname {uri-issues}/190[#190]

* [ ] Add CLI option to specify the site generator to use {uri-issues}/178[#178]

* [ ] Implement fallback value for component version {uri-issues}/161[#161]

* [ ] Support loading the UI from a directory {uri-issues}/150[#150]

* [ ] Add a merge mode to supplemental UI files {uri-issues}/149[#149]

* [ ] Add a logging infrastructure {uri-issues}/145[#145]

* [ ] Allow a component to be promoted to the site root {uri-issues}/132[#132]

* [ ] Decide whether content aggregate should be sorted {uri-issues}/121[#121]

* [ ] Ignore duplicate component in same repository if it matches component in HEAD {uri-issues}/120[#120]

* [ ] Set up UI acceptance test suite {uri-issues}/95[#95]

* [ ] Separate content aggregator from git provider {uri-issues}/93[#93]

* [ ] Add option to playbook to skip/bypass worktree(s) in local repositories {uri-issues}/82[#82]

* [ ] Allow module paths to be configurable {uri-issues}/28[#28]

* [ ] Add support for a moduleless docs component {uri-issues}/27[#27]

* Add Node 9 to CI matrix

* Upgrade build to Gulp 4

* Webhooks between repositories (e.g., docs.antora.org, docker-antora)

* Component to host mapping, not just one site URL

* Custom UI output dir missing test in generator

* Decide whether to isolate id (or ctx) from src property on content file

* Be able to make references to page aliases; would require parsing all document headers in a separate step/phase
//whiteboard
* contentCatalog.resolvePage()
//whiteboard
* antora-version

* Separate site publisher from providers

* Evaluate new strategies for interpreting equations (e.g., build-time conversion to SVG)

*  Watch mode for files in worktree

.Accepted Ideas
* Add support for git-lfs for assets storage such as images (Requirements: {uri-issues}/185[#185])

.Discussions
* Properly store generated PlantUML images directly in Antora content folder instead of output directory (Requirements: {uri-issues}/189[#189])

== Antora Documentation, Demo, & Docs Site

For current Antora documentation tasks, see the Core components {uri-issues}[issue tracker].

For current demo tasks, see the Demo materials {uri-demo-issues}[issue tracker].

For current docs.antora.org tasks, see the site {uri-docs-site-issues}[issue tracker].

=== v1.0.0

* [ ] Document how to run and extend the Docker image for Antora {uri-issues}/211[#211]
* [ ] Move CLI documentation to its own module {uri-issues}/206[#206]
* [ ] Move pages files into topic directory in AsciiDoc module and restructure navigation {uri-issues}/222[#222]

=== Unscheduled

* [ ] Switch docs.antora.org publishing to netlify and automate https certificate renewal
* [ ] Switch antora.org publishing to netlify and automate https certificate renewal
* [ ] Set up a roadmap page for Core components in the docs {uri-issues}/223[#223]
* [ ] Document that .nojekyll file is required when publishing to GitHub Pages {uri-issues}/194[#194]
* [ ] Document the `page-` attributes {uri-issues}/177[#177]
* [ ] Add how to create a partial page {uri-issues}/176[#176]
* [ ] Document sitemap features {uri-issues}/168[#168]
* [ ] Improve custom publish provider documentation {uri-issues}/164[#164]
* [ ] Expand private repository section {uri-issues}/139[#139]
* [ ] Document how to create user-defined page attributes
* [ ] Document redirect features
* [ ] Document stem functionality with common UI integration scenarios
* [ ] Document how to add MathJax integration to the UI
* [ ] Document how to integrate external Javascript files with the UI
* [ ] Document maintenance and bug fix priority policies on antora.org
* [ ] Document release schedule on project site
* [ ] Document list of environment variables to usage
* [ ] Make Get Antora a category landing page
* [ ] Set up a What's New? in the Docs
* [ ] Create community participation guidelines
* [ ] Add changelog system to Docs
* [ ] Add contributing guide to Docs
* [ ] Remove most documentation-type content from README and replace with links to the appropriate Docs pages

== Antora Default UI

For a detailed list of current development tasks, refer to the UI {uri-ui-issues}[issue tracker].

=== v1.0.0

*Release Timeframe*: April 2018

* [ ] Add client-side search (algolia docsearch) {uri-ui-issues}/44[#44]
* [ ] IE 11 fixes
* [ ] Cut stable release of default UI

=== Unscheduled

* [ ] Create task list SVGs {uri-ui-issues}/31[#31]
* [ ] Enable unordered list marker styles {uri-ui-issues}/26[#26]
* [ ] Enable start number attribute for ordered lists {uri-ui-issues}/25[#25]
* [ ] Upgrade preview site sample content {uri-ui-issues}/20[#20]
* [ ] Extract all colors into CSS variables {uri-ui-issues}/18[#18]
* [ ] Upgrade build to Gulp 4
* [ ] Improve SVG options stability

== Completed Releases

See the {uri-changelog}[CHANGELOG] for a summary of notable features, functionality, and bug fixes that have already been released.
