= Antora Project Roadmap
// Settings:
ifdef::env-browser[]
:toc-title: Contents
:toclevels: 3
:toc:
endif::[]
// Project URIs:
:uri-home: https://antora.org
:uri-org: https://gitlab.com/antora
:uri-repo: {uri-org}/antora
:uri-issues: {uri-repo}/issues
:uri-milestones: {uri-repo}/milestones
:uri-changelog: {uri-repo}/blob/master/CHANGELOG.adoc
:uri-demo-issues: https://gitlab.com/groups/antora/demo/-/issues
:uri-docs-site-issues: {uri-org}/docs.antora.org/issues
:uri-ui-repo: {uri-org}/antora-ui-default
:uri-ui-issues: {uri-ui-repo}/issues

This roadmap provides the current development direction and schedule for {uri-home}[Antora].
It's intended for informational purposes only.
The proposed features, their scope, and the release timeline are estimates, not firm commitments.

== Antora Core Components

For a detailed list of current development tasks, refer to the Core components {uri-issues}[issue tracker].

=== v2.1.x

*Release Timeframe*: Q1 2019

* [ ] Automatically set up latest version URLs {uri-issues}/314[#314]
* [ ] Contents of xref should use page title if contents is not specified {uri-issues}/310[#310]
* [ ] Resolve symlinks (possibly just file symlinks) in git tree {uri-issues}/188[#188]
* [ ] Add a logging infrastructure; configure Asciidoctor logger to use it {uri-issues}/145[#145]
* [ ] Allow AsciiDoc attributes to be specified per component-version (in antora.yml) {uri-issues}/251[#251]
* [ ] Implement fallback value for component version based on git ref or config {uri-issues}/296[#296]
* [ ] Provide a better way to indicate that a component version is "versionless"
* [ ] Implicitly disable branches pattern if tags pattern is specified in content source {uri-issues}/268[#268]
* [ ] Allow AsciiDoc content to be included from a URL {uri-issues}/246[#246]
* [ ] Add support to include processor for including lines by line number
* [ ] Add initial support for translations by adding language key to virtual file
* [ ] Provide access to cached repositories in Antora context (as src.origin.cacheDir) {uri-issues}/305[#305]
* [ ] Use worktree of local git repository even when repository has no commits {uri-issues}/298[#298]
* [ ] Don't set canonical URL if page doesn't exist in latest version of component (otherwise, this confuses crawlers)
* [ ] Publish metapackage @antora/antora to simplify installation

=== v2.2.x

*Release Timeframe*: Q2 2019

* [ ] Make module path configurable (using antora.yml) {uri-issues}/28[#28]
* [ ] Add support for a moduleless docs component {uri-issues}/27[#27]
* [ ] Add watch mode for files in worktree {uri-issues}/329[#329]
* [ ] Allow pattern for edit URL to be configurable {uri-issues}/292[#292]
* [ ] Add PDF output option for pages and/or components {uri-issues}/349[#349]
* [ ] Show the file URI where the site can be previewed offline {uri-issues}/220[#220]
* [ ] Add authentication for remote UI bundles {uri-issues}/280[#280]
* [ ] Support loading the UI from a directory {uri-issues}/150[#150]
* [ ] Add support for referencing images across modules
* [ ] Add xref support to image link {uri-issues}/330[#330]
* [ ] Add support for referencing attachments using xref macro {uri-issues}/227[#227]
* [ ] Add priority boosts in sitemap based on component version {uri-issues}/317[#317]
* [ ] Compose playbook files (include one into another)
* [ ] Integrate lunr search into default site generator (or promote the extension and make it easier to enable)
* [ ] Automatically substitute environment variables in playbook file
//* allow a group to be defined in antora.yml
//* make all metadata from antora.yml available to model
//* allow static files in UI to be decorated with page template / access UI model

=== v3.0.x

*Release Timeframe*: Q3 2019

* [ ] Add lifecycle hooks to default site generator
* [ ] Add support for git-lfs for assets storage such as images {uri-issues}/185[#185]

=== Unscheduled

The capabilities and features in this section have been proposed and tentatively accepted as future work tasks.
They aren't slated for imminent development but are reviewed for possible scheduling after each release.

* [ ] Add algolia keys (app ID, API key, and index name) to playbook schema
* [ ] Add support for using template languages other than Handlebars in the UI (e.g., pugjs)
* [ ] Set up repositories for site-publisher-s3 and site-publisher-sftp
* [ ] Add scaffolding commands to CLI to create a new component, module, or page
* [ ] Set up API documentation and automatically publish as CI artifact
* [ ] Generate a robots.txt file (perhaps configured in site.yml) {uri-issues}/219[#219]
* [ ] Add context as second argument to ContentCatalog#addFile {uri-issues}/209[#209]
* [ ] Allow supplemental files to be fetched and added to the content catalog {uri-issues}/195[#195]
* [ ] Add (Apache) httpd redirect facility to redirect producer {uri-issues}/192[#192]
* [ ] Allow static redirect page to be customized using a UI template {uri-issues}/191[#191]
* [ ] Allow page alias to be an explicit URL pathname {uri-issues}/190[#190]
* [ ] Add a merge mode to supplemental UI files {uri-issues}/149[#149]
* [ ] Allow a component to be promoted to the site root {uri-issues}/132[#132]
* [ ] Decide whether content aggregate should be sorted {uri-issues}/121[#121]
* [ ] Ignore duplicate component in same repository if it matches component in HEAD {uri-issues}/120[#120]
* [ ] Set up UI acceptance test suite {uri-issues}/95[#95]
* [ ] Add option to playbook to skip/bypass worktree(s) in local repositories {uri-issues}/82[#82]
* Set up webhooks between repositories (e.g., docs.antora.org, docker-antora)
* Component to host mapping, not just one site URL
* Decide whether to isolate id (or ctx) from src property on content file
* Be able to make references to page aliases; would require parsing all document headers in a separate step/phase
//whiteboard
* contentCatalog.resolvePage()
//whiteboard
* set antora-version AsciiDoc attribute
* Separate site publisher from providers
* Evaluate new strategies for interpreting equations (e.g., build-time conversion to SVG)

.Discussions
* Properly store generated PlantUML images directly in Antora content folder instead of output directory (Requirements: {uri-issues}/189[#189])

== Antora Documentation, Demo, & Docs Site

For current Antora documentation tasks, see the Core components {uri-issues}[issue tracker].

For current demo tasks, see the Demo materials {uri-demo-issues}[issue tracker].

For current docs.antora.org tasks, see the site {uri-docs-site-issues}[issue tracker].

=== Unscheduled

* [ ] Set up a What's New? in the Docs {uri-issues}/366[#366]
* [ ] Create dedicated UI project and bundle for docs.antora.org instead of using supplemental UI
* [ ] Set up a roadmap page for Core components in the docs {uri-issues}/223[#223]
* [ ] Document the `page-` attributes {uri-issues}/177[#177]
* [ ] Explain how to create a partial page {uri-issues}/176[#176]
* [ ] Document sitemap features {uri-issues}/168[#168]
* [ ] Improve custom publish provider documentation {uri-issues}/164[#164]
* [ ] Document how to create user-defined page attributes
* [ ] Document redirect features
* [ ] Document stem functionality with common UI integration scenarios
* [ ] Document how to add MathJax integration to the UI
* [ ] Document how to integrate external Javascript files with the UI
* [ ] Document maintenance and bug fix priority policies on antora.org
* [ ] Document release schedule on project site
* [ ] Document list of environment variables as page (or as appropriate) in CLI module
* [ ] Make Get Antora a category landing page
* [ ] Create community participation guidelines
* [ ] Add changelog system to Docs
* [ ] Add contributing guide to Docs
* [ ] Remove most documentation-type content from README and replace with links to the appropriate Docs pages
// https://gitlab.com/antora/antora/issues/206#note_63768866
* [ ] Partition the CLI options into two tables, general options and generate options

== Antora Default UI

For a detailed list of current development tasks, refer to the UI {uri-ui-issues}[issue tracker].

=== v1.0.0

*Release Timeframe*: Q1 2019

* [ ] Split off base UI from default UI; make default UI configurable from playbook
* [ ] Add client-side search (algolia docsearch) {uri-ui-issues}/44[#44]
* [ ] Cut stable release of default UI
* [ ] Support sample content for preview pages written in AsciiDoc
* [ ] Upgrade preview site sample content {uri-ui-issues}/20[#20]
//* [ ] IE 11 fixes

=== Unscheduled

* [ ] Create task list SVGs {uri-ui-issues}/31[#31]
* [ ] Enable unordered list marker styles {uri-ui-issues}/26[#26]
* [ ] Extract all colors into CSS variables {uri-ui-issues}/18[#18]
* [ ] Upgrade build to Gulp 4
* [ ] Allow SVGs to be embedded directly into Handlebars template
//* [ ] Improve SVG options stability

== Completed Releases

See the {uri-changelog}[CHANGELOG] for a summary of notable features, functionality, and bug fixes that have already been released.
