= AsciiDoc Loader Guidebook
:uri-adoc-js-docs: https://asciidoctor.org/docs/asciidoctor.js/
:uri-adoc-js-api: http://asciidoctor.github.io/asciidoctor.js/master

== Context

Various components in Antora need to parse the AsciiDoc into an abstract syntax tree (AST), either for accessing the document structure or converting it to HTML.
The code responsible for loading AsciiDoc should be centralized in a dedicated component to ensure that AsciiDoc is loaded consistently throughout the pipeline and to avoid code duplication.
This component should integrate the AsciiDoc processor ({uri-adoc-js-docs}[Asciidoctor.js]) into the Antora pipeline and bundle Antora-specific enhancements without exposing any low-level details about how that integration is performed.

== Functional Overview

The AsciiDoc loader component should entirely handle loading the AsciiDoc source stored in a virtual content file into a parsed AsciiDoc document object (i.e., AST).

At a low-level, the AsciiDoc loader should use the load API of the AsciiDoc processor to load the contents of the specified file to produce an AsciiDoc document object.
However, to load the AsciiDoc properly, there's more to it.

The loader should do the following when loading the AsciiDoc:

* set attributes that pertain to the integration
 ** environment attributes (e.g., env=site, site-gen=antora, etc.)
 ** default attributes (e.g., attribute-missing=warn, icons=font, etc.)
 ** custom attributes specified in the playbook
 ** built-in attributes (e.g., docname, docfile, imagesdir, etc.)
* resolve the target of include directives from the content catalog
* resolve xref macros that specify page references, verifying a match can be found in the content catalog
* set other processor options (e.g., safe=safe)

When loading is complete, the method should return the document object.
This document object can then be used by other components to examine the structure of the document, convert the document to HTML, or perform other processing.

== Software Architecture

The AsciiDoc loader component functionality is provided by the asciidoc-loader module.
All the details of loading AsciiDoc documents into a document object, such as resolving include directives and xref macros, should be encapsulated in this component.

The AsciiDoc source string should be retrieved from the `contents.toString()` property of the specified file.
Asciidoctor.js should be used to load the AsciiDoc.
The source string should be passed along with options to the {uri-adoc-js-api}/#Asciidoctorload[`Asciidoctor.load`] API of Asciidoctor.js.
That function should parse the AsciiDoc source into an abstract syntax tree.

=== AsciiDoc processor options

Here's a list of options that should be set when calling `Asciidoctor.load`:

* safe - set to 'safe'
* attributes - environment, default, custom, and built-in
* extension_registry - contains an include processor extension that resolves includes from the content catalog
 ** if the target begins with a family symbol, the target should be looked up by page ID
 ** if the target does not begin with a family symbol, it should be looked up by path relative to the current file
 ** if an include cannot be resolved, the loader should log a warning (meaning, don't be silent)
 ** this extension should be registered per instance, not globally
* converter - an enhanced HTML5 converter
 ** intercepts the conversion of inline_anchor to convert xrefs that are page references (allowing other xrefs through)
 ** this enhancement should be registered on the converter instance, not globally

=== AsciiDoc processor attributes

Here's a list of default attributes that should be passed to `Asciidoctor.load`, which can be overridden in the playbook:

* env = 'site'
* env-site = ''
* site-gen = 'antora'
* site-gen-antora = ''
* attribute-missing = 'warn'
* icons = 'font'
* sectanchors = ''
* source-highlighter = 'highlight.js'

Here's a list of mandatory, built-in attributes that should be set when calling `Asciidoctor.load`, which cannot be overridden:

* docname = file.src.stem
* docfile = file.path
* docdir = file.dirname
* docfilesuffix = file.src.extname
* imagesdir = path.join(file.pub.moduleRootPath, '_images')
* attachmentsdir = path.join(file.pub.moduleRootPath, '_attachments')
* examplesdir = 'example$'
* partialsdir = 'partial$'

=== Page reference converter

The page reference converter should intercept conversion of the inline xref macro and handle any targets that end with `.adoc`.
The target is expected to have the following form:

 <version@><component:><module:><topic/...><page>.adoc<#fragment>[<content>]

All parts except for the file path (i.e., `<topic/...><page>.adoc`) are optional.

If any part is missing, the value from the current context should be consumed.
For example, if the component is not specified, the component of the referring page (the page containing the xref) should be assumed.

The xref macro should be translated into a link to the URL of the target page.
The URL of the target page should be retrieved from the `pub.url` of the target file.
That URL should be made relative to the current page's URL so that the link can be followed even when the site is not served through a web server.

If the target page cannot be resolved, a warning should be emitted and the target should be used as the link's content.

The page reference converter should be registered on the converter instance (per load) and not globally.

=== Include processor

A custom include processor should be registered that resolves the target of all include directives from the content catalog.
The include processor should not be registered globally, but rather once per `loadAsciiDoc` invocation.

The target of an include should either point to a file in the `partial` family or the `example` family of the current module, or to a file relative to the current document.

If the include target begins with a family reference (i.e., `{partialsdir}` or `{examplesdir}`), for example:

 include::{partialsdir}/partial.adoc[]
 include::{examplesdir}/example.json[]

then the included file should be looked up in the content catalog by ID.

Otherwise, if the include target is just a bare path, for example:

 include::sibling.adoc[]

then the target should be resolved relative to the current document and looked up in the content catalog by path.

After successfully looking up the file in the catalog, the following data should be passed to the processor's `push_include` method:

* contents = (file.src.contents || file.contents).toString()
* file = file.src.path
* path = file.src.basename

When retrieving the contents, the `src.contents` should be checked first, then `contents`.
The `src.contents` property is set for any file which is both a page and a partial (as indicated by the `page-partial` attribute on the document).

The include processor should also perform tag filtering on the contents if either the `tag` or `tags` attribute is set on the include directive.

If the include file cannot be resolved, then the include directive should be left unprocessed and a warning should be added to the file (pending architecture).

=== Inputs and outputs

.Inputs
* Virtual AsciiDoc file
* Custom attributes from playbook (`asciidoc.attributes`)
* Content catalog (`ContentCatalog`)

.Output
* AsciiDoc document object (`Document`)

== Code

The AsciiDoc loader is implemented as a dedicated node package (i.e., module).
The AsciiDoc loader API exports the `loadAsciiDoc` function, which accepts:

* a virtual AsciiDoc file
// Q: should we pass the whole playbook, playbook.asciidoc, or playbook.asciidoc.attributes?
* a map of custom AsciiDoc attributes specified in the playbook
* the content catalog

This function returns the parsed AsciiDoc as a document object (`Document`).

The API for the AsciiDoc loader should be used as follows:

[source,js]
----
const loadAsciiDoc = require('@antora/asciidoc-loader')

//...

const doc = loadAsciiDoc(file, {}, contentCatalog)
----

== Data

The `loadAsciiDoc` function should read the AsciiDoc source by calling `contents.toString()` on the specified file.
It should also use properties on that file to set certain attributes, as specified above.

The `loadAsciiDoc` function should return a {uri-adoc-js-api}/#document[Document] object.

// Q: should it also incorporate attributes from antora.yml?
When converting each AsciiDoc document, this component incorporates global AsciiDoc attributes defined in the playbook (at the path `asciidoc.attributes`).

== Consequences

The AsciiDoc loader component ensures AsciiDoc source is loaded consistently throughout the pipeline.
It integrates Asciidoctor.js, configuring it to work properly in the Antora environment, without exposing any low-level details about how that integration is performed.

The main function of this component transforms a virtual AsciiDoc file into a parsed AsciiDoc document, which can then be used by other components to examine the document structure, convert all or parts of the document to HTML, or perform other processing.

This component is used by the document converter component, which converts the contents of the page to HTML, and the navigation builder, which converts navigation files written in AsciiDoc into a navigation model.
