= Linked Navigation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
////
TODO:

Info about where to store a nav file and any alternatives.
Better examples and example output
Align on the names for nav in general and linked vs aspect: linked and aspect domain, linked and aspect navigation, nav tree, linked page, aspect page, etc.
////

Each module contains a navigation file named nav.adoc.
In Antora, this navigation file is called linked navigation.
That's because the nav.adoc file stored in each module doesn't have to be registered in a playbook.
These files are enlisted automatically by Antora.

== nav.adoc file structure

A linked navigation file is an AsciiDoc document that contains a single unordered list.
Each top-level item (`*`) can have up to five levels of nested navigation.
The list can have a block title.

.nav list anatomy
----
.xref:index.adoc[Product Home] <1>
* xref:get-started.adoc[Start here] <2>
** xref:account-setup.adoc[Set up a new account]
*** xref:download-and-install.adoc[Install product]
**** xref:server-install.adoc[Install on a server]
***** xref:install-troubleshoot.adoc[Installation troubleshooting]
* xref:manage.adoc[Manage product]
** xref:console-overview.adoc[Control console tour]
** xref:cloud::manage-deployed-applications.adoc[Managing Deployed Applications] <3>
* More Resources <4>
** xref:console-commands.adoc[Console commands]
** https://support.example.com[Contact support] <5>
----
<1> List title with reference (optional)
<2> List item with reference
<3> List item with reference to another document component
<4> List item without reference
<5> List item with external link

The items in a linked navigation file are usually cross references to pages in the same module.
// relink xref page-references,appropriate inline xref macro patterns
However, using the appropriate inline xref macro patterns, you can include references to any document in the site, whether it's stored in the same module or not.

// relink xref <<ex-links,external links>>
You can also include external links, such as pass:[https://support.example.com], and normal (i.e. unlinked) text.

Unlike xref:aspect.adoc#register[aspect navigation files], the linked navigation file in a module doesn't have to be registered in a playbook.
These files are enlisted automatically by Antora.

////
.Example linked navigation list
----
.xref:index.adoc[Runtime Manager]
* xref:cloudhub::tutorials.adoc[Tutorials]
 ** xref:cloudhub::building-an-https-service.adoc[Building an HTTPS Service]
* xref:deployment-strategies.adoc[Deployment Strategies]
 ** xref:deploying-to-cloudhub.adoc[Deploying to CloudHub]
 ** xref:deploying-to-your-own-servers.adoc[Deploying to Your Own Servers]
* xref:managing-deployed-applications.adoc[Managing Deployed Applications]
 ** xref:cloudhub::managing-applications-on-cloudhub.adoc[Managing Applications on CloudHub]
  *** xref:managing-queues.adoc[Managing Queues]
  *** xref:managing-schedules.adoc[Managing Schedules]
  *** xref:secure-application-properties.adoc[Secure Application Properties]
  *** xref:object-store::managing-application-data-with-object-stores.adoc[Managing App Data using Object Stores]
* More Goodness
 ** https://support.example.com[Contact Support]
----
////
