= Site Navigation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:description: An introduction to how Antora creates site and component navigation menus for multiple documentation products and multiple documentation versions.
:keywords: navigate between documentation versions, navigate between projects, navigate to other versions of a page, add page links to a menu, add page links to a sidebar, add page links to an AsciiDoc list, set up website navigation with Antora, multi-version navigation, create a navigation menu with AsciiDoc
// Settings
:idprefix:
:idseparator: -

With Antora, you can create your site's navigation with AsciiDoc and store it right alongside your documentation files.

== Navigation assembly requirements

The navigation for an Antora documentation site requires:

* at least one navigation source file that contains at least one unordered AsciiDoc list,
* at least one navigation source file registered in the component descriptor file,
* a UI bundle, such as the Antora default UI, that can apply styles and interaction behavior to the menu(s) Antora generates.

// diagram

Let's take a brief look at each of the numbered items in this diagram.

=== 1 Source: Navigation list files

The navigation for a component is described by at least one AsciiDoc file.
However, as seen in the diagram, you can have as many navigation files as you need.
Creating a navigation file per module is a common organizational structure we see.

A navigation file contains one or more AsciiDoc lists.
Each item in a list can be the link to a documentation page, URL to a website that isn't part of the site, or unlinked content such as a category title that groups a nested set of links.
Documentation page links are created using the same cross referencing syntax used in the pages themselves.

When you want the list contents of a navigation file to be published to a component's navigation menu, you need to register the file in the appropriate component descriptor file.

=== 2 Source: Navigation enlistment

Navigation files are registered in a component descriptor file under the nav key (`nav`).
List the navigation files in the order you want them to be displayed in when they're published to the component menu on your site.
When you run Antora, it will only use the registered navigation files to create the component menu.

=== 3 Site: Component navigation menu

Antora collects the contents of each registered navigation file, puts the contents in the order the files are listed under the `nav` key, and publishes a fully assembled navigation menu for the component to the site.
The behavior and style of the menu is dictated by the UI bundle specified in your playbook.

// screenshot of component menu

Antora carries out this assembly process for each version of each component that it locates in the repositories, branches, and tags listed under `sources` in the site's playbook.

=== 4 Site: Component version selector

When your site has several components and/or several versions of one or more components, Antora assembles an aggregated list of the components and their versions.
We refer to this master menu of components and versions as the component version selector.
Antora automatically lists the components in alphabetical order and the versions in order from the greatest or latest.

// screenshot of drawer

In the default UI, this list is displayed in the "`drawer`" located at the bottom of any component menu.
When a visitor clicks on the drawer, it expands upwards and the reader can then select the component and version they want to see.

=== 5 Site: Page version selector

If a page is available in more than one version of a component, a dropdown selector is visible on that page.
From this selector, a visitor can navigate between other versions of that page.
Antora automatically populates this selector menu when multiple versions of a page are available.

// screenshot of page selector

== What's next?

*Deep Dives*: All the details about each concept.

* xref:source-files.adoc[Navigation file overview: purpose, file name, file format]
//other ways to navigate to a page
//Pages: to add or not to add them to a navigation file?
* xref:list-structure.adoc[Navigation list structures: list item and title nesting depth, single list file, multi-list file]
// source nesting depth versus published nesting depth, titled versus non-titled lists
* xref:content-syntax.adoc[Navigation list item syntax: xrefs, URLs, text styles, images, icons, and more]
* Valid navigation file locations
//* Navigation files and the AsciiDoc include directive
* The nav key and registering navigation files
//* Component navigation menu, home icon, and the index / start page
* Breadcrumbs
* Component version selector menu
* Page version selector menu

*Use Cases*: Workflows and tutorials.

* xref:create-a-navigation-file.adoc[Create and register a basic navigation file]
* Create a navigation file that contains multiple AsciiDoc lists
//* Add xrefs to pages in topic folders and other modules
//* Insert one module's navigation between the lists or list items of another module's navigation

//* Set up a new navigation file and add different types of content to it.
//* Organize navigation files in a component.
//* Select the order the navigation lists should be displayed in a published site.

// In addition to xrefs, the lists can contain normal text, images, icons, and URLs to other sites.
// You don't need to know any special syntax just for creating navigation menus, it's just regular AsciiDoc.
// There's no special syntax or file structure for creating navigation menus or UI template logic to learn.
// It then publishes the output to a navigation menu for each component version.
// describe and control the navigation structure as a content concern; navigation stored with the content; author-controlled, yet can still be manipulated by the UI / designer
