= Navigation Source Files
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:description: An overview of the purpose of an Antora navigation source file, its file format, and its naming parameters.
:keywords: AsciiDoc navigation file, nav.adoc
// Settings
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] The ways visitors can navigation to site pages.
* [x] The purpose of a navigation file.
* [x] The navigation file's extension and naming rules.

== Navigation methods

All of the AsciiDoc files (`.adoc`) in a [.path]_pages_ directory are automatically published to your site by Antora.
That means visitors can find a page using search tools, through links on other site pages, and in some scenarios, through dropdown menus such as the page version selector.
If you want visitors to be able to go to a page using a component navigation menu, then you must add a cross reference (`xref`) to that page in the appropriate navigation source file.

== What is a navigation source file?

A navigation source file is a marked up list of page links, website URLs, and other content that is stored in a documentation component as an AsciiDoc file.
Antora combines one or more navigation files as instructed by a component descriptor file, converts the assembled navigation file lists into HTML, wraps the HTML with a UI template, and publishes the results as component navigation menus on your site.
These component navigation menus allow your users to discover and navigate between the pages in your published site.
Antora allows for a variety of use cases so that you can create, store, and assemble the navigation source files to suit your documentation requirements.

== File format and name

Navigation files should end with the AsciiDoc file extension (`.adoc`).
Navigation files are commonly named [.path]_nav.adoc_; however, you can use any name that is meaningful to you.

== What's next?

The pages in the Site Navigation category describe the fundamentals of creating and storing navigation files in a documentation component.

* xref:list-structure.adoc[Navigation list structures: list item and title nesting depth, single list file, multi-list file]
// source nesting depth versus published nesting depth, titled versus non-titled lists
* xref:content-syntax.adoc[Navigation list item syntax: xrefs, URLs, text styles, images, icons, and more]
* xref:register-navigation-files.adoc[Register a navigation file for display in a component menu]

// and then describe some alternative scenarios.
