= Navigation File Syntax and Structure
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

== List structure

A navigation source file contains one or more xref:asciidoc:ordered-and-unordered-lists.adoc#unordered[unordered AsciiDoc lists].
The top-level navigation item in an unordered list is marked by a single (`{asterisk}`).
Each top-level item can have as many nested items as you need.
The greatest nesting depth allowed is level five (`+*****+`).
Also, a list can have a title, denoted by a period (`.`).

.List depth levels
[source,asciidoc]
----
.List title (optional for single list files)
* Level 1 (top)
** Level 2
*** Level 3
**** Level 4
***** Level 5
----

=== Single list file

A navigation source file can contain a single list.
When the file only has one list, the list title is optional.

.Single list structure
[source,asciidoc]
----
* List item
** Nested item
* List item
* List item
** Nested item
*** Nested item
----

=== Multiple lists file

When a navigation source file contains multiple lists, each list must have a title be separated by at least one blank line.

.Multi-list structure
[source,asciidoc]
----
.List title        // <1>
* List item
                   // <2>
.Second list title // <3>
* List item
** Nested item
*** Nested item
----
<1> Required list title
<2> Require blank line between lists
<3> Required list title

== List titles and items

A list title is denoted by a period (`.`) and directly followed by the content of the title.
If the navigation file only contains one list, a list title is optional and you can start the list with a top level item.
List titles are required when a navigation source file contains multiple lists.

A list item is denoted by one to five asterisks, depending on desired nesting level, directly followed by a single space, and then the content of the item.

The content of a title and each item can be a page cross reference, URL, normal text, or an image.

.List title and item content
[source,asciidoc]
----
.xref:overview.adoc[The Special Project] // <1>
* xref:install.adoc[Install the App] // <2>
* More Resources // <3>
** https://special-project.com/support[Get Help] // <4>
----
<1> Xref list title
<2> Xref list item
<3> Normal text list item
<4> URL list item
