= Command-line Interface
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

Antora provides a command-line interface (CLI) so you can interact with it through your terminal.
When installed, the CLI adds the `antora` command to your PATH.

== Terminal conventions

We use some typical conventions when showing terminal examples.

Prompt (`$`)::
The terminal's command prompt is indicated by a dollar sign ('$').
Don't include the prompt when you type commands.

Directory::
A directory name may be shown before the command prompt in some examples.
If displayed, the following command should be executed from that directory.

Command Output::
If Antora returns information after a command is executed, that output is displayed in the terminal underneath the command.
The command prompt (`$`) will not be displayed on output lines.

== Command Structure

The `antora` command accepts user inputs in the form of command-line arguments and environment variables.

 $ antora <command> <options>

All functions start with a call to Antora (`antora`).
After the base call is the command that tells Antora what operation to perform.
Additional options, such as environment variables, can be specified after a command.

// Shows usage documentation, which should list the options (flags and switches), (sub)commands, arguments, and environment variables that it accepts as input.
