= Command-line Interface
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
:table-caption!:

Antora provides a command-line interface (CLI) so you can interact with it through your terminal.
When installed, the CLI adds the `antora` command to your PATH.

== Terminal conventions

We use some typical conventions when showing terminal examples.

Prompt (`$`)::
The terminal's command prompt is indicated by a dollar sign ('$').
Don't include the prompt when you type commands.

Directory::
A directory name may be shown before the command prompt in some examples.
If displayed, the following command should be executed from that directory.

Command Output::
If Antora returns information after a command is executed, that output is displayed in the terminal underneath the command.
The command prompt (`$`) will not be displayed on output lines.

== Command Structure

The `antora` command accepts user inputs in the form of command-line arguments and environment variables.

 $ antora <command> [options] <arguments>

. All functions start with a call to Antora (`antora`).
. The command tells Antora what operation to perform.
. Additional options, also called flags or switches, can be specified after a command.
. Arguments, such as the name of the playbook filename and environment variables, are specified last.

// Shows usage documentation, which should list the options (flags and switches), (sub)commands, arguments, and environment variables that it accepts as input.

== Commands and Options

.CLI Commands
|===
|Command |Purpose

|antora
|The base command.

|generate [options] <playbook>
|Generate the documentation site specified by the <playbook>.
This command is implicitly executed if no command is specified.
|===

.CLI Options
|===
|Option |Purpose

|--clean
|Remove the previous output directory before generating the site.

|-h, --help, help
|Output the command usage information.

|--quiet
|Do not write any messages to stdout.

|--silent
|Supress all messages.

|--stacktrace
|Print the stacktrace to the console if the application fails.

|--title <title>
|Specify the title of the site.
This option overrides the xref:playbook:configure-playbook.adoc#site-title-key[site title value] specified in the playbook.

|--to-dir <dir>
|The directory where the site should be generated.
The default output directory is [.path]_build/site_.

|--ui-bundle <bundle>
|The UI bundle URL.
The URL can be a path on the local filesystem.
This option overrides the xref:playbook:configure-playbook.adoc#ui-bundle-key[ui bundle value] specified in the playbook.

|--url <url>
|The base URL of the published site.
The URL should not include a trailing slash.
This option overrides the site url value specified in the playbook.

|-v, --version
|Output the Antora version information.
|===
