////
TODO: explain how this relates to page versions
////
= Component Versions and Branches

Versions of a xref:component-structure.adoc[documentation component] are stored in branches in a version control repository such as git.
The name of the branch itself doesn't matter.
It's the version property in the component descriptor that determines the name of the version for the component.

== Branches as versions

Like with software, we use branches to store different versions of the documentation.
Branches are ideally suited for managing multiple versions of the same content.

If we didn't use branches to specify versions, but instead used folders with trailing version numbers, all stuffed in a single branch, then we'd have to explicitly duplicate all the files in a documentation component for each version.
And we'd have no easy way to compare, manage, and merge different instances of a document.

Branches handle all this for us.
Creating a new branch is extremely cheap.
You simply create a new branch from an existing reference in the repository, and the repository only stores what's changed since that branch point.

== Setting the version for a branch

To set the version of documentation stored in a particular branch, you specify the xref:component-descriptor.adoc#version-key[version in the component descriptor]:

[source,yaml]
----
name: versioned-component
version: '2.1'
title: Versioned Component
----

This component descriptor communicates that the files taken from this branch contribute to version 2.1 of the versioned-component component.
The name of the branch could be v2.1 or v2.1-beta.
It doesn't matter.

This is the only file you have to update when creating a new branch.
All the page references for that component should be relative to the version, so you shouldn't need to update any links.
The next time you run Antora on the repository, you'll see a new version in the component explorer drawer.

You may need to add the xref:playbook:configure-content-sources.adoc#branches[branch to your playbook file].
Keep in mind that content sources are filtered by branch name, not by the version they contain.
That's because a single version can be spread out across multiple branches, or even multiple repositories.

== How Antora sorts versions

Antora sorts the versions of a component.
To attain the order you want, you need to understand Antora's sorting rules.
Antora uses these rules:

* Consider separately versions that look like sematic versions with an optional leading "'v'" (e.g. 3.4.9-beta or v10.2) and those that do not.
* Add the versions that are not semantic to the list in reverse-alphabetical (descending) order.
* Add the remaing versions, those that do start with an optional leading "`v`" followed by a digit, to the list in descending semantic versioning order as defined on https://semver.org.

Whenever Antora displays versions, it presents them in this order.
Bear in mind that if a display version is specified, the display version is shown instead (other than in URLs).
Thus, to the reader's eyes, the versions may not appear to be sorted this way.
The display version allows the sortable version and the version displayed to be independent of each other.

Example (with no display versions):

----
witt
venn
ulam
master
v3.10
v3.9
v2.0
----

Although `master` is a reserved word and <<#versionlessComponents,affects the URLs for pages in that component-version>>, it is sorted normally.

== Subtle considerations with versions

=== Prerelease versions and latest version

A version may be designated [.term]*prerelease* by including a `prerelease` attribute with a value in [.path]_antora.yml_.
This has two effects:

* If a `display_version` is not explicitly specified, the value of the `prerelease` is combined with the version to generate a `display_version`
* A prerelease version is normally skipped when determining the [.term]*latest version*:

The [.term]*latest version* is the first version (in sorted order) that is not prerelease, unless all versions are prerelease, in which case it is the first.
This is used as the version for the overall site start page and in resource ids that otherwise cannot determine version, and is exposed in the content model.


[#versionlessComponents]
=== Versionless URLs and components

Normally the version is a segment in the URL of every page of the component.
One version of a component may omit the version in the URLs for that version by using the reserved word 'master' as the version.
If this is the only version of the component, the component is termed a [.term]*versionless component*.

.antora.yml for a versionless component
[source,yaml]
----
name: tutorials
version: master
title: Tutorials
----

When the name of a component version is `master`, Antora removes the version segment from the URL (and output path) of all publishable files in that component version.
For example, a page in the versionless component shown above might have a URL like `/tutorials/build-a-restful-web-service.html`.
However, the version name can still be referenced in resource IDs for the purpose of making references (e.g., `master@tutorials::build-a-restful-web-service.adoc`).

If the version property has any value other than `master` (e.g., latest), that value will appear in the URL (and output path) of the files.
