= Organizing Your Documentation for Antora
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Antora works with collections of documentation that follow a standard, well-defined project structure.
The benefits of a standard project structure for documentation are as follows:

* faster onboarding of contributors
* interoperability with authoring, validation, migration, and bootstrap tools
* the ability to define page references that span component versions (and thus repositories), are not coupled to output URLs (source-to-source), and can be automatically updated by a tool when source files are moved and renamed
* better organization system to manage files as the documentation grows

We call a collection of documentation files organized under Antora's standard project structure a [.term]_documentation component_.

When you use documentation components, you can take advantage of the open source tools, plugins, and automated processes built to integrate with the Antora pipeline.

== Documentation component overview

A documentation component is content that adheres to a standard, well-defined organization structure.
This type of component contains of a collection of AsciiDoc text files and their assets, such as images, as well as a component descriptor file.
All the documentation in a component should follow the same versioning scheme and be versioned together.
Your site can be generated using just one documentation component, or as many as you want.

When Antora receives instructions from your playbook to scan a specific repository, its first objective is to find a component descriptor file in that repository.
The xref:component-descriptor.adoc[component descriptor file] is named [.path]_antora.yml_.

Once Antora finds this file, it assumes that that directory and all its files and subdirectories are a documentation component.
The structure of a documentation component is laid out below.

//.Component directory hierarchy
image::component-dir-structure.svg[,240]

The component illustrated in the above figure contains required and reserved directories and files as well as an example of an optional, user created module ([.path]_user-named-module_).
When Antora encounters these folders and files in a properly structured component, it automatically assigns preset behavior and metadata to them.

.Component preset legend
****
*Required* - Must be present in the documentation component.

*Recommended* - Should be present in the documentation component, but not required.

*Optional* - Doesn't need to be created if the directory, file, or content type isn't applicable to the component or module.

*Reserved* - Directory or file is associated with specific pipeline operations.
The contents of a directory or file using a reserved name must adhere to certain requirements.
****

xref:component-descriptor.adoc[antora.yml] ::
_Required_; _Reserved_
+
The component descriptor file tells Antora that the contents of the directory are a documentation component.
This file contains crucial xref:component-descriptor.adoc[metadata about the documentation component].

xref:modules.adoc[modules] ::
_Required_; _Reserved_
+
Except for [.path]_antora.yml_, all of the files in a component reside in this directory.

xref:modules.adoc#root[modules/ROOT] ::
_Recommended_; _Reserved_
+
Directory that contains the xref:modules.adoc#root[ROOT (aka top-level) module].
This special directory does not appear in the output path.
Instead, it becomes the parent folder of any user-defined modules.
The directory name must be written in all uppercase letters.

modules/<user-defined-module> ::
_Optional_
+
In addition to the ROOT module, you can create as many additional modules as your documentation component requires.

Each module, whether the ROOT module or an additional module, is structured as follows:

xref:modules.adoc#assets-dir[<module>/assets] ::
_Optional_; _Reserved_
+
Directory where multimedia and supplemental files are organized by content type.

xref:modules.adoc#attachments-dir[<module>/assets/attachments] ::
_Optional_; _Reserved_
+
Directory that contains supplemental materials, such as PDFs or ZIP files, that readers can download via a link created in a page using the xref:asciidoc:link-attachment.adoc[AsciiDoc link macro].

xref:modules.adoc#images-dir[<module>/assets/images] ::
_Optional_; _Reserved_
+
Directory that contains pictures, screenshots, diagrams, and other graphics files that are displayed in a page using the xref:asciidoc:insert-image.adoc[AsciiDoc image macro].

xref:modules.adoc#examples-dir[<module>/examples] ::
_Optional_; _Reserved_
+
Directory that contains non-AsciiDoc file types, such as source code or data values.
These files are often inserted into listing blocks using the xref:asciidoc:include-content.adoc#include-example[AsciiDoc include directive].

xref:modules.adoc#pages-dir[<module>/pages] ::
_Required_; _Reserved_
+
Directory that contains all of a module's AsciiDoc files.
These files are automatically enlisted by Antora and converted to standalone HTML pages.

xref:modules.adoc#partials-dir[<module>/partials (or <module>/pages/_partials)] ::
_Optional_; _Reserved_
+
Directory that contains AsciiDoc files that can be inserted into the files stored directly under [.path]_pages_.
These files are *not* converted to HTML by Antora directly.
Instead, they must be referenced by an xref:asciidoc:include-content.adoc#include-partial[include directive] in a page in the [.path]_pages_ directory.

<module>/_attributes.adoc ::
_Required_; _Reserved_
+
Helper file that enables assets, partials, and examples to be rendered in preview tools such as Atom and the Asciidoctor Chrome extension.

xref:navigation:index.adoc[<module>/nav.adoc] ::
_Optional_; _Reserved_
+
A xref:navigation:filenames-and-locations.adoc[navigation file] contains one or more AsciiDoc lists.
Each navigation file must be xref:navigation:register-navigation-files.adoc[declared in the component descriptor] if you want it to be displayed in the component's navigation menu.

//We know the structure in the example above represents a documentation component because of the presence of an [.path]_antora.yml_ file.
