= Component Descriptor: antora.yml
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

A documentation component must contain a component descriptor file named [.path]_antora.yml_.

This file serves two purposes:

. *Component marker*: When Antora finds [.path]_antora.yml_ in a repository, it knows that it has located a documentation component.
This ability to "`start`" a documentation component anywhere in a directory hierarchy allows you to store a component in a repository with the software it documents, with a demo project, by itself, etc.

. *Component information*: [.path]_antora.yml_ is a component descriptor file.
It associates the files under this hierarchy with the specified component name and version (aka component-version), decoupling the files from the repository and branch in which they live.
This information is used for creating links to pages in this component.
The file also identifies files to use for site navigation.

//When we find a component descriptor file, specifically , in a repository, we expect to find the standard structure of a documentation component below it.
//Thus, the documentation can live anywhere in the repository.
//The component can even share the same repository as the software it documents.
//The documentation component is then repeated in each branch of each repository that hosts a documentation component.

== Component descriptor requirements

A documentation component must have a [.term]_component descriptor_ file.
This file provides stable metadata that Antora and other tools can use when they need to retrieve information about the component and version.

The component descriptor must:

* be located at the root of the documentation component (adjacent to the [.path]_modules_ directory for that component)
* be named [.path]_antora.yml_
* be written in YAML
* contain the required keys and values

.Component descriptor structure
[source,yaml]
----
name: component-a # <1>
title: Component A # <2>
version: '1.0' # <3>
start_page: module:filename.adoc # <4>
nav: # <5>
- modules/ROOT/nav.adoc
- modules/module-three/nav.adoc
- ...
----
<1> Name key
<2> Title key
<3> Version key
<4> Start page key
<5> Nav key

[#name-key]
=== name

The value of the `name` key is the component name that is used when the component is referenced in a xref:asciidoc:page-to-page-xref.adoc#page-id-cname-def[cross reference].
The value can contain letter, number, underscore (`+_+`), hyphen (`-`), and period (`.`) characters.
The component name *does not* have to be the same as the name of the repository it lives in.

=== title

The value of the `title` key is the display name for the component.
It's used anywhere in the UI that the component is identified.
//(or its super type, domain)
This includes:

* xref:navigation:index.adoc#component-menu[component navigation menu]
* xref:navigation:index.adoc#component-dropdown[component version selector]
* first breadcrumb position

The component title *does not* have to be the same as the component name.

[#version-key]
=== version

The value of the `version` key is both the display name and version coordinate.
This includes:

* page ID and cross references (xref:asciidoc:page-to-page-xref.adoc#page-id-vname-def[version@])
* xref:navigation:index.adoc#component-menu[component navigation menu]
* xref:navigation:index.adoc#component-dropdown[component version selector]
* xref:navigation:index.adoc#page-dropdown[page version selector]
* edit page URI (not visible)

The value can contain letter, number, period (`.`), underscore (`+_+`), and hyphen (`-`) characters.
If the value starts with a number, it must be contained within a set of single quote marks (`'`).

.Example version key values
* '1.0'
* v2.0-beta
* latest

The version key value isn't related to a xref:component-versions.adoc[repository branch name or tag] in any way.
Instead, the value should be useable by the documentation writers and useful to the readers.

[#start-page-key]
=== start_page

By default, Antora looks for a file named [.path]_index.adoc_ in the ROOT module of each component to use as the start page for that component and version (e.g., _\https://example.org/component-name/index.html_).

If the ROOT module doesn't have an [.path]_index.adoc_ page, you must specify a start page explicitly in the component descriptor.
The `start_page` key accepts the xref:page:page-id.adoc[page ID structure] and must point to an existing page in the same component (e.g., `ROOT:home.adoc`, `module-one:overview.adoc`).

If a start page isn't specified, and the component does not have a ROOT module with an [.path]_index.adoc_ page, the reader will be directed to a 404 page when navigating to that component from the xref:navigation:index.adoc#component-dropdown[component version selector] on any page.

.Start page value examples
[source,yaml]
----
start_page: ROOT:home.adoc

# or

start_page: security:protocols/ssh.adoc
----

IMPORTANT: A component must have a ROOT module that contains an [.path]_index.adoc_ page.
Otherwise, a start page must be specified using the `start_page` key in the component descriptor.

[#nav-key]
=== nav

The nav key accepts a list of xref:navigation:filenames-and-locations.adoc[navigation files].
Each xref:navigation:register-navigation-files.adoc[value specifies the path to a navigation file] (e.g., [.path]_modules/module-name/nav.adoc_).
The order of the values dictates the order the contents of the navigation files are assembled in the published xref:navigation:index.adoc#component-menu[component menu].
