= Installation Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
// URIs
:uri-node: https://nodejs.org
:uri-git: https://git-scm.com
:uri-git-dl: {uri-git}/downloads
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-yarn: https://yarnpkg.com

You'll learn:

* [x] What tools you need on your computer before you can install Antora.
* [x] How to install these tools on your computer.

If you've never installed Antora before, you'll need to complete the steps on this page before you can generate a documentation site.

To install Antora, you need Node 8 (including npm, which is typically bundled with Node) and the base build tools.
Let's start with the build tools, since you may also need them to manage Node.

== Base Build Tools

The base build tools are required for installing the nodegit package, a dependency of Antora.
This selection of tools provides other useful commands you'll need in your workflow, such as `git`.

Once you have these tools installed, you can expect the remaining installation to go smoothly.

=== Linux

If you're running Linux, select the appropriate base build tools package for your distribution.

* Fedora: `dnf install @development-tools`
* Debian/Ubuntu: `apt-get install build-essential`
* Arch Linux: `pacman -S base-devel`
* Alpine Linux: `apk add build-base`

=== macOS

If you're running macOS, you need the https://railsapps.github.io/xcode-command-line-tools.html[Xcode command line tools].
Even if you've installed these tools in the past, it's good to do it again.

You can trigger installation using the following command:

 xcode-select --install

== Node 8

Antora requires Node 8, the current long-term support (LTS) release of Node.

To check which version of Node you have installed, if any, open a terminal and type:

 $ node --version

*If this command fails with an error*, you don't have Node installed.
The best way to install Node 8 is via the package manager for your operating system.
However, if your package manager doesn't provide Node, skip directly to <<install-nvm,install nvm and Node>> for instructions.

*If the command returns a version less than 8.0.0*, upgrade to the latest Node 8 version using your operating system's package manager.
Or, if your package manager doesn't provide Node and you have nvm installed, go directly to <<upgrade-node,upgrade and alias Node with nvm>> for instructions.

*If the command returns a Node 8 version*, set Node 8 as the default by typing the following command in your terminal.

 $ nvm alias default 8

Now you can proceed with installing Antora.

CAUTION: While you can use Node 9, we don't recommend it because there are no precompiled binaries for Node 9 of nodegit, a dependency of Antora.
If you use Node 9, installation will take considerably longer.

[#install-nvm]
=== Install nvm and Node

If your package manager doesn't provide Node, we recommend using {uri-nvm}[nvm] (Node Version Manager) to manage your Node installations.
Follow the {uri-nvm-install}[nvm installation instructions] to set up nvm on your machine.

TIP: Many CI environments use nvm to install the version of Node used for the build job.
By using nvm, you can closely align your setup with the environment that is used to generate and publish your production site.

Once you've installed nvm, open a new terminal and install Node 8.

 $ nvm install 8

The above command will install the latest version of Node 8 and automatically set it as your default alias.
Now that you have Node installed, you can install Antora.

[#upgrade-node]
=== Upgrade and alias Node with nvm

If you have nvm installed but your Node version is less than 8.0.0, type the following command in your terminal.

 $ nvm install 8

The above command will install the latest version of Node 8.

Next, set Node 8 as the default for any new terminal.

 $ nvm alias default 8

The above command will set the latest version of Node 8 as your default.

Now that you've upgraded your Node version, you're ready to install Antora.

////
== git

You need basic git skills and {uri-git}[git] (command: `git`) installed on your machine in order to pull down project repositories and push updates to them.

Check to see if you have git installed.

 $ git --version

If that command doesn't return any information, {uri-git-dl}[download and install] the git package for your system.

[#yarn]
== Yarn

{uri-yarn}[Yarn] (command: `yarn`) is the preferred package manager and script runner for the Node ecosystem.
You'll need Yarn to download Antora and manage its dependencies as new versions are released.

Install Yarn globally with the following command:

 $ npm install -g yarn

(You got access to the `npm` command when you installed Node.)

Next, verify Yarn is installed by checking the version:

 $ yarn --version

If you see a version, you are all set.
If your Yarn installation failed, see xref:troubleshoot-yarn-nodegit.adoc[Troubleshooting Yarn and NodeGit].

Now that you have Node and Yarn installed, you're ready to xref:playbook:set-up-existing-playbook-project.adoc[clone and initialize an Antora playbook project].
////
