= Page IDs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

Antora's page IDs are one of its foundational elements.

In order to reference a page, that is, create a link to it from another page, that page has a unique and stable identifier.
That identifier doesn't change, even if page gets published to different places.
Like a mobile phone number, when that identifier is "`called`", the page answers, no matter where it's published.

We call a page's "`number`" a page identifier, or page ID for short.
The page ID is constructed from the properties of the source document that make it unique within a documentation site.

A page ID is based on a documentation component's xref:component-structure.adoc[standard project structure].
Documentation components ensure that each page lives in a defined, describable location.
From this structure, each location derives unique, reliable coordinates we can use to refer to it.

These "`coordinates`" that make a source document unique, are described below:

Component::
The documentation component to which the page belongs; often mapped to a repository.

Version::
The version of the component in which this page lives; often mapped to a repository branch.

Module::
The content bundle in which the page is grouped; if empty, defaults to ROOT.

Page::
The path to the page's source file in the module, including any leading topic directories.

Fragment::
The identifier of an element inside a page, i.e., deep link.

Using this information, a fully-qualified page ID can be constructed.

image::page-id-anatomy-diagram.svg[Page ID anatomy,role=grow-x]

Here's an example of a fully-qualified page ID:

----
1.0@antora:playbook:configure.adoc#filter-branches
----

////
We can repurpose the http://asciidoctor.org/docs/user-manual/#inter-document-cross-references[inter-document xref macro^] in AsciiDoc to convert this page ID into a link:

image::xref-macro-anatomy-diagram.svg[Page reference anatomy,role=grow-x]

Here's how that looks in practice:

----
xref:1.0@antora:playbook:configure.adoc#filter-branches[filter branches]
----

*We've avoided coupling to the published URL* by using a source-to-source reference.
(Notice the page coordinate ends with .adoc, the file extension of an AsciiDoc source file).
Regardless of whether you're deploying your site locally, to staging, or to production, or you change URL strategies, the page ID always remains the same.
The reference locks on to the target page and produces a URL that points to it wherever it gets published.

*We've avoided coupling to the filesystem* by using a location based on the documentation component structure.
The page ID describes the source file's project (component / version) and where in that project the source file is located (module / page).

*We've eliminated the relative path (../../) problem* by specifying the page as a module-relative path.
The path always starts from a module's [.path]_pages_ directory, even when the referencing page is located inside a topic folder.
If you move or rename a page within a module, you don't have to change any references to other pages.

Of course, inbound references to the page you move do have to be updated.
To counter this, you could pin the page ID of the page you want to move, thus adding more stability.
That way, references to the page don't have to be updated even when it moves.
Though, a little help from the text editor to "`refactor`" references could make this abstraction unnecessary.

*We've made it possible to validate and update references* by using a well-defined pattern that's easy for a script to locate, parse, and rewrite.

This human-friendly referencing system saves you from having to do computations in your head while writing.
You just specify the coordinates of the page you want to reference.
There's no need to worry about the source file physical location on disk or its published URL.
All you need to know are the names of your components, versions, modules, and pages so you can fill in this information.

Specifying the component and version every time seems like overkill.
Surely there must be some sort of shorthand, right?
////
