= AsciiDoc Page Header
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] How to structure a valid AsciiDoc page header.
* [x] How to set a page title.
* [x] Where the page title is used in the published site.
* [x] How to set and use AsciiDoc's built-in page attributes.
* [x] How to add page metadata.

== Page header anatomy

.Common elements in a page header
[source,asciidoc]
----
= Page Title // <1>
First Middle Last <author@email.com> // <2>
:description: A description of the page stored in an HTML meta tag. // <3>
:keywords: comma-separated values, stored, in an HTML, meta, tag // <4>
:sectanchors: // <5>
:url-repo: https://my-git-repo.com // <6>
----
<1> Title of the page
<2> Author name and email address
<3> Page description that is stored in the HTML `meta` tag `description`
<4> Comma-separated list of values that are stored in the HTML `meta` tag `keywords`
<5> Example of a built-in page attribute
<6> Example of a user created and defined page attribute

== Page title

A page title is specified by one equals sign (`=`), followed by one blank space, and then the text of the title.

[source,asciidoc]
----
= The title of this page
----

The content of a page's title populates the navigation breadcrumb when the site is generated.

== Page metadata

AsciiDoc provides several built-in attributes for defining page metadata.

=== Author

Specifying the author of a page is optional.
The author of a page is listed on the line beneath the page’s title.
An optional email address or URL can follow an author’s name inside a set of angle brackets (`< >`).

.Multiple authors
[source,asciidoc]
----
= Page Title
First Middle Last <author@email.com>; First Middle Last <author-url[@author]>
----

When a page has multiple authors, each author is separated by a semicolon (`;`).
The author's name is stored in the HTML `meta` tag `author`.

.Author HTML meta tag output
[source,xml]
....
<head>
<meta charset="UTF-8">
<meta name="author" content="Firstname Lastname, Firstname Lastname">
....

Whether the page author information is visible on a generated page depends on the site's UI templates.

=== Description

The page attribute `description` is assigned to the HTML `meta` tag with the same name.
If the description is long, you can break value across several lines by ending each line with a backslash `\` that is preceded by a space.

[source,asciidoc]
----
= Page Title
:description: A description of the page stored in an HTML meta tag. This page is \
about all kinds of interesting things.
----

.Description HTML meta tag output
[source,xml]
....
<head>
<meta charset="UTF-8">
<meta name="description" content="A description of the page stored in an HTML meta tag. This page is about all kinds of interesting things.">
....

=== Keywords

The `keywords` attribute contains a list of comma-separated values that are assigned to the HTML `meta` tag with the same name.

[source,asciidoc]
----
= Page Title
:keywords: comma-separated values, stored, in an HTML, meta, tag
----

.Keywords HTML meta tag output
[source,xml]
....
<head>
<meta charset="UTF-8">
<meta name="keywords" content="comma-separated values, stored, in an HTML, meta, tag">
....

== Built-in page attributes

////
author::
The author’s full name, which includes all of the characters or words prior to a semicolon (`;`), angle bracket (`<`) or the end of the line.

firstname::
The first word in the author attribute.

lastname::
The last word in the author attribute.

middlename::
If a firstname and lastname are present, any remaining words or characters found between these attributes are assigned to the middlename attribute.

authorinitials::
The first character of the firstname, middlename, and lastname attributes.

email or contact information::
An email address or contact information such as a social media account, delimited by angle brackets (`< >`).
////
