= AsciiDoc Page Header
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] How to structure a valid AsciiDoc page header.
* [x] How to set a page title.
* [x] Where the page title is used in the published site.
* [x] How to set and use AsciiDoc's built-in page attributes.
* [x] How to add page metadata.

== Page header anatomy

.Common elements in a page header
[source,asciidoc]
----
= Page Title // <1>
First Middle Last <author@email.com> // <2>
revnumber, revdate: revremark // <3> <4> <5>
:description: A description of the page stored in an HTML meta tag. // <6>
:keywords: comma-separated values, stored, in an HTML, meta, tag // <7>
:sectanchors: // <8>
:url-repo: https://my-git-repo.com // <9>
----
<1> Title of the page
<2> Author name and email address
<3> Page revision number
<4> Page revision date
<5> Page revision remarks
<6> Page description that is stored in the HTML `meta` tag `description`
<7> Comma-separated list of values that are stored in the HTML `meta` tag `keywords`
<8> Example of a built-in page attribute
<9> Example of a user created and defined page attribute

== Page title

== Built-in page attributes

== Page metadata
