= What's New in Antora
:doctype: book
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases
:url-gitlab: https://gitlab.com
:url-git-antora: {url-gitlab}/antora/antora
:url-issues: {url-git-antora}/issues
:url-milestone-2-2-0: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%202.2.0
:url-mr: {url-git-antora}/merge_requests

= Antora 2.2.0

_**Release date:** 2019.10.31 | *Issue label:* {url-milestone-2-2-0}[2.2.0^]_

== Resolved issues

=== Added

Issue {url-issues}/292[#292^]:: Allow edit URL to be configured from pattern or disabled in playbook using the `edit_url` key on the content category or specific content source.
Additionally, store the edit URL and file URI independently so both values are accessible via the UI model.
Issue {url-issues}/219[#219^]:: Generate a robots.txt file if the `site.robots` key is set in the playbook.
Issue {url-issues}/374[#374^]:: Prune stale branches and tags when fetching repository updates.
Issue {url-issues}/412[#412^]:: Add support for `lines` attribute on include directive, which can be used to filter lines by line numbers or line number ranges.
Issue {url-issues}/497[#497^]:: Preserve stack from original clone error thrown by git client.

=== Changed

Issue {url-issues}/476[#476^]:: Upgrade git client (isomorphic-git); new index cache may improve performance.
Issue {url-issues}/510[#510]:: The `tags` and `branches` keys override the inherited (global) value even if the values are falsy.
Issue {url-issues}/513[#513]:: Clean embedded auth from remote URL resolved from git config of local repository.
Issue {url-issues}/505[#505]:: Be more strict about detecting semantic component versions when sorting.

== Customizable edit URL

By default, Antora automatically computes the edit URL for all files it takes from a remote repository or a local repository connected to a remote repository, if possible.
"`If possible`" means this works if the remote repository is located on the primary GitHub, GitLab, BitBucket, or Pagure hosted services.
What was lacking in previous versions of Antora was support for other git hosts (e.g., on-prem GitLab) or to be able to customize or disable the value.
If the automatic value of the edit URL doesn't work in your case, you can now customize it using the playbook.

You can use the `edit_url` key to control the edit URL.
This optional key can be set directly on the `content` category to apply to all content sources or on an individual content source entry to override that inherited value.

By default, the value of the `edit_url` is `true`, which tells Antora to use the existing behavior of computing the edit URL automatically.

If the value of the `edit_url` is a string, it's interpreted as a pattern.
That pattern supports the following placeholders, which are fulfilled by the file's origin information:

\{web_url}:: The web URL for the git repository from which the file was taken.
This value is derived automatically from the repository URL (by converting the protocol to `https` and dropping the `.git` extension, if necessary).
\{refname}:: The name of the reference (i.e., branch or tag) from which the file was taken.
\{path}:: The path of the file from the root of the repository (regardless of whether the content source defines a `start_path`).

For example, to configure the edit URL to point to the view page of a file on GitHub, you'd use the following entry:

[source,yaml]
----
content:
  sources:
  - url: https://github.com/asciidoctor/asciidoctor.git
    edit_url: '{web_url}/blob/{refname}/{path}'
----

If, instead, you want to disable the edit URL, set the value to `false`.

[source,yaml]
----
content:
  edit_url: false
----

or

[source,yaml]
----
content:
  sources:
  - url: https://github.com/asciidoctor/asciidoctor.git
    edit_url: false
----

As part of this change, the edit URL no longer points to the file URI when a file is taken from the worktree (local file tree).
Instead, the file URI is stored separately.
Both values are passed to the UI model as `editUrl` and `fileUri`, respectively.
This gives the UI template control over whether to use the file URI when available, or whether to ignore it and use the edit URL instead.

The default UI has been updated to use the value of the `fileUri` for the edit link if it is set and the `CI` environment variable is not set (i.e., `(and page.fileUri (not env.CI))`).
Otherwise, it falls back to using the `editUrl` if the repository is public (i.e., `(and page.editUrl (not page.origin.private))`).
That change allows the default UI to work with Antora 2.2 as well as earlier versions.

To find out all the details about how this feature works, please refer to the xref:playbook:configure-edit-url.adoc[edit URL configuration page] in the documentation.

== robots.txt generation

When you put a static site online, you want to give a hint to search engines about where to crawl when indexing the site.
Sometimes, you want to give them free rein.
Other times, you want to tell them to back off entirely.
Or, you may want to restrict access to certain portions of the site.
That's the role of the https://en.wikipedia.org/wiki/Robots_exclusion_standard[robots.txt file], stored at the root of the site.

You can now use the `site.robots` key in the playbook file to instruct Antora to generate a robots.txt.

If you want to grant full access, set the value to `allow`:

[source,yaml]
----
site:
  robots: allow
----

If you want to forbid access, set the value to `disallow`:

[source,yaml]
----
site:
  robots: disallow
----

Any other value will be used as the contents of the robots.txt file.
For more details, see xref:playbook:configure-site.adoc#configure-robots[configuring the robots.txt file].

== Filter includes by line numbers

In addition to filtering the lines of an include file by named tags, you can now filter lines by line numbers.
This AsciiDoc feature has already been available in Asciidoctor, but was not previously working in Antora.

Line numbers of specified in the value of the `lines` attribute on the include directive.
Line numbers, which are numbered starting with 1, can be identified as individual entries or as a range.
Multiple entries can be separated either by semi-colons or commas.

For example, here's how you'd select the first line of this page:

[source,asciidoc]
----
\include::./whats-new.adoc[lines=1]
----

Here's how you'd select lines 2 through 10:

[source,asciidoc]
----
\include::./whats-new.adoc[lines=2..10]
----

And here's how you'd select the first line, and all the remaining lines starting at line 10:

[source,asciidoc]
----
\include::./whats-new.adoc[lines=1,10..]
----

For more information about the `lines` attribute on the include directive, refer to the https://asciidoctor.org/docs/user-manual/#by-line-ranges[include by line ranges] section in the Asciidoctor user manual.

== Prune references

When you pass the `--fetch` flag to the `antora` command or set the `runtime.fetch` key in the playbook file to true, Antora fetches updates from all the remote git repositories.
What it was not doing was removing references that had been deleted from the remote repository.
As a result, Antora would discover references (branches and tags) that it should not be finding as the result of a stale cache.
In addition to publishing content it shouldn't publish, Antora would also fail when files from a stale reference conflicted with files from a newer reference (the dreaded duplicate nav or page errors).

Now when Antora reaches out to the remote repositories for updates, it will also remove any references in the cache that have been removed from the remote repository.
In other words, it will do a complete sync.
That means Antora won't discover any references that it shouldn't be finding.
There's nothing you need to do to enable this feature.
It's automatic.

== Disable tags or branches

To disable either tags or branches for a content source entry, you used to have to set the value to an empty array:

[source,yaml]
----
content:
  sources:
  - url: https://git.example.org/org/repo.git
    branches: []
----

Now you can use the special value `~`, which is short for `null` (aka nothing).

[source,yaml]
----
content:
  sources:
  - url: https://git.example.org/org/repo.git
    branches: ~
----

If the `tags` or `branches` key is present on a content source entry, that value takes precedence, regardless of what the value is.

== Documentation changes

TODO

[#thank-you-2-2-0]
== Thank you!

Most important of all, a huge *thank you!* to all the folks who helped make Antora even better.

We want to call out the following people for making contributions to this release:

David Jencks ({url-gitlab}/djencks[@djencks]):: For implementing the robots.txt generation {url-issues}/219[#219^], for helping to get to the bottom of {url-issues}/497[#497^] and come up with a solution, and for helping to improve the documentation.
