= What's New in Antora
:route: New
:doctype: book
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases
:url-gitlab: https://gitlab.com
:url-git-antora: {url-gitlab}/antora/antora
:url-issues: {url-git-antora}/issues
:url-milestone-2-0: {url-issues}?milestone_title=v2.0.x&scope=all&state=closed
:url-mr: {url-git-antora}/merge_requests

Learn about what's new in the 2.0 release series of Antora.

= Antora 2.0.0

_Release date: 2018.12.25 | Addresses these core component {url-milestone-2-0}[issues]_

The Antora 2.0.0 release drastically streamlines the installation process, improves platform and library compatibility, provides a simpler and pluggable authentication mechanism for private repositories, and delivers the latest Asciidoctor capabilities.

TIP: If you need a quick overview of the breaking changes, jump to the <<checklist,upgrade checklist>>.

== Hassle-free installation thanks to isomorphic-git

When Antora launched, nodegit was the only JavaScript git client that provided the features for interfacing with git repositories (clone, fetch, resolve refs, walk trees, read blobs).
Despite the fact that nodegit is a thorough git client, it's proven to be tremendously difficult for users to install.
This difficulty stems from its coupling to native system libraries for compilation, bundling of native libraries, limited (and declining) portability across platforms and Node versions, irregular post-install scripts, reliance on an SSH agent for authentication, and lack of interest in addressing portability concerns.

Since then, a full-fledged alternative has emerged.
Our friend https://github.com/wmhilton[William Hilton] stepped up to create https://isomorphic-git.org/[isomorphic-git], a pure JavaScript git client (hint, it also runs in the browser).
In Antora 2.0, we've completely replaced nodegit with isomorphic-git.

Switching Antora to isomorphic-git not only guarantees a hassle-free installation, but drastically reduces installation time as well.
This improvement is due to the fact that Antora's dependencies no longer rely on native system libraries.
It also means Antora works on all platforms and supported Node versions.

isomorphic-git also allowed us to expand our test coverage and therefore improve Antora's stability.
In fact, isomorphic-git is used to drive all of the git tests in the test suite, and the tests now use proper clone and fetch operations for testing remote repositories.

All-in-all, the switch from nodegit to isomorphic-git is a huge step forward for Antora and the main reason for the major version jump to Antora 2.0.

== Goodbye SSH. Hello git credentials.

Replacing nodegit with isomorphic-git brought with it a breaking change in how Antora handles private repository authentication.
Private repository authentication is now performed using HTTP Basic authentication over HTTPS instead of public/private key authentication over SSH using an SSH agent.

This change makes it easier to manage authentication since Antora no longer requires running an SSH agent.
Instead, authentication credentials can be managed using the git credential store mechanism or a custom credential manager provided by the user.

*If you use private repositories, you'll need to add authentication credentials for each private repository to the default or a custom git credentials store before running Antora 2.0*.
To learn what types of credentials Antora can use for authentication and how to add your credentials to the default credentials store, located at [.path]_$HOME/.git-credentials_, see the xref:playbook:private-repository-auth.adoc[Private repository authentication] documentation.

And you're not locked to this one storage location.
You can influence where Antora looks for credentials using several methods:

* `--git-credentials-path` CLI option to override location of git credential store file
* `GIT_CREDENTIALS_PATH` environment variable to override location of git credential store file
* `git.credentials` key in Antora playbook to override path or contents of git credential store
* `GIT_CREDENTIALS` environment variable to override contents of git credential store

The documentation has examples showing how to xref:playbook:private-repository-auth.adoc#custom-credential-path[specify a custom git credential store path] using each of the methods listed above.

Finally, Antora transparently converts SSH URLs to HTTPS URLs, so you don't have to update your playbook files when you upgrade to Antora 2.0.

=== Pluggable credentials manager

Thanks to isomorphic-git, Antora allows you to register a custom credential manager using `git.cores.create('antora').set('credentialManager', credentialManager)`.
This object completely takes over how credentials are resolved.
Among other benefits, this gives users the option of storing credentials more securely for environments that require it.
See xref:playbook:private-repository-auth.adoc#custom-manager[Configure a custom credential manager] to learn more.

== All the latest Asciidoctor features

Antora 2.0 ships with Asciidoctor.js 1.5.9.
This release of Asciidoctor.js brings the latest Asciidoctor features, updates the Asciidoctor.js API, fixes conflicts with libraries, and offers several nice enhancements to the AsciiDoc syntax.
Here are some of the highlights for each part:

.AsciiDoc
* Nest ordered and unordered lists to an arbitrary depth.
* Autonumber callout markers using the `<.>` syntax.
* Create an xref with automatic text to a list item or table cell.

.Asciidoctor
* Section titles are scrubbed more thoroughly when auto-generating an ID from the text.
* The position of section anchors can be configured (before _or_ after).
* The xref macro now supports attributes (just as the link macro does).
* The `docname` attribute is now set to the complete relative path of the page without the file extension.
* Although not used directly in Antora, all messages are now routed through a logger.

.Asciidoctor.js API (for extension writers)
* An upgrade to Opal means Asciidoctor.js no longer causes cycles when iterating over an object's properties.
* Much more of the Asciidoctor API has been mapped in Asciidoctor.js, making it far easier to write extensions.
* The extension API provides a simple mechanism for generating an extension class (as an alternative to an extension block).
* The AbstractNode#findBy method can be short-circuited to halt the tree walk.

See the release notes for {url-releases-asciidoctor}[Asciidoctor] and {url-releases-asciidoctorjs}[Asciidoctor.js] to find complete details.

== More improvements and changes

Next, previous, and parent pages:: The `next`, `previous`, and `parent` properties are now available in the UI model so your UI can access adjacent pages in the navigation tree.

Versioned cache folder:: Antora uses a versioned cache folder for the cloned git content repositories.
On first run, Antora will re-clone your content repositories into this folder.
This was necessary to avoid conflicts with repositories that were cached using nodegit.

Node compatibility:: Antora now works with Node 10 and 11.

Antora playbook files in TOML:: You can now write Antora playbook files in the TOML configuration language.
The CSON format is no longer supported.
If your Antora playbook is in CSON, you'll need to migrate it to YAML, JSON, or TOML before using Antora 2.0.

page.origin.private:: If a content source requires authentication (either because credentials were defined in the URL or credentials were requested from the credentials manager), the `page.origin.private` property will be set in the UI model.

page.displayVersion:: The display version of a component is now accessible via the UI model using the `page.displayVersion` property.

AsciiDoc doctype:: The AsciiDoc `doctype` option can be safely set in the AsciiDoc configuration key.
Navigation files will always be parsed using the article doctype.

default tags filter:: The default tags filter can now be set using the `content.tags` key in the playbook.

page.latest:: The `page.versions.latest` property in the UI model can now be reached using `page.latest`.

== Known issues

=== Reference pruning

{url-issues}/374[Issue #374]:: After the switch to isomorphic-git, references are no longer pruned when the `--pull` option is specified.
This means that if a reference is removed from the remote repository, it will not be removed from Antora's cached version.
Workaround:: You can clear Antora's cache directory or the cache of the repository in question.
We'll restore this behavior in a future enhancement.

=== Broken 404 pages on sites that aren't served from root folder

{url-issues}/258[Issue #258]:: If your site is not served from the root folder of a domain (such as is the case of sites running on the GitHub Pages or GitLab Pages domain), the references to UI assets and navigation links on the 404 page will not work property.
Workaround:: Postprocess the 404.html page to fix the paths before publishing the site.

== Thank you!

Most important of all, a big *Thank you!* to all the folks who helped make Antora even better.

Abel Salgado Romero ({url-gitlab}/abelsromero[@abelsromero]):: Fix wrong gulp-ci package name replacing it with correct gulp-cli {url-mr}/294[MR 294]

Antonio ({url-gitlab}/bandantonio[@bandantonio])::
Fix colon typo in resource id include directive {url-mr}/284[MR 284] +
Add information about missing runtime category in the playbook configuration {url-mr}/282[MR 282]

Julien Grenier ({url-gitlab}/jgrenier[@jgrenier]):: Fix failing build (docker-antora) https://gitlab.com/antora/docker-antora/merge_requests/5[MR 5]

Matthew Setter ({url-gitlab}/settermjd[@settermjd]):: Correct reference to ui-bundle-url in the docs {url-mr}/280[MR 280]

{url-gitlab}/Leantricity[@Leantricity]:: Fix page-to-page-xref.adoc typo {url-mr}/278[MR 278]

== Metrics

//TODO add Docker metrics
The raw install size of Antora drops from 154MB down to 43MB.
It took 11 seconds to install Antora 1.1.1 from cache; it just takes about 3 seconds to install Antora 2.0.0 from cache.

//as of !307
[%hardbreaks]
Merges: 28
Issues resolved: 25

[#checklist]
include::install:partial$upgrade-checklist.adoc[]
