= What's New in Antora
:doctype: book
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases

Learn about what's new in the 2.0 release series of Antora and how to migrate.

= Antora 2.0.0 (2018-12-20)

The Antora 2.0.0 release drastically streamlines the installation process, improves platform and library compatibility, provides a simpler (and pluggable) authentication mechanism for private repositories, and delivers the latest Asciidoctor capabilities.

== Hassle-free installation thanks to isomorphic-git
// (#264)

When Antora launched, nodegit was the only JavaScript git client that provided the features necessary to interface with git repositories (clone, fetch, resolve refs, walk trees, read blobs).
Despite the fact that nodegit is a very thorough git client, it has proven to be tremendously difficult for users to install.
This difficulty stems from it's coupling to native system libraries for compilation, bundling of native libraries, limited (and declining) portability across platforms and Node versions, irregular post-install scripts, reliance on an SSH agent for authentication, and apparent lack of interest in addressing portability concerns.

Since then, a full-fledged alternative has emerged.
Our friend https://github.com/wmhilton[William Hilton] stepped up to create https://isomorphic-git.org/[isomorphic-git], a pure JavaScript git client (which also runs in the browser, btw).
In Antora 2.0.0, nodegit has been completely replaced by isomorphic-git.

Switching Antora from nodegit to isomorphic-git not only guarantees a hassle-free installation, but drastically reduces installation time as well.
This improvement is due to the fact that Antora's dependencies no longer rely on native system libraries.
It also means Antora will immediately work on all platforms as well as all Node versions starting with Node 8.

isomorphic-git also allowed us to expand our test coverage and therefore improve Antora's stability.
In fact, isomorphic-git is used to drive all git tests in the test suite, and the tests now use proper clone and fetch operations for testing remote repositories.

All-in-all, the switch from nodegit to isomorphic-git is a huge step forward for Antora and the main reason for the major version jump to Antora 2.

== Goodbye SSH. Hello git credentials.
// (#264)

Replacing nodegit with isomorphic-git did introduce a breaking change in how Antora handles private repository authentication.
Private repository authentication is now performed using HTTP Basic Authentication over HTTPS instead of public/private key authentication over SSH using an SSH agent.

Thankfully, this change makes it much easier to manage authentication since Antora no longer requires running an SSH agent.
And Antora transparently converts SSH URLs to HTTPS URLs so users don't have to update their playbook files.
All that's necessary to fill in your authentication credentials.

Authentication credentials can be managed using the git credential store mechanism or a custom credential manager provided by the user.
By default, Antora will look for credentials in the default credential store file ([.path]_$HOME/.git-credentials_).
If you're using private repositories with Antora, you'll need to add one line to this file per git host using the following format:

----
https://<credentials>@<hostname>
----

`<hostname>` looks like `github.com`.
`<credentials>` consists of either a username and password (e.g., `octocat:ilovegit`) or--if you have two-factor authentication (2FA) enabled--a personal access token (e.g., `abcdefgh0123456`).

Where Antora looks for credentials can be influenced using several options:

* `--git-credentials-path` CLI option
* `git.credentials` key (path or contents) in an Antora playbook
* `GIT_CREDENTIALS_PATH` environment variable to override location of git credential store file.
* `GIT_CREDENTIALS` environment variable to override contents of git credential store.

=== Pluggable credentials manager

Another option is to register a custom credential manager with isomorphic-git using `git.cores.create('antora').set('credentialManager', credentialManager)` to completely take over how credentials are resolved.
Among other benefits, this gives users the option of storing credentials more securely for environments that require it.

== All the latest Asciidoctor features
// (#290)

Antora 2.0.0 ships with Asciidoctor.js 1.5.9.
This release of Asciidoctor.js brings the latest Asciidoctor features, updates the Asciidoctor.js API, fixes conflicts with libraries, and offers several nice enhancements to the AsciiDoc syntax.
Here are some of the highlights for each part:

.AsciiDoc
* You can now nest ordered and unordered lists to an arbitrary depth.
* You can autonumber callout markers using the `<.>` syntax.
* You can now create a xref with automatic text to a list item or table cell.
* The text of a block title can begin with a period.

.Asciidoctor
* Section titles are scrubbed more thoroughly when auto-generating an ID from the text.
* The position of section anchors can be configured (before _or_ after).
* Parts are numbered when the `partnums` attribute is set.
* The xref macro now supports attributes (just as the link macro does).
* The `docname` attribute is now set to the complete relative path of the page without the file extension.
* Although not used directly in Antora, all messages are now routed through a logger.

.Asciidoctor.js API (for extension writers)
* An upgrade to Opal means Asciidoctor.js no longer causes cycles when iterating over an object's properties.
* A lot more of the Asciidoctor API has been mapped in Asciidoctor.js, making it far easier to write extensions.
* The extension API provides a simple mechanism for generating an extension class (as an alternative to an extension block).
* The AbstractNode#findBy method can be short-circuited to halt the tree walk.

See the release notes for {url-releases-asciidoctor}[Asciidoctor] and {url-releases-asciidoctorjs}[Asciidoctor.js] to find complete details.

== More improvements and changes

Next, previous, and parent pages:: The `next`, `previous`, and `parent` properties are now available in the UI model so your UI can access adjacent pages in the navigation tree.
// (#233)

Versioned cache folder:: Antora uses a versioned cache folder for the cloned git content repositories.
On first run, Antora will re-clone your content repositories into this folder.
This was necessary to avoid conflicts with repositories that were cached using nodegit.

Node compatibility:: Antora works with Node 10 and 11 in addition to Node 8.

Antora playbook files in TOML:: You can now write Antora playbook files in the TOML configuration language.
The CSON format is no longer supported.

page.origin.private:: If a content source requires authentication (either because credentials were defined in the URL or credentials were requested from the credentials manager), the `page.origin.private` property will be set in the UI model.

page.displayVersion:: The display version of a component is now accessible via the UI model using the `page.displayVersion` property.
//(#362)

AsciiDoc doctype:: The AsciiDoc `doctype` option can be safely set in the AsciiDoc config.
Navigation files will always be parsed using the article doctype.
//(#376)

ANTORA_PLAYBOOK:: The PLAYBOOK environment variable has been renamed to ANTORA_PLAYBOOK.
This is a breaking change.

default tags filter:: The default tags filter can now be set using the `content.tags` key in the playbook.

page.latest:: The `page.versions.latest` property in the UI model can now be reached using `page.latest`.

== Known issues

=== Reference pruning (#374)

Issue:: After the switch to isomorphic-git, references are no longer pruned when the `--pull` option is specified.
This means that if a reference is removed from the remote repository, it will not be removed from Antora's cached version.
Workaround:: You can clear Antora's cache directory or the cache of the repository in question.
We'll restore this behavior in a future enhancement.

=== Broken 404 pages on sites that aren't served from root folder (#258)

Issue:: If your site is not served from the root folder of a domain (such as is the case of sites running on the GitHub Pages or GitLab Pages domain), the references to UI assets and navigation links on the 404 page will not work property.
Workaround:: Postprocess the 404.html page to fix the paths before publishing the site.

== Thank you!

Most important of all, a big *Thank you!* to the folks that helped make Antora even better.

*TODO: Add community shout outs!*

== Metrics

The raw install size of Antora drops from 154MB down to 43MB.
It takes about 3s to install Antora 2.0.0 from cache, which is down from 11s to install Antora 1.1.1.

//Total Merges:
//Total Issues (References? Closed?)
//Contributors:

////
== Upgrade instructions

If you're not using private repositories, the only thing you need to do to migrate is to upgrade Antora (making sure the version is set to 2.0.0).

If you use private repositories, you need to reconfigure how you authenticate.
For each git host, you'll either need a username and password or, if you have two-factor authentication (2FA) enabled, a personal access token.

*??? I think I want to move the following instructions to their final location in the documentation (either as a page or an include file) and then provide a link/include ... but I'm still thinking about it.*

Add the following entry to the [.path]_$HOME/.git-credentials_ file.

```
https://<credentials>@github.com
```

Where `<credentials>` is either `username:password` or `token`.

Next, change the mode of this file to 600 so that only the current user can read it:

```
$ chmod 600 $HOME/.git-credentials
```

Antora will automatically detect this file and use it to authenticate with repositories that require authentication.

You can also use git to populate this file.
First, put an HTTPS URL to a private git repository in your clipboard.
Now run, the following commands:

```
$ mkdir set-up-credentials
  cd set-up-credentials
  git init .
  git config --local credential.helper store
  git fetch <url>
```

Now enter your username/password or token when prompted.
If authentication succeeds, git will save the credentials in [.path]_$HOME/.git-credentials_.

You can also pass the path to this file using the `--git-credentials-path` CLI option.
////
