= UI Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] How to retrieve the UI bundle via a URL or local path.
* [x] How to specify a start path inside the bundle.
* [x] How to set a default UI layout.
* [x] How to configure an output directory for the UI files.

The ui key contains an array of UI bundle and page layout specifications.

== UI bundle

The bundle key (`bundle`) provides the location where Antora should find a UI ZIP archive.
The key accepts a URI or filesystem path.

[#remote-bundle]
=== Fetch a UI bundle from a remote repository

When the value for `bundle` is a URI, Antora downloads the ZIP archive and caches it to avoid downloading the UI bundle each time you build your site.

.Remote UI bundle
[source,yaml]
----
ui:
 bundle: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
----

The value in this example is the URL to Antora's default UI.

[#local-bundle]
=== Load a UI bundle from a local path

The UI bundle can be loaded from an absolute or relative filesystem path.
When the value is a relative path, the path is resolved relative to the playbook file.

.Relative UI bundle path
[source,yaml]
----
ui:
 bundle: ../ui/build/ui-bundles.zip
----

Here's the path to the same UI bundle, but using an absolute path.

.Absolute UI bundle path
[source,yaml]
----
ui:
 bundle: /home/user/projects/docs-beta/ui/build/ui-bundles.zip
----

[#start-path]
=== Specify a UI start directory

The `start_path` is the relative path inside the bundle from where Antora should start reading files.
This key is useful when you have more than one UI packaged in the same archive.

.UI files' start_path
[source,yaml]
----
ui:
 bundle: /home/user/projects/docs-beta/ui/build/ui-bundles.zip
 start_path: dark-theme
----

In this example, Antora will ignore all of the files in the UI bundle that fall outside of the directory [.path]_dark-theme_.

[#default-layout]
== Apply a default layout

A default layout template can be assigned to all of the pages that don't have a template explicitly assigned to them in their page header.
The `default_layout` accepts a value that is the stem (i.e., don't include the file extension) of a layout file.
The layout file should be stored in the UI bundle directory [.path]_src/layouts_.

For example, if you want to use a layout named [.path]_article.hbs_ as the default, the `default_layout` value would be `article`.

.Default layout value
[source,yaml]
----
ui:
 bundle: ../ui/build/ui-bundles.zip
 default_layout: article
----

== Default UI output directory

The UI files are published to a directory labeled with a single [.path]+_+ (underscore) that is located relative to the site's output directory.
For instance, when the site is published to the xref:configure-output.adoc#output-dir[default destination directory] ([.path]_build/site_), and no UI `output_dir` is specified, the UI files are written to [.path]_build/site/{blank}__.

[#output-dir]
=== Specify an output directory

The output directory key (`output_dir`) allows you to specify the directory where Antora should publish the UI files.
The path must be relative to the directory where the site is to be published

.Relative UI output path
[source,yaml]
----
ui:
 bundle: /home/user/projects/docs-beta/ui/build/ui-bundles.zip
 output_dir: _ui
----

In this example, the site will be written to the default destination directory, therefore, the UI files will be published [.path]_build/site/{blank}_ui_.

In the next example, the site's output directory (`dir`) has been specified in addition to the UI output directory.

.Custom site and UI directory
[source,yaml]
----
ui:
 bundle: /home/user/projects/docs-beta/ui/build/ui-bundles.zip
 output_dir: _ui
output:
 dir: public
----

The UI files will be published to [.path]_public/{blank}_ui_.

//supplemental_files: Supplemental file list or a directory of files to append to the UI bundle.
