= Edit URL Configuration
:xrefstyle: short
:listing-caption: Example

Antora automatically provides edit URLs for pages that are sourced from the hosted GitLab, GitHub, Bitbucket, and Pagure services.
In the default UI, the *Edit this Page* link in the upper right corner of the page uses the computed edit URL to link a visitor to edit interface provided by the hosted git service for that particular source file.
For instance, if you click the *Edit this Page* link on this page, you'll go to GitLab's file editing page and the AsciiDoc source file will be loaded into the interface.

== edit_url key and value

The edit_url key is useful when you're using an unsupported git solution or you want the *Edit this Page* feature to link to an alternative source file location, such as the git solution's raw view or rendered preview of a page's source file.

The `edit_url` key is set in the playbook and can be applied to all of the content sources or customized per individual source.
The key accepts a URL pattern that contains the URL segments of the git solution or source file view plus three placeholder segments, `{url}`, `{refname}`, and `{path}`.

[#ex1]
.edit_url key and value
[source,yaml]
----
edit_url: '{url}/blob/{refname}/{path}' # <1>
----
<1> Enclose the value of `edit_url` in single quotation marks (`'`) when it starts with a curly bracket (`{`).

<<ex1>> shows a hypothetical edit URL pattern containing the three placeholders.
The word _blob_ is an example of a URL segment that isn't represented by a placeholder.
In the following sections, we'll explain the role of the three placeholders and where they should be positioned in the `edit_url` value.

=== How does Antora assemble an edit URL for a page?

When the `edit_url` is set, either by default or explicitly, on a content source, Antora automatically computes the value of the `{url}`, `{refname}`, and `{path}` placeholders for each individual page.
Then, using the pattern assigned to the `edit_url` key, it assembles each page's unique edit URL.

url:: The `{url}` placeholder is the corresponding web URL for the content source repository that Antora automatically computes from its git URL.
For example, [.path]_\https://gitlab.com/antora/antora.git_ is converted to [.path]_\https://gitlab.com/antora/antora_.
This placeholder can be omitted if the URL pattern explicitly includes the web URL for the content source repository.

refname:: The `{refname}` is the name of the git reference (e.g., v2.1.x, master, rawhide).

path:: The `{path}` is the path of the source file relative to the root of the repository, including the start path.

Let's examine the resulting edit URL for the page generated from a file named [.path]_index.adoc_ that's stored in content source shown in <<ex2>>.

[#ex2]
.Edit URL value pattern
[source,yaml]
----
content:
  sources:
  - url: https://app.company.com/the-group/schwoop.git
    branches: [v1.2.5, next]
    edit_url: '{url}/_src/{refname}/u890/{path}'
----

Let's determine what the edit URL would look like for the page generated from a file named [.path]_index.adoc_.
The [.path]_index.adoc_ file is stored in branch v1.2.5 of the schwoop repository in the pages directory of the ROOT module.
Using the URL pattern assigned to `edit_url` in <<ex2>>, Antora would compute the following edit URL for [.path]_index.adoc_.

[#ex3]
.Edit URL for index.adoc using the inputs from <<ex2>>
----
https://app.company.com/the-group/schwoop/_src/v1.2.5/u890/modules/ROOT/pages/index.adoc
----

Antora replaces `{url}` with the content source's web URL.
In this case, the _.git_ is dropped from the end of the value of `url`.
`{refname}` is replaced with the _v1.2.5_ git branch reference.
Finally, `{path}` is replaced by the path to the source file, relative to the root of the repository.
Since this source doesn't have a specified start path, the resulting path is _modules/ROOT/pages/index.adoc_.

When a content source has an assigned `start_path`, Antora prepends it to `{path}`.

[#ex4]
.Content source with start_path and edit_url set
[source,yaml]
----
content:
  sources:
  - url: https://app.company.com/the-group/schwoop.git
    branches: [v1.2.5, next]
    start_path: learn/docs
    edit_url: '{url}/_src/{refname}/u890/{path}'
----

Using the inputs from <<ex4>>, the edit URL for [.path]_index.adoc_ would be:

[#ex5]
.Edit URL for index.adoc using the inputs from <<ex4>>
----
https://app.company.com/the-group/schwoop/_src/v1.2.5/u890/learn/docs/modules/ROOT/pages/index.adoc
----

=== Where do I put the placeholders in the edit_url pattern?

//https://gitlab.com/antora/antora/blob/master/docs/modules/cli/pages/index.adoc

== Apply a custom edit URL to all content sources

An `edit_url` can be applied to all of your content sources by setting the key directly on the `content` key.

[source,yaml]
----
content:
  edit_url: '{url}/_src/{refname}/u890/{path}'
  sources:
  - url: https://app.company.com/the-group/schwoop.git
    branches: [v1.2.5, next]
    start_path: learn/docs
  - url: https://app.company.com/city/team-l/kapow.git
    branches: v2.*
  - url: https://app.company.com/city/team-l/bam.git
    branches: release/*
----

== Apply custom edit URLs to individual content sources

When the `edit_url` key is set on an individual content source, it applies only to that content source.
For instance, let's set the `edit_url` on the kapow repository but not on the fizz repository.

[source,yaml]
----
content:
  sources:
  - url: https://app.company.com/city/team-l/kapow.git
    branches: v2.*
    edit_url: `{url}/_src/{refname}/u890/{path}`
  - url: https://gitlab.com/wow/fizz.git
    branches: v*
----
