= Site Configuration

On this page, you'll learn:

* [x] How to add a title to the site.
* [x] How to configure the site's base URL.
* [x] How to assign a site start page.
* [x] How to associate the site with a Google Analytics account.

[#configure-title]
== Add a site title

Use the title key (`title`) to add a title to your site.

[source,yaml]
----
site:
  title: Demo Docs Site
----

The title is displayed wherever the site's UI calls this key.
Antora's default UI displays the site title in the navigation bar at the top of the site.

[#configure-url]
== Configure the base URL

The site URL key (`url`) defines the optional base URL of the published site.

If set, the URL must be absolute and *should not contain a trailing slash* (e.g., _\https://docs.example.com_).
The URL may end with a pathname (i.e., subpath) (e.g., _\https://example.com/docs_).

IMPORTANT: The `url` value must start with a valid URL scheme directly followed by a colon and two slashes (`://`).
Common URI schemes include `https://`, `http://`, and `file://`.

[source,yaml]
----
site:
  url: https://demo.antora.org
----

The site URL is only used when an absolute URL is required.
It also implicitly activates features that require an absolute URL.
Those features are the sitemaps, the 404 page, and the canonical URL property in the UI model.

If the site URL is set, Antora will produce sitemap files and include the canonical URL in the head of each page.
In those instances, the component, version, module, and page segments are appended to the site URL to produce the complete URL.
For example,  _\https://docs.example.org/component/version/page.html_.
Antora will also generate the 404 page.

[#configure-start-page]
== Configure the site start page

You can use a page from a documentation component as the index page for your site.
When a start page is specified, visitors are redirected from the site's index page at the base URL to the URL of the start page.

The start page key (`start_page`) accepts a xref:page:page-id.adoc[page ID] as a value.

=== Use a specific version

If you want the site's start page to be a specific version of the designated page, include the xref:page:page-id.adoc#id-version[version in the page ID].

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: 1.0@component-b::index.adoc
----

In this example, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/1.0/index.html_.

=== Use the latest version

If you want the start page to always point to the last version of the page you designate, don't include a version in the page ID.

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: component-b::index.adoc
----

For this example, let's say that version 2.0 is the latest version of Component B.
In this case, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/2.0/index.html_.

[#configure-ga]
== Add a Google analytics account

Account keys for services can be passed to Antora using the `keys` subcategory.
The `google_analytics` key assigns a Google Analytics account to the site.

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  keys:
    google_analytics: 'XX-123456'
----

The account key must be enclosed in single quotation marks (`'`).
