= Site Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

On this page, you'll learn:

* [x] How to add a title to the site.
* [x] How to configure the site's base URL.
* [x] How to assign a site start page.
* [x] How to associate the site with a Google Analytics account.

[#configure-title]
== Add a site title

Use the title key (`title`) to add a title to your site.

[source,yaml]
----
site:
  title: Demo Docs Site
----

The title is displayed wherever the site's UI calls this key.
Antora's default UI displays the site title in the navigation bar at the top of the site.

[#configure-url]
== Configure the base URL

The site URL key (`url`) is the base URL of the published site.

The `url` value must be a valid URI scheme that is directly followed by a colon and two slashes (`://`).
Common URI schemes include `https://`, `http://`, and `file://`.

The URI should be absolute, e.g., _\https://www.project.org/docs_ or _\https://docs.product.com_.
The base URL *should not end with a trailing slash*.

[source,yaml]
----
site:
  url: https://demo.antora.org
----

When the site is generated, the component, version, module, and page URL segments are appended to the site URL, e.g.,  _\https://demo.antora.org/component/version/page.html_.

[#configure-start-page]
== Configure a start page for the base URL

You can use a page from a documentation component as the index page for your site.
When a start page is specified, visitors are redirected from the site's base URL index page to the URL of the start page.

The start page key (`start_page`) accepts a xref:ROOT:page-id.adoc[page ID] as a value.

=== Use a specific version

If you want the site's start page to be a specific version of the assigned page, include the xref:ROOT:page-id.adoc#id-version[version name in the page ID].

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: 1.0@component-b::index.adoc
----

In this example, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/1.0/index.html_.

=== Use the latest version

Don't include the version name in the page ID when the start page should always be the latest version of that page.

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: component-b::index.adoc
----

For this example, let's say that version 2.0 is the latest version of Component B.
Therefore, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/2.0/index.html_.

[#configure-ga]
== Add a Google analytics account

Account keys for services can be passed to Antora using the `keys` subcategory.
The `google_analytics` key assigns a Google Analytics account to the site.

[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  keys:
    google_analytics: 'XX-123456'
----

The account key must be enclosed in single quotation marks (`'`).
