= Output Keys
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] How to configure the output directory key.
* [x] How to configure the destinations provider key.
* [x] How to configure the destinations path key.

== Directory key

The output dir key specifies the directory where the generated site will be published.
The value should not contain a leading forward slash or trailing forward slash (`/`).

=== Default output directory

The default output directory value is [.path]_build/site_.
All of the site files will be written into this directory.

[#add-dir]
=== Specify output directory

In this example, the site will be published to a folder named [.path]_launch_.

.Dir path
[source,yaml,subs=attributes+]
----
output:
 dir: launch
----

== Provider key

The destinations provider key specifies the protocol Antora should use to publish the site.

Antora has two built-in provider protocols.

.Built-in providers
* Filesystem (`fs`)
* Archive (`archive`)

You can also create custom providers for SSH, SFTP, etc.

=== Default provider

The default provider protocol is the filesystem (`fs`).
When no provider is specified, Antora publishes the site to the local filesytem at the default output directory location or the location specified by the dir key.

[#add-archive]
=== Publish a site as a ZIP file

The `archive` provider publishes a site as a ZIP file.

.Archive provider
[source,yaml,subs=attributes+]
----
output:
 destinations:
 - provider: archive
----

In this example, the archived site will be located at [.path]_build/site.zip_.

== Path key

The path key allows you to add file paths per provider.
The value should not contain a leading forward slash or a trailing forward slash (`/`).

=== Default path values

The default filesystem (`fs`) path is the same as the default output directory value ([.path]_build/site_).
This is because `fs` is the default provider.

The default archive provider path is [.path]_build/site.zip_.

[#archive-path]
=== Specify an archive path

You can specify the name and path of the site archive with the path key.

In this example, the archived site will be located at [.path]_build/blue.zip_.

.Archive provider path
[source,yaml,subs=attributes+]
----
output:
 destinations:
 - provider: archive
   path: blue.zip
----

When a value is assigned to the output directory key, the archive path is appended to the `dir` path.

.Dir and archive provider path
[source,yaml,subs=attributes+]
----
output:
 dir: launch/sites
 destinations:
 - provider: archive
   path: blue.zip
----

In this example, the archived site will be located at [.path]_launch/sites/blue.zip_.

=== Specify fs and archive path

In this example, the site will be published to two different locations.

.fs and archive paths
[source,yaml,subs=attributes+]
----
output:
 destinations:
 - provider: fs
   path: red
 - provider: archive
   path: blue.zip
----

The site published via the `fs` provider will be located at [.path]_build/site/red_.
The site published via `archive` will be located at [.path]_build/blue.zip_.
