= Playbook Configuration Schema
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:idprefix:
:idseparator: -
:experimental:

On this page, you'll learn:

* [x] How to structure an Antora playbook.
* [x] The role of each playbook key.
* [x] The values each playbook key accepts.

== Playbook file structure

Here's a factitious example of a playbook file if all the keys were defined.

WARNING: This example is merely for reference and is not intended to be copied.

[source,yaml]
----
site: # <1>
  title: Demo Docs Site # <2>
  url: https://demo.antora.org # <3>
  start_page: demo-component-b::index # <4>
  keys: # <5>
    google_analytics: XX-123456 # <6>
content: # <7>
  sources: # <8>
  - url: https://gitlab.com/antora/demo/demo-component-a.git # <9>
    branches: master # <10>
    tags: v* # <11>
    start_path: docs # <12>
ui: # <13>
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable # <14>
    snapshot: true
  start_path: dark # <15>
  default_layout: base # <16>
  output_dir: _/dark # <17>
output: # <18>
  clean: true # <19>
  dir: ./public # <20>
  destinations: # <21>
  - provider: archive # <22>
----
<1> <<site-key,Site keys>>
<2> <<site-title-key,Title key>>
<3> <<site-url-key,Base URL key>>
<4> <<site-start-page-key,Start page key>>
<5> <<site-service-keys,Service keys>>
<6> <<site-ga-key,Google analytics key>>
<7> <<content-sources-keys,Content keys>>
<8> <<content-sources-keys,Sources keys>>
<9> <<sources-url-key,Content repository URL key>>
<10> <<branches-key,Content repository branches key>>
<11> <<tags-key,Content repository tags key>>
<12> <<sources-start-path-key,Content repository start path key>>
<13> <<ui-keys,UI keys>>
<14> <<ui-bundle-key,UI bundle repository key>>
<15> <<ui-start-path-key,Bundle start path key>>
<16> <<ui-default-layout-key,UI default layout key>>
<17> <<ui-output-dir-key,UI output directory key>>
<18> Published output keys
<19> Clean output directory key
<20> Output directory key
<21> Output destinations key
<22> Output provider key

Let's explore the purpose and usage of each key and its values.

[#site-key]
== Site keys

The site's global properties are defined under the `site` category in the playbook schema.
Antora applies these properties to the whole site when it is generated.

[#site-title-key]
=== title

The title of the documentation site.

Learn more:

* xref:configure-site.adoc#configure-title[Add a title to the site]

[#site-url-key]
=== url

The url key is the base URL of the published site.

Learn more:

* xref:configure-site.adoc#configure-url[Configure the site's base url]

[#site-start-page-key]
=== start_page

You can use a page from a documentation component as the index page for your site.
The start page key accepts a xref:ROOT:page-id.adoc[page ID] as a value.

Learn more:

* xref:configure-site.adoc#configure-start-page[Configure a start page for the base url]

[#site-service-keys]
=== keys

The account keys for global site services such document search tools and Google Analytics.

[#site-ga-key]
==== google_analytics

This key associates a Google Analytics account with the site.

Learn more:

* xref:configure-site.adoc#configure-ga[Add a Google Analytics account key to the site]

[#content-sources-keys]
== Content and sources keys

The `content` category contains an array of source repository specifications.
These source repository specifications are arranged under the `sources` category.

The sources key contains the list of git repository locations, branch name patterns, and other repository properties that Antora uses when aggregating the site content.

[#sources-url-key]
=== url

The url key tells Antora where to find a documentation component's repository.
The key accepts any URI that git supports, including a local filesystem path.

Learn more:

* xref:configure-content-sources.adoc#local-urls[Use local content repositories]
* xref:configure-content-sources.adoc#remote-urls[Fetch remote content repositories]
* xref:configure-content-sources.adoc#author-urls[Configure remote and local content repository URLs in the same playbook]
* xref:configure-content-sources.adoc#mix-local-remote-branches[Mix local and remote repositories and branches]

[#branches-key]
=== branches

The branches key accepts a list of branch name patterns, either as exact names or shell glob patterns (`v3.*`).
When no branches are specified for a sources `url`, Antora will use the [.term]_default branches set_, i.e., the `master` branch and every branch that begins with `v`.

Learn more:

* xref:configure-content-sources.adoc#default-branch[Use or modify the default branches set]
* xref:configure-content-sources.adoc#separate-branch-names[Separate branch names with commas or markers]
* xref:configure-content-sources.adoc#exact-branch[Specify branches by name]
* xref:configure-content-sources.adoc#glob-branch[Specify and exclude branches by glob patterns]
* xref:configure-content-sources.adoc#current-branch[Use the current local branch (HEAD)]
* xref:configure-content-sources.adoc#mix-local-remote-branches[Mix local and remote branches and repositories]

[#tags-key]
=== tags

The tags key (`tags`) accepts a list of tag name patterns, either as exact names or shell glob patterns.

Learn more:

* xref:configure-content-sources.adoc#default-tag[Set a default sources tag]
* xref:configure-content-sources.adoc#mix-branches-and-tags[Use tags and branches from the same content repository]

[#sources-start-path-key]
=== start_path

Antora automatically looks for the xref:ROOT:component-descriptor.adoc[component descriptor] file at the root of a repository.
When the documentation component isn't stored at the root, you need to specify the repository relative path to the component descriptor's location using `start_path`.

Learn more:

* xref:configure-content-sources.adoc#add-start-path[Specify a start path for a content repository]

[#ui-keys]
== UI keys

The `ui` category contains keys that specify the location of the UI bundle and how it should be processed.

[#ui-bundle-key]
=== url

The url key under the `bundle` subcategory accepts a URL or local filesystem path to a UI bundle ZIP archive.
The filesystem path can be absolute or relative.

Learn more:

* xref:configure-ui.adoc#remote-bundle[Fetch and load a remote UI bundle]
* xref:configure-ui.adoc#local-bundle[Load a local UI bundle]

[#ui-snapshot-key]
=== snapshot

The snapshot key under the `bundle` subcategory indicates whether the URL points to a snapshot (i.e., it doesn't always point to the same artifact).
By default, Antora assumes that URL is permanent.

Learn more:

* xref:configure-ui.adoc#snapshot[Mark a URL as a snapshot]

[#ui-start-path-key]
=== start_path

The start path key under the `bundle` category is the path inside the bundle from which UI files should be selected.
When no value is specified, it defaults to the root of the bundle.

Learn more:

* xref:configure-ui.adoc#start-path[Specify a start path for the UI files]

[#ui-default-layout-key]
=== default_layout

The default layout key applies a layout template to pages that don't specify a page layout.

Learn more:

* xref:configure-ui.adoc#default-layout[Specify a default page layout template in the playbook]

[#ui-output-dir-key]
=== output_dir

This key specifies the output directory path where the UI files are written in the published site.
When the UI `output_dir` isn't specified, the files are published to the [.path]_++_++_ directory relative to the root of the published site.

Learn more:

* xref:configure-ui.adoc#output-dir[Specify an output directory for the UI files]

== Output keys

The `output` category contains common output settings and a list of destination specifications.
The destination specifications tell Antora which provider(s) to use to publish the site (e.g., fs, archive, ssh, s3) and where those files should go.
The provider, in turn, determines which transport protocol to use (local, SSH, HTTP, etc.) and manages the low-level details of publication.

The output key is not required.

[#clean-key]
=== clean

The clean key is a boolean.
By default, it's set to false (turned off).
When true (turned on), it will remove the destination path recursively before generating the site.
This key only applies to the filesystem providers currently.

WARNING: Use this key with great care.
For example, if you set `dir` to your computer's home directory and `clean` to true, you will delete ALL of the folders and files in your home directory.

[#dir-key]
=== dir

The output dir key specifies the directory to publish the generated site files.
The key accepts a relative or absolute filesystem path.

If the destinations are unspecified, and the dir key is not set, the value defaults to [.path]_build/site_.

IMPORTANT: The dir key overrides the path key of the first `fs` provider in the list of destinations.
This allows the output directory to be overridden from the CLI using the `--to-dir=<dir>` option.

Learn more:

* xref:configure-output.adoc#output-dir[Specify an output directory]

=== destinations

The destinations key contains a list of specifications that determine how, by which provider, and where the site will be published.
A site can be published to multiple destinations.

When no destinations are specified, Antora publishes the site to the local filesystem at the location specified by the dir key or, if the dir key is not specified, the default output directory location ([.path]_build/site_).

To disable publishing entirely, including the default output, set destinations to an empty array (`[]`).

==== provider

The provider key specifies the transport protocol Antora should use for publishing the generated site.
Antora has two built-in providers, `fs` (filesytem) and `archive` (ZIP archive).
This value is also an extension point that can be used to delegate to a custom provider, such as SSH, S3, etc.
The default provider is `fs`.

Learn more:

* xref:configure-output.adoc#archive-path[Publish the site as a ZIP file]
* xref:configure-output.adoc#multiple-destinations[Specify multiple publishing destinations]

==== path

The path key designates the target location where the output file(s) are to be written.
The value gets interpreted appropriately by each provider.
For example, the `fs` provider treats this value as a target directory, while the `archive` provider treats it as the target file.

If the path key is not specified, it typically gets populated with a default value.
The default `fs` path is [.path]_build/site_, and the default `archive` path is [.path]_build/site.zip_.
The key accepts a relative or absolute filesystem path.

IMPORTANT: If you set the dir key in the playbook or via the CLI, its value will override the `path` value for the first `fs` provider specified in the destinations key.

Learn more:

* xref:configure-output.adoc#archive-path[Specify ZIP file name]
* xref:configure-output.adoc#multiple-destinations[Specify relative and absolute provider publishing destinations]

==== clean

The clean key can be specified directly on any `fs` provider.
When specified at this location (instead of directly under output), it only cleans the output location specified by this destination.

== Runtime keys

The `runtime` category contains keys that manage the console output, resource update behavior, and cache location.

[#cache-dir-key]
=== cache_dir

The cache dir key specifies the directory where Antora will cache any remote git repositories and UI bundles.
The key accepts a relative or absolute filesystem path.
If `cache_dir` isn't set, the repositories and UI bundle are saved to the [.path]_antora_ folder under the operating system cache directory for the current user.

Learn more:

* xref:configure-runtime.adoc#default-cache[Locate default cache directory]
* xref:configure-runtime.adoc#cache-dir[Override default cache location]

[#pull-key]
=== pull

If you want Antora to refresh the files in the cache, you need to set the `pull` key under the `runtime` category to true.

Learn more:

* xref:configure-runtime.adoc#pull[Pull updates]

////
== antora.yml

The file system name of the repository and branch are ignored by Antora once the content is retrieved.
Instead, metadata about the component is read from a xref:ROOT:component-descriptor.adoc[component descriptor file] in the repository.
Inside each branch is a file named [.path]_antora.yml_ at the documentation component root.
The file defines the name and version of the component.

As an example, here's the [.path]_antora.yml_ file in the v5.0 branch of the server repository:

.antora.yml
[source,yaml]
----
name: server
title: Server
version: '5.0'
nav:
- modules/start/nav.adoc
- ...
----

This decoupling allows you to have more than one branch that provides the same version of a documentation component, which you can then toggle by configuring the branches key in the playbook.

urls:
urls html_extension_style: Controls how the URL extension for HTML pages is handled.

redirects: Generate nginx config file containing URL redirects for page aliases. Boolean

== Create a custom playbook

Instead of modifying the main playbook, you can create a custom playbook and pass it to Antora.

Start by creating a new file named [.path]_custom-site.yml_.
Populate it as follows:

.custom-site.yml (excerpt)
[source,yaml,subs=attributes+]
----
site:
  title: Custom Docs Site
content:
  sources:
  - url: https://github.com/my-docs/server-docs
  - url: https://gitlab.com/antora/demo/demo-component-b
    branches: v1.0
----
////
