= The Playbook
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:idprefix:
:idseparator: -

On this page, you'll learn:

* [x] The purpose of an Antora playbook.
* [x] The playbook file formats Antora accepts.
* [x] Where the playbook file is located.
//* [x] How a playbook drives an Antora pipeline.

== Why does Antora need a playbook?

A playbook is the configuration object for Antora.
It tells an Antora pipeline what content to use, how the content should be processed, how the site should be generated, and where to publish the output.
The playbook is populated using a combination of a playbook file, CLI options, and environment variables.

== Playbook formats

Playbooks can be written in YAML, JSON, and CSON.

YAML is a common configuration language for defining automated tasks.
Most of the playbook examples in this documentation use YAML since it's less verbose than JSON and CSON.

Regardless of the format, a playbook contains structured xref:playbook-schema.adoc[categories and keys] for specifying general site properties, content and UI input sources, and published output destinations and providers.

== Where is a playbook stored?

A playbook is usually located at the root of a xref:use-an-existing-playbook-project.adoc[playbook project].

//== How is a playbook created?

//== How does Antora get a playbook?
