= Use an Existing Playbook Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*This page is for people joining a documentation project that already uses Antora.*

include::{partialsdir}/playbook-project-summary.adoc[]

Before you can generate a site with Antora, you'll need to fetch the playbook project for your site.

== Fetch the playbook project

To start, open a terminal and clone the playbook project using git:

[source,subs=attributes+]
$ git clone your-playbook-repo && cd "`basename $_`"

// Good place to put in demo info

The command clones an existing playbook project and then switches to the project folder.

== What's next?

* xref:ROOT:run-antora.adoc[Run Antora] to generate the site.
* Modify the playbook to xref:playbook-schema.adoc[configure the site properties, inputs, and outputs].

////
Stay in this project folder in order to initialize the project using Yarn.

== Install Antora

Initializing a playbook project means downloading and installing Antora and its dependencies.
These tasks are managed by Yarn.
Make sure you've xref:ROOT:install-prerequisites.adoc[installed Antora's prerequisites] before running Yarn.

In your terminal, execute the following command from the root folder of the playbook project to install Antora and its dependencies:

 $ yarn

//The default command in Yarn is `install`, so running `yarn` by itself is the equivalent of running `yarn install`.
The install command uses dependency information defined in [.path]_package.json_ and [.path]_yarn.lock_ to resolve dependencies.
Yarn installs these dependencies inside the project under the [.path]_node_modules_ folder.

NOTE: If you run into problems while installing dependencies, see xref:ROOT:troubleshoot-yarn-nodegit.adoc[Troubleshoot Yarn and NodeGit].

Once you've installed Antora and its dependencies, you can xref:ROOT:run-antora.adoc[generate your site] with your playbook.

=== Refresh dependencies

You must run the `yarn` command each time the `yarn.lock` file is changed.
This refreshes the dependencies, fetching any dependencies you don't yet have installed and cleaning out old ones.
Since Yarn runs very quickly, it doesn't hurt to run it each time you run `git pull`.

=== About dependencies

A playbook project only has one top-level dependency, which is (pending release) _antora_.
You can see that this is the only dependency declared in [.path]_package.json_:

.package.json (excerpt)
[source,json,subs=attributes+]
----
"dependencies": {
  "antora": "{uri-antora-repo}#v1.0.2"
},
----

*You do not need to clone the Antora repository listed in this excerpt*.
Yarn does that for you.

Antora has its own transitive dependencies, but those are fetched automatically by Yarn.

=== Generate the Site

To generate the site using the default configuration, run the following command:

 $ node generate

You can preview the site locally by navigating to the [.path]_build/site_ in your browser.
////
