= Antora AsciiDoc Loader

The AsciiDoc loader is a reusable library for handling AsciiDoc content in Antora.
It loads AsciiDoc content into an AsciiDoc Document object (AST) for use in an Antora documentation pipeline.

The AsciiDoc loader wraps http://asciidoctor.org/docs/asciidoctor.js/[Asciidoctor.js], adding several extensions that enable AsciiDoc to work in an Antora environment.
These extensions include:

* An include processor that resolves files from the content catalog.
* A cross reference converter that resolves references between pages based on Antora's page reference system.
* Automatic resolution of paths to images and attachments.
* Inherent document attributes that reflect the Antora environment.

https://antora.org[Antora] is a modular static site generator designed for making documentation sites from AsciiDoc aggregated from versioned content repositories and processed with Asciidoctor.

== Copyright and License

Copyright (C) 2017-2018 https://opendevise.com[OpenDevise Inc.] and the https://antora.org[Antora Project].

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
