= Site Publisher Guidebook

== Context

The publishable files for the site, which includes the files Antora generates and auxiliary files, need to be published (i.e., deployed) to a location so that the site can be viewed.
This destination, which includes the location where the files should be published and the protocol over which they are transferred, may vary by circumstance.
It may even be necessary to publish the files to multiple destinations.
Therefore, the site publisher component should handle publishing the files to one or more destinations, which are specified in the playbook.
The destination provider should be an extension point so Antora can be augmented to handle new destination types.

== Functional Overview

The main purpose of this component is to publish the files for the site to a location where they can be viewed.
The site publisher component should locate all publishable files in each file catalog and publish them to one or more destinations specified in the playbook.

Most site generators write files to a local folder, then use a separate step to copy (i.e., deploy) those files to the final destination.
Since Antora maintains files in a virtual filesystem, it's possible to consolidate these steps.
For example, if the site author wants to publish the files to S3, the files should be streamed directly from the virtual filesystem to the destination S3 bucket.
Antora could also support publishing the virtual files to multiple destinations.

The site publisher component accepts a collection of file catalogs (content, UI, site, etc.).
From those catalogs, it queries for all publishable files (currently, files which have an `out` property).
It then delegates to each destination provider specified in the playbook to publish the files.

If no destinations are specified, the site publisher outputs the files to the [.path]_build/site_ folder by default.
If the `dir` property is specified directly on the `output` category of the playbook, that value either replaces the path of the first filesystem (`fs`) destination or is used to create an `fs` destination if one doesn't exist.

== Software Architecture

The site publisher component functionality is provided by the site-publisher module.

The playbook can specify one or more destination configuration entries.
Each destination configuration consists of a provider type and an open-ended configuration map.
The site publisher publishes the site's files for each destination configuration entry.
The same destination provider can be used multiple times (for example, to publish to multiple directories on the filesystem).

A destination provider is a function that accepts a stream of files, the destination configuration, and the playbook.
All the work of publishing the virtual files to a concrete location or endpoint is handled by the destination provider functions.

The site publisher should load the destination providers on demand.
Some of the providers, such as `fs` and `archive`, are built-in.
If the provider is built-in, the site publisher should load it directly from the site publisher module.
If the provider is not built-in, the site publisher should load the provider from a path relative to the playbook file, an absolute path, or the Node require path, depending on whether the value begins with a dot (`.`), a filesystem root, or neither, respectively.

Once the provider functions are loaded, the site publisher should query the file catalogs to create a stream of publishable files.
It should then iterate over each destination configuration entry and pass the files, destination configuration, and playbook to the corresponding publish function.
If the provider needs to modify the virtual file, it should work on a copy of the files so the providers can operate in parallel without interference.

.Inputs
* Playbook (`output`, `dir`)
* File catalogs (e.g., `contentCatalog`, `uiCatalog`, etc.)

.Output
* _none_ (the virtual files are written to the configured destination by the destination provider)

== Code

The site publisher is implemented as a dedicated node package (i.e., module).
The site publisher API exports the `publishSite()` function, which accepts a playbook and collection of virtual file catalogs.
The site publisher queries for publishable files in each catalog (`+catalog.getAll().filter((file) => file.out)+`) and creates a stream from this collection.
It then passes that stream and the playbook to the publish function for each destination provider configured in the playbook.
The function returns a Promise that resolves once all the destination providers have run to completion.
However, the Promise does not currently resolve any data.

The API for the site publisher component should be used as follows:

[source,js]
----
const publishSite = require('@antora/site-publisher')

//...

publishSite(playbook, catalogs)
----

The site publisher should provide two destination providers:

* _fs_ -- publishes the site files a directory on the local filesystem (specified by the `path` property)
 ** If the `clean` property is set globally or on the destination configuration, this provider should first remove the directory, if it exists.
* _archive_ -- publishes the site files to a ZIP archive on the local filesystem (specified by the `path` property).

Here's the signature of the publish function for each destination provider:

[source,js]
----
function publish (config, files, playbook) {
  ...
}
----

The publish function can return a Promise, which will get resolved together along with the result of all the other publish functions.

== Data

The main data for the site publisher is the list of destination configuration entries read from the playbook.
Each entry describes a destination where the files should be published.
It consists of the provider that handles publishing and the configuration needed by that provider to get the files to the destination.

Here's an example that shows how destinations are specified:

[source,yml]
----
output:
  destinations:
  - provider: fs
    path: _site
  - provider: site-publisher-ssh
    host: hostname
    user: username
    agent: true
    path: /var/www/html
----

The site publisher passes all publishable files to the destination providers as a stream.
It identifies publishable files by the presence of the `out` property on the file.
(This assumption may change in the future).

== Consequences

This component carries out the primary result of the site generator, which is to publish the files for the site.
It does so by taking the publishable files in the virtual file catalogs and turning them into concrete files.
It can publish to zero or more local or remote destinations, depending on the destinations specified in the playbook.
How the files are published is determined by the provider and the destination configuration specified in the playbook.

Once this component runs, the generation pipeline is complete.
