= Content Classifier Guidebook

== Context

Throughout Antora's documentation pipeline, components frequently need to retrieve files by group or look up a file at a specific path.
Therefore, these files need to be well organized in order for the components to process them efficiently.
This component provides that function.
The collection of files this component creates, which we call a [.term]_content catalog_, is the primary interface components will use to access the virtual files and their metadata, which includes source and destination paths.
The catalog should be structured for optimal querying.

== Functional Overview

The content classifier component is responsible for populating each file with metadata pertaining to where it's published, organizing the files for efficient processing, and putting the files into a content catalog.
It effectively transforms the content aggregate into a content catalog.

The content classifier requires the playbook and the content aggregate as input.
Using those inputs, it should carry out the following operations:

* Further partition the content aggregate into modules and families
 ** Build on the work the content aggregator did to organize the files by component version
* Reject files which are not in a recognized location
* Add additional metadata to the virtual files concerning information about their module, family, family-relative path, etc.
* Compute the output path (disk) and publish path (URL) information for each publishable file
//* Add a navigation index to the navigation files
* Create a look up mechanism to find files matching certain criteria
* Build a structured catalog of virtual files that can be queried and transmitted

== Software Architecture

The content classifier component functionality is provided by the content-classifier module.

The details of calculating file paths, assigning calculated metadata to files, sorting files by family for processing, and adding each file to a structured and transmittable content catalog should be encapsulated in this component.

The content classifier should:

* Access the content aggregate, which is produced by the content aggregator component
* Walk the files in each component version
 ** The file walker should be aware of the following divisions: module and family
* Only keep files that match a known family and family file format
* Discard files that do not match allowed project or file structures
* Calculate source, output, and published path information for each file
 ** Assign source metadata to each file (`src` property)
 ** Assign output metadata to each file (`out` property)
 ** Assign published metadata to each file (`pub` property)
  *** Apply the URL extension style to published files (drop or indexify)
* Keep track of navigation order for each navigation file (`nav` property)
* Add each file to the content catalog
 ** The content catalog is an index of virtual file entries keyed by page ID

.Inputs
* Content aggregate (`aggregate`)
* Playbook (`site.startPage` and `urls.htmlExtensionStyle`)

.Output
* Content catalog (`ContentCatalog`)

== Code

The content classifier is implemented as a dedicated node package (i.e., module).
Its API exports the `classifyContent()` function, which accepts a playbook instance and the content aggregate data structure.

The API for the content classifier should be used as follows:

[source,js]
----
const classifyContent = require('@antora/content-classifier')

//...

const catalog = classifyContent(playbook, aggregate)
----

The files in the catalog can be queried as follows:

[source,js]
----
const pages = catalog.getPages()
----

.Content catalog API
* `getAll()` - gets all files in the catalog; replaces deprecated `getFiles()` method
* `addFile()` - add a file to the catalog; stored by ID (see `getById`)
* `getById({ component, version, module, family, relative })`
* `getByPath({ component, version, path })`
* `findBy({...})` - finds files that match example; at least one property must be specified
 ** filterable properties: `component`, `version`, `module`, `family`, `relative`, `basename`, `extname`
* `getPages()` - equivalent to `findBy({ family: 'page' })`

== Data

The classifier assumes that each documentation component adheres to the following filesystem structure:

....
antora.yml
modules/
  ROOT/
    assets/
      attachments/
      images/
    pages/
      index.adoc
      ...
      _partials/
    examples/
  module-a/
    assets/
    pages/
      index.adoc
      ...
    examples/
  module-b/
    assets/
    pages/
      index.adoc
      ...
    examples/
....

There must be one or more modules.
Files in the ROOT module are promoted a level above the named modules when published (effectively belonging to the component version itself).
AsciiDoc files are assumed to have the file extension `.adoc`.
Files and folders which begin with an underscore are not published.

The content catalog object (instance of `ContentCatalog`) produced by this component should provide a queryable index of virtual files.

Each virtual file in the content catalog is a Vinyl file, which already has a built-in set of https://github.com/gulpjs/vinyl#instance-properties[instance properties] to start.
The content aggregator already set some additional properties on the file object, such as `src.origin`.
The classifier should complete this work by fully populating the `src`, `out`, and `pub` properties.

Each virtual file object should include the following Antora-specific properties:

.src property
* `path` - component root-relative path (no leading forward slash); matches initial value of `path`
* `component`
* `version`
* `module`
* `family` (attachment, example, partial, image, navigation, or page)
* `relative` - family root-relative path (no leading forward slash)
// moduleRootPath may no longer be needed on src
* `moduleRootPath`
* `basename`
* `stem`
* `extname`
* `mediaType`
* `origin`

.out property
// dirname may not be needed on out
* `dirname`
* `basename`
* `path`
* `moduleRootPath`
* `rootPath`

.pub property
* `url`
//* `absoluteUrl` - the `site.url` property from the playbook + the `url`
* `moduleRootPath`
* `rootPath`

== Consequences

The content classifier component is responsible for the fine-grained organization of the virtual files.
The classifier organizes the files and allows subsequent components to request a specific file by its page ID, its path, or other grouping, such as family or component and version.

* All destination information for each file has been determined and assigned.
* Files can be queried by component version and/or family so they can be processed in parallel.
* No subsequent components should have to organize the files for processing.
* The content catalog is transmittable.
* Pages can now be found and processed.

The next component in Antora's documentation pipeline is the page generator.
The page generator requires the catalog as an input and operates on the files in the `pages` family.
