= Admonitions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
// External URIs
:uri-adoc-manual: http://asciidoctor.org/docs/user-manual
:uri-admonition: {uri-adoc-manual}/#admonition

On this page, you'll learn:

* [x] How to mark up an admonition with AsciiDoc.
* [x] How to create an admonition with complex content.

== Admonition styles

An admonition, also known as a notice, helps draw attention to a line or block of text with a special label or icon.

Asciidoctor comes with five built-in styles.

* NOTE
* TIP
* IMPORTANT
* CAUTION
* WARNING

== Basic admonition

.Basic admonitions
[source,asciidoc]
----
CAUTION: Don't stick forks in electric sockets.

TIP: After someone sticks a fork in a socket, you'll need to reset the circuit in the breaker box in the dark and scary basement.

WARNING: Never go into the basement.

IMPORTANT: A monster lives in the basement.

NOTE: If you go into the basement, see if you can find Kenny's orange parka.
----

CAUTION: Don't stick forks in electric sockets.

TIP: After someone sticks a fork in a socket, you'll need to reset the circuit in the breaker box in the dark and scary basement.

WARNING: Never go into the basement.

IMPORTANT: A monster lives in the basement.

NOTE: If you go into the basement, see if you can find Kenny's orange parka.

== Complex admonition

.Example block masquerading as an admonition
[source,asciidoc]
----
[IMPORTANT]
.Optional Title
====
Use an example block to create an admonition that contains complex content, such as (but not limited to):

* Lists
* Multiple paragraphs
* Source code
* Images
====
----

[IMPORTANT]
.Optional Title
====
Use an example block to create an admonition that contains complex content, such as (but not limited to):

* Lists
* Multiple paragraphs
* Source code
* Images
====

Asciidoctor resources:

* {uri-admonition}[Admonition paragraphs and blocks]
