= Bold
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:example-caption!:
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-bold: {url-adoc-manual}/#bold-and-italic

On this page, you'll learn:

* [x] How to make text bold in AsciiDoc.
* [x] Where to modify your site's bold text styling.

Text that is marked up as bold will stand out against the regular, surrounding text due to the application of a thicker and/or darker font.
Bold is useful when the text needs to catch the attention of a site visitor quickly scanning a page.

== Bold syntax

A word or phrase is marked as bold when it's enclosed in a single set of asterisks (e.g., `+*word*+`) (constrained formatting).
Bounded characters are marked as bold when they're enclosed in a set of double asterisks (e.g., `+char**act**ers+`) (unconstrained formatting).

Bounded characters are characters that are:

* directly preceded by a non-whitespace character, or
* directly followed by a non-whitespace character.

.Bold inline formatting
[source,asciidoc]
----
A bold *word*, and a bold *phrase of text*.

Bold c**hara**cter**s** within a word.
----

You don't need to use double asterisks when an entire word or phrase marked as bold is directly followed by a common punctuation mark, such as `;`, `"`, and `!`.

.Results
====
A bold *word*, and a bold *phrase of text*.

Bold c**hara**cter**s** within a word.
====

== Mixing bold with other formatting

You can add multiple emphasis styles to bold text as long as the syntax is placed in the correct order.

.Order of inline formatting syntax
[source,asciidoc]
----
`*_monospace bold italic phrase_*` & ``**__char__**``acter``**__s__**``
----

xref:monospace.adoc[Monospace syntax] (`++`++`) must be the outermost formatting set (i.e., outside the bold formatting set).
xref:italic.adoc[Italic syntax] (`+_+`) is always the innermost formatting set.

.Result
====
`*_monospace bold italic phrase_*` & ``**__char__**``acter``**__s__**``
====

== Site styles

How bold text appears on your site depends on the fonts loaded by your UI and any CSS styles applied to the `<strong>` HTML tag.
You can learn more about customizing xref:antora-ui-default::inline-text-styles.adoc#bold[how bold text appears in your site] in the UI documentation.

[discrete]
=== Asciidoctor resources

* {url-bold}[Bold text formatting^]
