= Include a Page
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-tags: {url-adoc-manual}/#by-tagged-regions
:url-leveloffset: {url-adoc-manual}/#include-partitioning

You can insert one page, or a portion of that page, into another page using the include directive.

== Include directive

You can include a page (or a portion of that page) into another page using either a relative path (a path relative to the current file) or the familiar resource ID syntax in the target of the include directive.

----
\include::./relative-path.adoc[<attrlist>]
----

or

----
\include::version@component:module:page$relative-path.adoc[<attrlist>]
----

Let's explore this syntax.

. On a new line, enter the name of the directive followed by two colons.
+
[subs=+quotes]
----
**include::**version@component:module:page$relative-path.adoc[]
----

. Next, enter the relative path (starting with `./`) or the xref:page:page-id.adoc[resource ID] of the target file.
+
--
A relative path must begin with `./`.

[subs=+quotes]
----
\include::**./relative-path.adoc**[]
----

A page's resource ID is determined just like the xref:page-to-page-xref.adoc#same-module[coordinates in an xref].
However, when used in an include directive, the resource ID must contain the `page$` family (since it supports multiple families).
All other segments (component, version, and module) are optional and will inherit the context from the current file.

[subs=+quotes]
----
\include::**version@component:module:page$relative-path.adoc**[]
----
--

. Close the directive with a set of square brackets (`[]`).
The brackets may contain an optional list of attributes (i.e., attrlist) such as `leveloffset`, `tag`, and `tags`.
The attributes should be entered as key=value pairs separated by commas.
+
[subs=+quotes]
----
include::version@component:module:page$relative-path.adoc**[tag=definition]**
----

Currently, Antora only supports filtering lines of an include by tags, not by lines.

== The page-partial attribute

As Antora processes each page, it converts the contents of the file from AsciiDoc to HTML.
(Within a component version, pages are typically processed in order according to the module and relative filename).
The conversion of the contents from AsciiDoc to HTML would normally impact the behavior of the include directive.
Specifically, a page that uses the include directive to include a page that has already been processed would see HTML instead of AsciiDoc.

To rectify this ordering problem, Antora can retain the AsciiDoc source until all pages have been converted.
This behavior is activated by setting the `page-partial` attribute in the document header of the page.
As of Antora 2.2, the `page-partial` attribute is (soft) set globally by default.
(Soft set means the it can still be overridden by the page).
So, really, you don't even have to think of it.
It will just work.

The downside of retaining the AsciiDoc source is that it _may_ increase the peak heap usage of Antora for very large sites by ~ 10%.
If that's a concern, you can revert to the previous behavior.
To revert to the previous behavior (prior to Antora 2.2), set the following property in the playbook file:

[source,yaml]
----
asciidoc:
  attributes:
    page-partial: false
----

Now the `page-partial` attribute will not be set globally.
But you can still set it per page.
In fact, you *must* now set set the `page-partial` atttribute on any page that you want to use in an include directive.
For example:

[source,asciidoc]
----
= Shared Page
:page-partial:

Page contents.
----

Now you can safely refer to that page using the include directive:

[source,asciidoc]
----
\include:shared-page.adoc[]
----

The `page-partial` attribute in the included page instructs Antora to retain the AsciiDoc source until all pages have been converted.

== Learn more

* xref:include-partial.adoc[Include a partial]
* xref:include-example.adoc[Include an example]
* xref:page:page-id.adoc[Page IDs]
* xref:page:resource-id.adoc[Resource IDs]

== Asciidoctor resources

* {url-tags}[Select regions of content with tags^]
* {url-leveloffset}[Offset section headings with leveloffset^]
