= Page Header
:note-caption: OPS HINT
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-author: {url-adoc-manual}/#author-and-email
:url-attrs: {url-adoc-manual}/#attributes
:url-builtin-attrs: {url-adoc-manual}/#builtin-attributes
:url-netlify-redirects: https://www.netlify.com/docs/redirects/
:url-meta-tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
:url-nginx-rewrite-return-directive: https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return

On this page, you'll learn:

* [x] How to structure a valid AsciiDoc page header.
* [x] How to set a page title.
* [x] How to add metadata to a page.
* [x] How to configure redirects to one or more pages.
* [x] How to set AsciiDoc's built-in page attributes.

== Header anatomy

The page header is a set of contiguous lines that start on the first line of the file.
The header is separated from the page body by at least one blank line.

.Common elements in a page header
[source,asciidoc]
----
= Page Title // <1>
First Middle Last <author@email.com> // <2>
:description: A description of the page stored in an HTML meta tag. // <3>
:keywords: comma-separated values, stored, in an HTML, meta, tag // <4>
:page-role: tiles // <5>
:sectanchors: // <6>
:url-repo: https://my-git-repo.com // <7>
----
<1> Title of the page
<2> Author name and email address
<3> Description attribute
<4> Keywords attribute
<5> A user-defined `page` attribute
<6> A built-in AsciiDoc attribute
<7> A user-defined attribute

Each attribute entry must be entered on its own line.
The header can also contain xref:comments.adoc[comments].

[#page-title]
== Page title

A page title is specified by one equals sign (`=`), followed by one blank space, and then the text of the title.

.Page title syntax
[source,asciidoc]
----
= The title of this page
----

[#page-meta]
== Page metadata

AsciiDoc provides several built-in attributes for defining page metadata.

=== Author syntax

Specifying the author or authors of a page is optional.
The author is listed on the line directly beneath the page’s title.
An optional email address or contact URL can follow an author’s name inside a set of angle brackets (`< >`).
When a page has multiple authors, each author is separated by a semicolon (`;`).

.Multiple authors and author information syntax
[source,asciidoc]
----
= Page Title
First Middle Last <author@email.com>; First Last <author@email.com>
----

Author names are output to the HTML `<meta>` tag.

.Author HTML output
[source,html]
....
<head>
<meta charset="UTF-8">
<meta name="author" content="First Middle Last, First Last">
....

Whether any author information is also displayed on a published page depends on the site's UI templates.

[discrete]
==== Asciidoctor resources

Refer to the Asciidoctor user manual for additional author attributes and methods for specifying author information.

* {url-author}[Author attributes and usage examples^]

=== Description syntax

If set, `description` is output to an HTML `<meta>` tag with the same name.
You can break long values across several lines by ending each line with a backslash `\` that is preceded by a space.

.Description attribute syntax
[source,asciidoc]
----
= Page Title
:description: A description of the page stored in an HTML meta tag. This page is \
about all kinds of interesting things.
----

.Description HTML output
[source,html]
....
<head>
<meta charset="UTF-8">
<meta name="description" content="A description of the page stored in an HTML meta tag. This page is about all kinds of interesting things.">
....

=== Keywords syntax

The keywords attribute contains a list of comma-separated values that are assigned to an HTML `<meta>` tag with the same name.

.Keywords attribute syntax
[source,asciidoc]
----
= Page Title
:keywords: comma-separated values, stored, in an HTML, meta, tag
----

.Keywords HTML output
[source,html]
....
<head>
<meta charset="UTF-8">
<meta name="keywords" content="comma-separated values, stored, in an HTML, meta, tag">
....

== Configuring page redirects

To configure page redirects, you use the `page-alias` attribute.
This attribute contains a comma-separated list of pages that redirect to the current page.

For example, if `upgrade/service/apache.adoc` was renamed to `upgrade/server/apache.adoc`, then at the top of `upgrade/server/apache.adoc`, add a `page-alias` attribute that references the renamed page:

[source,asciidoc]
....
= Page Title
:page-aliases: upgrade/service/apache.adoc
....

NOTE: The redirected pages must follow xref:page:page-id.adoc[Antora’s Page Identifier rules].

To allow Antora to follow redirects, you need to generate them.
To do this, assuming one or more page-alias attributes have been added, use Antora's xref:cli:index.adoc#_commands_and_options[`--redirect-facility` option], and specify one of the four redirect types (`disabled`, `netlify`, `nginx`, or `static`).

For example, to generate a redirect configuration suitable for use with the NGINX webserver, then you would use the, simplified, command:

[source,console]
....
antora --redirect-facility nginx playbook.yml
....

Redirects work differently, depending on the value provided.
Below are the examples of generated configurations for each of the four parameters:

=== nginx

Antora generates an {url-nginx-rewrite-return-directive}[NGINX rewrite configuration] in a file called `rewrite.conf`, in a new directory called  `.etc/nginx`, itself created inside the Playbook's output directory.

.Generated configuration for Nginx
[source,nginx]
....
location = /upgrade/service/apache.html {
  return 301 /upgrade/server/apache.html;
}
....

=== netlify

Antora generates {url-netlify-redirects}[a Netlify _redirects file] (called `_redirects`) in the Playbook's output directory, containing the generated rewrite configuration.

.Generated configuration for Netlify
[source]
....
/upgrade/service/apache.html /upgrade/server/apache.html 301
....

=== static

Antora generates static bounce pages for each page that is to redirected _from_.
These pages contain:

. A link to the new, canonical reference.
. A {url-meta-tag}[meta refresh tag] to redirect to the new canonical reference
. A notice, letting the reader know that the old page no longer exists along with the location of the new page.

.Generated static configuration for ./service/apache.html
[source,html]
....
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="http://localhost:5000/upgrade/server/apache.html">
<script>location="marketplace_apps.html"</script>
<meta http-equiv="refresh" content="0; url=../server/apache.html">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>
  The page you requested has been relocated to
  <a href="../server/.html">http://localhost:5000/server/apache.html</a>.
</p>
....

[#page-attrs]
== Built-in attributes

Antora and AsciiDoc provide built-in attributes that activate and control syntax output behavior and styles.
See xref:page:page-and-site-attributes.adoc[Page and Site Attributes] to learn about the built-in Antora attributes.

TIP: If you're not familiar with AsciiDoc attribute restrictions or operations precedence, review the {url-attrs}[attributes section of the Asciidoctor manual^].

Built-in AsciiDoc attributes are reserved attributes that have special, pre-defined behavior.
Many built-in attributes also have a restricted set of accepted values.

These attributes usually do two things; they toggle a behavior on or off (boolean), and they change the generated output by accepting an alternate value or replacement content (variable).

[#set-attribute]
=== Set and unset built-in attributes

Let's turn on the attribute `sectanchors`.

.Set a built-in attribute
[source,asciidoc]
----
= Page Title
:sectanchors:
----

When turned _on_, `sectanchors` adds an anchor to the left of each xref:section-headings.adoc[section title].
The anchor is rendered as the symbol `§`.
The attribute is turned on, also known as _set_, by simply entering it into the header.

Built-in attributes that are on by default, like `table-captions`, can be _unset_ (turned _off_) with a leading or trailing `!` added to its name.

.Unset a built-in attribute
[source,asciidoc]
----
= Page Title
:sectanchors:
:table-caption!:
----

=== Change a built-in attribute value

Let's look at an example of a built-in attribute that has a default value that we want to replace with a custom value.

The label on a xref:admonitions.adoc[Note admonition] is controlled by the attribute `note-caption`.
This attribute is set (on) by default and has an implicit value of `NOTE`.
Let's change the value to "`OPS HINT`".

.Change a built-in page attribute value
[source,asciidoc]
----
= Page Title
:note-caption: OPS HINT
----

Now, when we create a Note admonition, its label is displayed as OPS HINT.

NOTE: This is an Ops Hint.

[discrete]
==== Asciidoctor resources

* {url-builtin-attrs}[Built-in page attributes^]
* {url-attrs}[AsciiDoc attribute restrictions or operations precedence^]
