= Page Cross References
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:colon: :

To link between documentation pages, you'll use the the AsciiDoc cross reference macro and a page ID.
This syntax in also used to xref:navigation:link-syntax-and-content.adoc[reference pages from your navigation files].

== Reference by page ID

In Antora, a cross reference, commonly abbreviated xref, needs a xref:page:page-id.adoc[page ID] in order to link to another page in the site.
The number of page ID coordinates you need to specify in the xref depends on the location of the current page in relation to the location of the destination page (i.e., the page you want to link to).
The closer the two files are, the shorter the page ID.

In the next section, we'll go over each part of the xref and page ID syntax.

NOTE: The page ID is integral to Antora's ability to publish a site to multiple environments and domains without you needing to modify your source content.
If you want to learn more about the page ID, see xref:page:page-id.adoc#important[Why are page IDs important?]

== Xref and page ID anatomy

Let's dissect a cross reference with a fully-qualified page ID.

image::xref-macro-anatomy-diagram.svg[Page reference anatomy,role=grow-x]

Here's what each part of the cross reference and page ID does:

xref{colon}::
The prefix of the AsciiDoc cross reference (xref) macro, which we're using here to make a page reference.

[#page-id-vname-def]
version@::
The first page ID coordinate is used to specify the version name of the destination component.
This value is defined in the xref:ROOT:component-descriptor.adoc#version-key[component descriptor file] ([.path]_antora.yml_) in the branch of the component repository that hosts the destination file.
When the version coordinate is filled, it must be directly followed by an at sign (`@`).

[#page-id-cname-def]
component-name{colon}::
The second coordinate specifies the name of the destination component.
The component name is directly followed by one colon (`:`).
This value is defined in the xref:ROOT:component-descriptor.adoc#name-key[name key] of the component descriptor in the branch of the component repository that hosts the destination file.
If a component name is present, a module name must be specified after the `:`.
Otherwise, this coordinate gets interpreted as the module name.

module-name{colon}::
The third coordinate specifies the name of the destination module.
The module name is directly followed by one colon (`:`).
If a component name is present, and the name of the module is ROOT, the module name position can be left empty in some cases.
That's why you see a component name followed by two colons (`::`) sometimes.

page.adoc::
The fourth coordinate specifies the local path of the destination file relative to the module's documents directory.
This value may include one or more optional topic folders.
The destination file name must have the _.adoc_ file extension.

#fragment::
An optional ID of a section or anchor point to link to in the destination page (i.e., deep link).
This part is always optional.

[link text]::
The text of the link that is displayed to the reader.
This text must be entered inside a set of square brackets (`[]`) at the end of the macro.
If the text is not specified, the raw target is used.

////
[link text,aspect=name-of-aspect] ::
To link to the aspect variant of a page, add the aspect attribute after the link text.
A comma (`,`) should directly follow the link text, and the aspect attribute should directly follow the comma, i.e., don't add a blank space after the comma.
To learn more about referencing aspect pages, go to the xref:apect-page-link.adoc[referencing an aspect page].
////

[#same-module]
== Scenario: In the same component and module

When the current page and the destination page are in the same module, you only need to enter the name of the destination file.

.Link to a page in the same module
[source,asciidoc]
xref:error-handling.adoc[Error Handling]

.Link to a page in a topic folder
[source,asciidoc]
xref:concept/index.adoc[Key Concepts]

.Link to a page in the same module but in a different version
[source,asciidoc]
xref:3.3@error-handling.adoc#message-list[error messages]

[#different-module]
== Scenario: In the same component but a different module

When the current page and the destination page are in the same component but different modules, you'll enter the name of the destination module and destination file.

.Link to a page in another module
[source,asciidoc]
xref:get-started:implement-api.adoc[implement an API]

.Link to a page in the ROOT module and in a topic folder
[source,asciidoc]
xref:ROOT:transports/c04-reference.adoc[C04 Transports]

.Link to a page in the ROOT module and in a different version
[source,asciidoc]
The xref:3.4@ROOT:scopes/super-mass.adoc[super massive scope] splits atoms.

[#different-component]
== Scenario: In a different component

When the current page and the destination page are in different components, you'll enter values for all of the coordinates.
If a version is not specified, the implicit value is `master@`.

.Link to a page in the ROOT module of a versioned component
[source,asciidoc]
How do I xref:2.0@default-ui::modify-template.adoc[modify a UI template]?

.Link to a page in the ROOT module of a component that doesn't have versions
[source,asciidoc]
xref:icons::index.adoc#intro[Introducing the Icon Project]

.Link to a page in a module of a component that doesn't have versions
[source,asciidoc]
xref:icons:web:modify-svg.adoc[Get started with the SVG assets]
