= Text Emphasis, Punctuation, and Typography
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: oblique, boldface, typeface

== Visual Emphasis

AsciiDoc provides multiple ways to visually emphasize inline text.

xref:bold.adoc[Bold]::
Text that is bold will stand out against the regular, surrounding text due to the application of a thicker and/or darker font.
Bold is useful when the text needs to catch the attention of a person visually scanning a page.

xref:italics.adoc[Italics]::
Text is often italicized in order to stress a word or phrase, quote a speaker, or introduce a term.
Italic type slants slightly to the right, and depending on the font, may have cursive swashes and flourishes.

xref:monospace.adoc[Monospace]::
Technical content often requires text to be styled in a way that indicates it is a command or source code.
Such text is usually emphasized using a fixed-width, i.e., monospace, font.

xref:highlight.adoc[Highlight]::
Another way to make visual scanning easier for website visitors is to highlight text that states key points.

== Punctuation

Common punctuation is typed in an AsciiDoc document just as you would in an email or word process.
Less common punctuation can be entered using your operating system's keybinding sequence for that mark.
For example, on macOS you can enter an en dash by pressing kbd:[⌥ Opt+-].

When you want extra control to ensure that you get exactly the mark you want on your published site, AsciiDoc also provides mark up for curved (smart) quotes and built-in attributes for punctuation that can be misinterpreted when converted to HTML.

xref:quotes-and-apostrophes.adoc[Quotation and apostrophe marks]::
Quotation marks and apostrophes can be explicitly marked as straight or curved.

// Break up special character and symbols table into punctuation, intellectual property, etc.
// Add category for equations, formulas, sub/superscript

== Symbols, Signs, and Marks

Special character and symbol replacement is built right into AsciiDoc.

xref:special-characters-and-symbols.adoc[Special characters and symbols]::
AsciiDoc accepts HTML and XML character entities as well as decimal and hexadecimal Unicode code point references.

// Subscript and Superscript
