= ADR 0006: Package Organization
:revdate: 2017-12-06

== Status

Accepted

== Context

The goal with Antora is to create an open architecture that allows core components to be reused to create a custom processing pipeline or to simply alter the default one.
That means each step in the pipeline should be designed a discrete function that's provided by a dedicated package (i.e., node module).
But this raises the question, should these core packages each have their own repository (i.e., a dedicated repository for each software component) or should they be organized together under the main repository (i.e., host all core components in a single repository)?
And if they are kept together, how can they be released as separate packages?

To quote the Lerna project:

> Splitting up large codebases into separate independently versioned packages is extremely useful for code sharing.
> However, making changes across many repositories is messy and difficult to track, and testing across repositories gets complicated really fast.

Especially during the early stages of development, we want to simplify development as much as possible.
Using separate repositories means having to set up separate builds, separate test suites, separate release tasks, and separate issue trackers, not to mention having to release packages sooner than planned.

One solution to these problem is to organize the code into a multi-package repository, or monorepo.
There are tools available, such as Lerna, to manage a JavaScript project repository that hosts multiple packages.
The decision to be made is whether to adopt the monorepo structure or use the traditional multi-repository structure.

== Decision

The decision is to organize the packages in the default pipeline as a monorepo (antora/antora), at least in the beginning.
This decision was made because:

a. it will simplify development
b. there are good tools available for organizing packages in this way

Specifically, we've decided to use a combination of Lerna and Yarn workspaces to manage the packages.

https://lernajs.io[Lerna] optimizes the workflow around managing multi-package repositories with git and npm or Yarn.
https://yarnpkg.com/lang/en/docs/workspaces/[Yarn workspaces], a built-in feature of Yarn, provides support for multi-package repositories.
When enabled for a project, Yarn workspaces allow Yarn to automatically recognizes the structure required by Lerna, thus allowing the user to continue to use Yarn in the normal way (e.g., `yarn install`).

With the slight change required by Lerna, it's possible to release the packages as separate node modules, but still use a shared build to run tasks such as lint, test, and format.

== Consequences

By organizing the Antora codebase as a multi-package project, we can simplify development in the early stages of the project.
We only need to maintain a single build, test suite, and issue tracker.
Yet, the packages remain independent.
Each package keeps track its own runtime dependencies, which can be installed using either Lerna or Yarn.
Using Lerna, each package can be released as a separate node module under a common version.

If and when we decide to graduate some or all of the packages, it shouldn't be difficult to extract the packages from the main repository and import them into repositories of their own.
The only thing we'd have to do is add the lint and test dependencies and add a dedicated build.
Graduating a package would in no way affect the package consumer since the package would continue to be published as a dedicated node module.
