= ADR 0007: Package Naming
:revdate: 2017-12-07

== Status

Pending

== Context

We want the Antora package names to be structured consistently so that their purpose is easy to identify.
Also, since the packages will be published to the main npm repository (npmjs.com), the names must be globally unique.

In order to meet these requirements, we need to decide what prefixing strategy to use for package names.
One option is to apply the hyphenated prefix `antora-` to the package names (e.g., `antora-content-aggregator`).
The other option is to create an organization for Antora on npmjs.com and organize the packages under the organization namespace `@antora` (e.g., `@antora/content-aggregator`).

== Decision

Although still gaining traction, organizing packages under an organization namespace seems to be emerging as a best practice.
It's used by major projects such as Babel, Phenomic, and Commitlint, and more are switching daily.
Therefore, we decided to create an organization for Antora on npmjs.com named `antora` and to organize the packages under the organization namespace, `@antora` (e.g., `@antora/content-aggregator`).

== Consequences

By using an organization namespace instead of a hyphenated prefix, it's more clear which packages are part of the Antora project.
It also allows us to restrict which packages use this namespace, so a distinction can be made between official packages and third-party packages.
Users can also navigate to the Antora organization on npmjs.com to see a list of all the official packages.
