= ADR 0007: Package Naming
:revdate: 2017-12-06

== Status

Pending

== Context

We want packages to be named consistently.
Since the packages will be published to the main npm repository (npmjs.com), the names must also be globally unique.

We need to decide what prefixing strategy to use for package names to meet these requirements.
One option is to apply the hyphenated prefix `antora-` to the package names (e.g., `antora-content-aggregator`).
The other option is to create an organization for Antora on npmjs.com and organize the packages under the organization namespace `@antora` (e.g., `@antora/content-aggregator`).

== Decision

Although still gaining traction, organizing packages under an organization namespace seems to be emerging as a best practice.
It's used by major projects such as Babel, Phenomic, and Commitlint, and more are switching daily.
Therefore, we've decided to create an organization for Antora on npmjs.com named `antora` and to organize the packages under the organizationn namespace, `@antora` (e.g., `@antora/content-aggregator`).

== Consequences

By using an organization namespace instead of a hyphenated prefix, it's more clear which packages are part of the Antora project.
It also allows us to restrict which packages use this namespace, so a distinction can be made between official packages and third-party packages.
Users can also navigate to the Antora organization on npmjs.com to see a list of all the official packages.
