= Linux Installation Requirements
:platform: Linux
:page-partial:
//tag::shared[]
:url-node-releases: https://nodejs.org/en/about/releases/
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation

On this page, you'll learn:

* [x] What tools you need in order to install Antora on {platform}.
* [x] How to install Node.

If you've never installed Antora before, you'll need to complete the steps on this page before you can install Antora and use it to generate a documentation site.

Antora is built on Node.js (herein "`Node`").
To install Antora, all you need on your machine is a long term support (LTS) release of Node.
Although Antora performs git operations, you don't need a git client installed to use Antora.
However, you'll likely need a git client to clone and modify files in repositories you plan to use with Antora.

== Node

//tag::node-intro[]
You need Node installed on your machine to install and run Antora.
Antora follows {url-node-releases}[Node's release schedule], so we advise that you choose an active long term support (LTS) release of Node.
The active LTS releases of Node are Node 8 and Node 10.
We recommend using Node 10.
While you can use other versions of Node, Antora is only tested against LTS releases.
//end::node-intro[]

To check whether you have Node installed, and which version, open a terminal and type:

 $ node --version

You should see a version string, such as:

....
v10.14.2
....

If you don't, and *the command fails with an error*, it means you don't yet have Node installed.
The best way to install Node is to use nvm (Node Version Manager).
Skip to <<install-nvm>> to find instructions.

ifeval::["{platform}" == "Linux"]
NOTE: If your package manager provides Node and npm packages, _and you're familiar with using the tools installed system-wide_, you may choose to go that route.
However, we believe you'll be more successful if you choose <<install-nvm,nvm>>.
endif::[]

If *the command returns a version string less than 8*, upgrade to the latest Node LTS version <<upgrade-node,using nvm>> (or your preferred package manager).

If *the command returns an active Node LTS version*, makes sure that version is the default by typing the following command in your terminal:

 $ nvm alias default 10

Now you're all set to xref:install/install-antora.adoc[install Antora].

[#install-nvm]
== Install nvm and Node

We recommend using the {url-nvm}[Node Version Manager (nvm)^] to manage your Node installations, especially if your package manager doesn't provide Node and npm.
Follow these {url-nvm-install}[installation instructions^] to set up nvm on your machine.
Then, return here.

TIP: Many CI environments use nvm to manage the version of Node used in the build job.
By using nvm, you can align your setup with the environment used to generate and publish your production site.

Once you've installed nvm, open a new terminal and install the latest Node LTS release (i.e., Node 10).

 $ nvm install --lts

The above command will both install the latest LTS release of Node and automatically set it as your default alias.

Type the following command to switch to it:

 $ nvm use

Now that you have Node set up, you can xref:install/install-antora.adoc[install Antora].

[#upgrade-node]
== Upgrade Node using nvm

If you have nvm installed, but you don't have an LTS release installed, type the following command in your terminal:

 $ nvm install --lts

The above command will install the latest version of the latest Node LTS release (i.e., Node 10).

To set the latest version of Node as the default for any new terminal, type:

 $ nvm alias default 10

Type the following command to switch to it:

 $ nvm use

Now that you're on the right version of Node, you can xref:install/install-antora.adoc[install Antora].

== What's next?

Once you've installed Node, you're ready to xref:install/install-antora.adoc[install Antora].
//end::shared[]
