= Antora Release Schedule
:page-aliases: version-and-lifecycle-policies.adoc
:table-caption!:

Each major release line of the Antora Core components is typically supported for one year after it enters general availability (GA).

[cols=6*]
|===
|Release Line |Latest Release |Status |GA |Maintenance |EOL

|Antora 3.x
|NA
|Pending
|~ 2020/01
|TBD
|TBD

|Antora 2.x
|2.2.0
|Active
|2018/12/25
|~ 2020/01/25
|~ 2020/04/25

|===

General Availability (GA):: A release line, such as Antora 2.x, enters general availability on the date the initial, final major version (e.g., Antora 2.0.0) of the software is released and available for download.

Active:: Release line is being actively improved and supported.

Maintenance:: Once a release line enters its maintenance period, only its most recent minor version will receive critical security patch releases.
A release line starts this phase 30 days after the next major release line goes GA.

End of Life (EOL):: The date after which the release line no longer receives support or releases.

== Version policy

Antora follows the semantic versioning rules.
Each Antora component release is versioned *major.minor.patch*.

Major::
Major releases occur when there are substantial changes in functionality or when new functionality breaks backwards compatibility.
Releases within the same major release line will maintain API compatibility.

Minor::
Minor releases add new features, improvements to existing features, and fixes that maintain backwards compatibility.

Patch::
Patch releases fix bugs and maintain backwards compatibility.
Only the latest minor release of a major release line will receive patches.
Patch releases happen as needed depending on the urgency of the fix.

Pre-release::
Major and minor releases may include pre-release versions (major.minor.patch-alpha.n | -beta.n | -rc.n).
Pre-release versions will be tagged as _next_ so that the npm client doesn't prefer a pre-release over a stable version.
Once a release candidate (rc) has been thoroughly tested, the stable release will be published.

[#roadmap]
== Roadmap

Refer to https://gitlab.com/antora/antora/-/milestones[Antora's milestones] and https://gitlab.com/antora/antora/issues[issue tracker] for a list of the currently scheduled development tasks.
The milestones are intended for informational purposes only.
The proposed features, their scope, and the release timeframes are estimates, not firm commitments.
