= ADR 0008: Demonstration data set sub-organization name
:revdate: 2017-12-22

== Status

Accepted

== Context

Antora is designed to work with multiple repositories, each having one or more branches organized as documentation components.
But it's unlikely the person evaluating Antora will already have documentation organized this way, or for it to be in the AsciiDoc format.
As a consequence, the content source repositories and the playbook project repository that assemble them could be an obstacle for people evaluating Antora.
It would be ideal if, when a person is evaluating Antora, they could execute the documentation pipeline on a sample data set.

We believe that creating a sample data set, including source repositories with branches and a playbook project, as well as the resulting site, will help people fully evaluate Antora and experience its capabilities "`hands-on`".
However, when we create this sample data set and playbook project, we need a publicly accessible, maintainable repository storage location.
We need to ensure that these repositories do not conflict with Antora's development repositories and its own documentation playbook project.
We need to decide how we will isolate the demonstration repositories and how we will identify them as demonstration repositories.

== Options Considered

One solution is to create a sub-organization within the Antora organization on GitLab to isolate the demonstration repositories.
The sub-organization will group the source and playbook repositories, making them easy for evaluators to find and review.
The sub-organization will also reduce some management overhead.
It can have access to current and future shared resources (such as the permissions, CI/CD processes, testing mechanisms, etc.) that we've already set up (or will set up) in the Antora organization.

Another solution is to set up a new organization for the demonstration repository.
This solution won't likely have any more overhead than a sub-organization at this time.
However, repository management may become more time consuming as any policy or process changes we make in the Antora organization will probably also need to be applied to the demonstration organization.
Divergence is likely.

Regardless of whether we set up a new organization or a sub-organization, it will need a name.
The name should clearly advertise its purpose to evaluators who discover the Antora organization and/or demonstration organization.

== Decision

We decided to set up a sub-organization in the Antora organization to host the demonstration repositories.
One of the key reasons for hosting Antora on GitLab is to take advantage of the extended feature set GitLab provides.
Sub-organizations are one of those features.

The sub-organization is called `antora/demo`.
Its initial repositories include:

[%hardbreaks]
antora/demo/demo-site
antora/demo/demo-component1-docs
antora/demo/demo-component2-docs
antora/demo/demo-component3-docs

The playbook repository is referred to as the site (i.e., demo-site).
Since this repository is what assembles the site, we want people to instinctively head there first.
We added the demo- prefix to each repository name since the last segment is used by git as the default folder when cloning.
It avoids any confusion about whether these are real docs.

We use GitLab Pages on antora/demo/demo-site to publish the demo site.

== Consequences

A functional set of source repositories, playbook project, and resulting site that include scenarios that showcase Antora's capabilities and features will allow potential users to quickly evaluate and gain hands-on experience with Antora.
The potential result of a smoother evaluation and demonstration experience is faster and greater adoption of Antora.
This demonstration data set would also have the secondary benefits of providing further testing materials, training scenarios, and examples for Antora's documentation.
However, the demonstration data set will require maintenance and QA resources to ensure it is kept aligned with Antora's functionality and provides a consistent and high-quality evaluation experience.

Creating a sub-organization for the demonstration will keep its repositories separate from Antora's development repositories, reducing confusion.
Also, the sub-organization will benefit from being able to adopt the permissions, policies, and shared resources of the parent organization.
