= ADR 0011: Align Node Support with Node LTS Schedule
:revdate: 2018-12-20

== Status

Accepted

== Context

The dependency on nodegit pinned Antora to a specific Node version (Node 8).
Since Antora 2 has replaced nodegit with isomorphic-git, we can now rethink which versions of Node we want Antora to support (i.e., test and recommend), and when to upgrade to a new version.

== Decision

Our general policy is to align our supported platform versions to the upstream platform's lifecycle (GA, EOL, etc.) schedule.

We will only support the latest patch release in a Node long term support (Node LTS) release line that is https://nodejs.org/en/about/releases/[current or active] according to the Node.js Foundation Release Working Group.
Although Antora can be used with non-LTS releases (odd major numbers), we will recommend only using a current or active Node LTS release for running Antora in production environments.
Once an LTS release has reached End of Life (EOL), support for it in Antora stops.

While we'll support a Node LTS version until its EOL, we'll recommend users upgrade to a current or active LTS release once a previous version enters its maintenance period.
This will give users the opportunity to update gradually.

== Consequences

Users will not be able to use Node LTS versions that have reached their EOL.
They'll be able to check which Node LTS versions are current and active, and there which versions Antora supports, by consulting the Node release schedule.
This will benefit us and Antora's users because everyone will be able to take advantage of stable Node features while minimizing backports and security and incompatibility issues.
We'll also know exactly when we can start preparing Antora and our infrastructure for new Node capabilities and versions.
