= Configuring a Playbook
ifndef::env-site,env-github[]
include::_attributes.adoc[]
:icons: font
endif::[]
ifdef::env-github[]
:important-caption: :exclamation:
:note-caption: :paperclip:
:warning-caption: :warning:
endif::[]
:idprefix:
:idseparator: -
:experimental:

[abstract]
The default playbook is the file _site.yml_ at the root of the project.
It's written in YAML, a common configuration language for configuring automated tasks.
Antora automatically detects and uses this file if you don't specify an override.

The playbook makes it possible for writers to control what content is included in the site without needing any knowledge of programming knowledge.
It's particularly useful for creating a partial site for local preview.

Here's an example of a playbook:

.site.yml
[source,yaml,subs=attributes+]
----
site:
  title: Docs Demo Site
content:
- repository: https://github.com/my-antora-demo/server-docs
  branches: v*
- repository: https://github.com/my-antora-demo/aspnet-docs
  branches: master
theme:
  repository: https://github.com/my-antora-demo/docs-site-ui
----

The content key is likely the one you'll tune most often.
It contains an array of repository specifications.
At a minimum, you must specify the location of each public repository using the `repository` key.
Antora will then scan and use every branch in that repository that begins with "`v`" or is named "`master`".

If you only want to generate pages for a single component, you can trim the content key down to a single entry.
For example, here's how you'd configure the `content` key so that Antora only generates the server component (using the default branch set):

.site.yml (excerpt)
[source,yaml]
----
content:
- repository: https://github.com/my-antora-demo/server-docs
----

Instead of modifying the main playbook, you can create a custom playbook and pass it to the generator.
Start by creating a new file named [.path]_custom-site.yml_.
Populate it as follows:

.custom-site.yml
[source,yaml,subs=attributes+]
----
site:
  title: Custom Docs Site
content:
- repository: https://github.com/my-antora-demo/server-docs
theme:
  repository: {uri-ui-repo}
----

You then pass your custom playbook to the generator using the `--playbook` flag, as follows:

 $ node generate --playbook=custom-site

TIP: You don't have to specify the file extension (i.e., `.yml`).
It gets added automatically if missing.

== Filtering Branches

If you want to limit the branches the generator scans and uses, you can specify an array of branch patterns using the branches key.
Each pattern is either an exact branch name or a shell glob pattern such as as `v3.*`.
If the pattern starts with a `!` character, then it is negated (i.e., the matches are excluded).
This is how you can deselect branches that were matched by the previous glob.

For example, let's say you want to include all 3.x versions of the server component except for 3.2.
You'd enter the following branches specification into the playbook:

.site.yml (excerpt)
[source,yaml]
----
- repository: https://github.com/my-antora-demo/server-docs
  branches:
  - v3.*
  - '!v3.2'
----

IMPORTANT: A negated value must be enclosed in single quotes, per YAML rules.

Here's how you'd exclude all branches that end in `-beta`.

.site.yml (excerpt)
[source,yaml]
----
- repository: https://github.com/my-antora-demo/server-docs
  branches:
  - v*
  - '!v*-beta'
----

== Altering the Metadata

The name of the repository and branch are ignored once the content is retrieved.
Metadata about the component is read from an configuration file in the repository instead.
Inside each branch you'll find a [.path]_component.yml_ file at the repository root.
That file defines the name and version of the component (i.e., the documentation version).

As an example, here's the [.path]_component.yml_ file in the v5.0 branch of the server repository:

.component.yml (excerpt)
[source,yaml]
----
name: server
version: '5.0'
----

This decoupling allows you to have more than one branch that provides the same version of a documentation component, which you can then toggle by configuring the branch filter in the playbook.
