= Antora Documentation IA & Roadmap
:r: Role:
:s: Status:

== Purpose

This document serves two purposes.
One, it provides an in-depth outline of Antora's of the categories, sub-categories, pages, and even in some cases a pages sections that we believe will be included in the documentation.
Two, it will provide a rough projection of which pages we believe should be written by quarter.
This projection is subject to change so that it aligns with the development roadmap.

== Outline

.Legend
****
C::
Category.
Entry has children.
The sub-categories and pages listed under the category are part of that category until another category is encountered.

NC-E::
Non-content entry.
The entry is not a link.

P::
Page.
Entry is a link to a documentation page.

P#::
Page section or partial.
Entry is a link to a section in a documentation page.

Role::
Short description of the purpose the page will fulfill.

SC::
Sub-category.
Entry has children.
The topics and pages listed under the sub-category are part of that sub-category until another SC or C is encountered.

Status::
Flag indicating if the entry is 1) under consideration 2) accepted 3) rejected.
Two question marks (`??`) next to the entry means it's been proposed but not considered yet.

T::
Topic (aka sub-sub-category).
Entry has children.
****

=== Basics / Getting Started / Orientation

Basics (C, NC-E)::
_{r}_ Category that the introductory pages and quick orientation pages are grouped under.
+
_{s}_ Under consideration

What is Antora (P)::
_{r}_ Describes, very concisely, what type of software Antora is, the problems it solves, and who it helps.
+
_{s}_ Accepted

Features (P)::
_{r}_ States each name of important Antora important features and capabilities.
Concisely describes each feature.
May be laid out as two columns.
+
_{s}_ Accepted

Architecture and Technologies (P)::
_{r}_ States the major architectural considerations/advantages of Antora's modular design.
Lists the major technologies it depends on.
+
_{s}_ Under consideration

License??::
_{r}_ Provides license.

Announcements??::
_{r}_ Major announcements, such as new features, patches, etc. about version.

Help??::
_{r}_ Where users can find help, such as links to the issue tracker, chat, etc.

////
Quick Install (for documentation writers/local usage)
 - List of requirements/Assumptions
 - Step 1
 - Step 2
 - ....
 - Installation Success
////

Requirements (SC?, P)::
_{r}_ Lists the prerequisites and other system considerations that need to be in place before installing Antora.
These items may or may not be broken down by OS, depending on whether or not there are special instructions per each.
+
_{s}_ Accepted

Installation (SC, P)::
_{r}_ Clear, straight-forward instructions for installing Antora on an OS.
+
_{s}_ Accepted

Assumptions (P#)::
_{r}_ Probably a section of the Installation page.
Reminds the user about the requirements/steps they should have already completed.
+
_{s}_ Under consideration

Download and Install (P)::
_{r}_ Instructions for downloading and installing Antora on an OS.
Page may be broken into a section for Linux, macOS, and Windows.
Page and/or each section will also include instructions on how to verify Antora installed and link to how to test the installation using the demo.
+
_{s}_ Accepted

Troubleshooting (P)::
_{r}_ Tips and instructions for overcoming common installation problems.
+
_{s}_ Accepted

// Methods
// Method Pros and Cons
// Next Steps

Inputs / Sources / Documentation files / Source Inputs (SC, P)::
_{r}_ Quick, basic orientation of the inputs and how they need to be organized in order for Antora to consume them.
+
_{s}_ Under consideration.
Obviously, we're having problem with what to name this SC.

Content and asset files (P or P#)::
_{r}_ Basic description of the text, image, attachment, partial and example files Antora consumes as documentation inputs.
Basic introduction of AsciiDoc.
+
_{s}_ Accepted

Navigation files (P or P#)::
_{r}_ Basic description of how the navigation content is created and stored.
+
_{s}_ Accepted

Documentation components (P or P#)::
_{r}_ Basic overview of what a documentation component is and how it is structured.
Also includes a review of what the component descriptor is.
+
_{s}_ Accepted

UI (P or P#)::
_{r}_ Basic description of the UI bundle.
+
_{s}_ Accepted

Writing Workflow (P)::
_{r}_ Tutorial that walks through the common steps a documentation writer takes when adding or modifying content in a documentation component.
+
_{s}_ Under consideration.
There are several pending questions about this page.
Dan isn't a fan of the word "`workflow`".
Is this the proper location for a high-level tutorial?

Configure (SC, P)::
_{r}_ Quick, basic orientation of how to configure the Antora pipeline in order to produce a documentation site.
+
_{s}_ Accepted

Playbook project (P or P#)::
_{r}_ Basic description of a playbook project and what it contains.
+
_{s}_ Accepted

Playbook (P or P#)::
_{r}_ Basic overview of playbook, its capabilities, and its functions and options.
+
_{s}_ Accepted

Playbook Workflow (P)::
_{r}_ Tutorial that walks through the common steps a documentation writer takes when modifying and using a playbook.
+
_{s}_ Under consideration.
There are several pending questions about this page.
Dan isn't a fan of the word "`workflow`".
Is this the proper location for a high-level tutorial?

Publish (SC, P)::
_{r}_ Quick, basic orientation of how to run Antora and what it produces.
+
_{s}_ Accepted

The antora command (P or P#)::
_{r}_ Basic description of how to run Antora and generate a documentation site.
May or may not include information about deployment environments (local; dev/testing/staging; production).
+
_{s}_ Accepted

Documentation site (P or P#)::
_{r}_ Basic description of what the generated site includes and how major features, such as URLs and the navigation menu, are determined.
May also touch on search and filtering capabilities, sitemap, 404 and other auxiliary pages.
+
_{s}_ Accepted

Generate Site Workflow (P)::
_{r}_ Tutorial that walks through the common steps a writer takes when running Antora.
+
_{s}_ Under consideration.
There are several pending questions about this page.
Dan isn't a fan of the word "`workflow`".
Is this the proper location for a high-level tutorial?

Try Antora with the Demo project (P)::
_{r}_ Could also be called Test Installation with Demo project.
The purpose of this tutorial would be for users to get quick, hands on experience with Antora--either to test their installation or evaluate it for use--by introducing them and showing them how to use it with the playbook project and documentation components in the organization.
+
_{s}_ Under consideration.
Would this be the right location for this tutorial?
Exactly how detailed would this tutorial be?
Would it even be a tutorial or more of a mention that they can use the Demo to practice the tutorials, functions, etc. on?

=== Components and Organization / File Organization & Components / File & Component Organization

Documentation Component (C, P)::
_{r}_ Full explanation of a documentation component, including its purpose, structure, and what the user should consider when organizing there source files into components.
+
_{s}_ Accepted

Structure (P)::
_{r}_ Full description of the directories and reserved directory and file names in a documentation component.
+
_{s}_ Accepted

Organizing source files (SC, P)::
_{r}_ Or: Source file organization. The considerations a user should keep in mind when choosing how to organize their source files.
+
_{s}_ Under consideration.
Not sure if this qualifies as an SC or if we've named it correctly.

Versions (P or P#)::
_{r}_ Whether to version a component or not.
How versioning impacts managing the content and the published site.
+
_{s}_ Accepted

Component or module? (P or P#)::
_{r}_ Whether a collection of files should be a component or a module within a component.
How components and modules impact managing the content and the published site.
+
_{s}_ Accepted

One or multiple modules? (P or P#)::
_{r}_ Whether a collection of files should be organized as a single module or many modules within a component.
How multiple modules within a component impact managing the content and the published site.
+
_{s}_ Accepted

Module or topic? (P or P#)::
_{r}_ Whether a collection of files should be organized as a module or a topic within a component.
How topics within a module impact managing the content and the published site.
+
_{s}_ Accepted

Naming directories and files (SC, P)::
_{r}_ Or: Directory and file names.
The considerations a user should keep in mind when choosing what to name the folders and files in their documentation.
+
_{s}_ Under consideration.
Not sure if this qualifies as an SC or if we've named it correctly.

Source to URL (P or P#)::
_{r}_ How the names of the component, module, topic directories and the file names affect a page URL.
The considerations the user should be mindful of both for writers (how filenames can affect system portability) and readers (human readable URLs) when naming.
May also include how names affect aliases, routes, navigation, and filtering.
+
_{s}_ Under consideration.
Not sure how much detail, if any, to include about aliases, routes, navigation, and filtering.

=== Pages

Pages (C, P)::
_{r}_ Full explanation of a page, including its purpose, types, structure, and behaviors.
+
_{s}_ Under consideration.

Types (SC?, P)::
_{r}_ The common types of documentation pages and their purposes.
Types include documentation (single, assembled from partials, combo), home/start/landing (page the user lands on from the root of the docs site or component), search and search results page, metadata filter and filter results page, generated pages (sitemap, 404).
+
_{s}_ Accepted

Page and UI interactions (P)::
_{r}_ Overview of how each page type and a UI template merge and what the user needs to consider (if anything).
+
_{s}_ Under consideration.

Structure (SC?, P)::
_{r}_ An overview of the major parts of a page from the AsciiDoc syntax perspective, including the purpose of the header, sections, insertions (images, partials, examples), and cross references.
This may also be where we give a full description of how the filename, alias, and URL are related.
+
_{s}_ Under consideration.
There's a lot of ambiguity about how much detail this page should include and whether or not this is where the filename, alias, and URL relationship should be explained.
Is this where a user would look for this info?
