= Antora Documentation IA & Roadmap
:r: Role:
:s: Status:

== Purpose

This document serves two purposes.
One, it provides an in-depth outline of Antora's of the categories, sub-categories, pages, and even in some cases a pages sections that we believe will be included in the documentation.
Two, it will provide a rough projection of which pages we believe should be written by quarter.
This projection is subject to change so that it aligns with the development roadmap.

== Outline

.Legend
****
C::
Category.
Entry has children.
The sub-categories and pages listed under the category are part of that category until another category is encountered.

NC-E::
Non-content entry.
The entry is not a link.

P::
Page.
Entry is a link to a documentation page.

P#::
Page section or partial.
Entry is a link to a section in a documentation page.

Role::
Short description of the purpose the page will fulfill.

SC::
Sub-category.
Entry has children.
The topics and pages listed under the sub-category are part of that sub-category until another SC or C is encountered.

Status::
Flag indicating if the entry is 1) under consideration 2) accepted 3) rejected.
A question mark (`?`) next to the entry means it's been proposed but not considered yet.

T::
Topic (aka sub-sub-category).
Entry has children.
****

== Basics / Getting Started / Orientation

Basics (C, NC-E)::
_{r}_ Category that the introductory pages and quick orientation pages are grouped under.
+
_{s}_ Under consideration

What is Antora (P)::
_{r}_ Describes, very concisely, what type of software Antora is, the problems it solves, and who it helps.
+
_{s}_ Accepted

Features (P)::
_{r}_ States each name of important Antora important features and capabilities.
Concisely describes each feature.
May be laid out as two columns.
+
_{s}_ Accepted

Architecture and Technologies (P)::
_{r}_ States the major architectural considerations/advantages of Antora's modular design.
Lists the major technologies it depends on.
+
_{s}_ Under consideration

License??::
_{r}_ Provides license.

Announcements??::
_{r}_ Major announcements, such as new features, patches, etc. about version.

Help??::
_{r}_ Where users can find help, such as links to the issue tracker, chat, etc.

////
Quick Install (for documentation writers/local usage)
 - List of requirements/Assumptions
 - Step 1
 - Step 2
 - ....
 - Installation Success
////

Requirements (SC?, P)::
_{r}_ Lists the prerequisites and other system considerations that need to be in place before installing Antora.
These items may or may not be broken down by OS, depending on whether or not there are special instructions per each.
+
_{s}_ Accepted

Installation (SC, P)::
_{r}_ Clear, straight-forward instructions for installing Antora on an OS.
+
_{s}_ Accepted

Assumptions (P#)::
_{r}_ Probably a section of the Installation page.
Reminds the user about the requirements/steps they should have already completed.
+
_{s}_ Under consideration

Download and Install (P)::
_{r}_ Instructions for downloading and installing Antora on an OS.
Page may be broken into a section for Linux, macOS, and Windows.
Page and/or each section will also include instructions on how to verify Antora installed and link to how to test the installation using the demo.
+
_{s}_ Accepted

Troubleshooting (P)::
_{r}_ Tips and instructions for overcoming common installation problems.
+
_{s}_ Accepted

// Methods
// Method Pros and Cons
// Next Steps

Inputs / Sources / Documentation files / Source Inputs (SC, P)::
_{r}_ Quick, basic orientation of the inputs and how they need to be organized in order for Antora to consume them.
+
_{s}_ Under consideration.
Obviously, we're having problem with what to name this SC.

Content and asset files (P or P#)::
_{r}_ Basic description of the text, image, attachment, partial and example files Antora consumes as documentation inputs.
Basic introduction of AsciiDoc.
+
_{s}_ Accepted

Navigation files (P or P#)::
_{r}_ Basic description of how the navigation content is created and stored.
+
_{s}_ Accepted

Documentation components (P or P#)::
_{r}_ Basic overview of what a documentation component is and how it is structured.
Also includes a review of what the component descriptor is.
+
_{s}_ Accepted

UI (P or P#)::
_{r}_ Basic description of the UI bundle.
+
_{s}_ Accepted

Writing Workflow (P)::
_{r}_ Tutorial that walks through the common steps a documentation writer would take when adding or modifying content in a documentation component.
+
_{s}_ Under consideration.
There are several pending questions about this page.
Dan isn't a fan of the word "`workflow`".
Is this the proper location for a high-level tutorial?
