= Install Antora

To generate and publish documentation sites with Antora, you need the Antora command line interface (CLI) and an Antora site generator pipeline.

Assumptions:

* [x] You've installed an active Node LTS release on your xref:linux-requirements.adoc#node[Linux], xref:windows-requirements.adoc#node[Windows], or xref:macos-requirements.adoc#node[macOS] machine.

On this page, you'll learn:

* [x] How to install Antora globally. (recommended)
* [x] How to install the Antora CLI and site generator packages in a project directory.

We recommend installing Antora globally, especially if you're managing several documentation sites.
When we say "`globally`" here, it does not imply system-wide.
It means the location where Node is installed.
If you used nvm to install Node, this location will be inside your home directory (thus not requiring elevated permissions).
However, you can also install Antora in a project directory if you prefer.

== Install Antora globally using npm

To install the Antora CLI and site generator packages globally, open a terminal and type:

 $ npm i -g @antora/cli @antora/site-generator-default

Verify the `antora` command is available on your PATH by running:

 $ antora -v

If installation was successful, the command should report the version of Antora.

[subs=attributes+]
 $ antora -v
 {page-component-version}.0

CAUTION: If you're using a system-wide Node installation managed by your operating system's package manager, you may run into permission problems when installing packages globally.
In that case, you'll need to <<install-dir,install Antora directly in your project repository>>.

== Install Antora globally using Yarn

If you prefer Yarn over npm, use this command to install the Antora CLI package:

 $ yarn global add @antora/cli

Next, install the default site generator.

 $ yarn global add @antora/site-generator-default

[#install-dir]
== Install Antora in a project directory

You can opt to install Antora in a project directory, such as the directory where the playbook file(s) for your site are stored.

When possible, we recommend installing the Antora CLI globally so that the `antora` command is available on your PATH.
You can then install the site generator packages in a project directory.

To install *only* the CLI globally, type:

.Install Antora CLI package globally
 $ npm i -g @antora/cli

Or, to install the CLI in a project directory, change into your project directory, and type:

.Install Antora CLI package in a project directory
 $ npm i @antora/cli

Dropping the `-g` flag installs the package under the [.path]_node_modules_ folder in the current directory.

Verify the `antora` command is available on your PATH by running `antora -v`.
If you installed the package without the `-g` flag, you'll need to prefix the command with `$(npm bin)/`.

.If installed globally
 $ antora -v

.If installed in a project directory
 $ $(npm bin)/antora -v

The command should report the Antora CLI version in the terminal.

[subs=attributes+]
 {page-component-version}.0

If you installed the CLI globally, change into the project directory before installing the site generator.

Next, install the site generator package.

 $ npm i @antora/site-generator-default

The `@antora/site-generator-default` and its dependent packages will be installed into the [.path]_node_modules_ folder inside your project.
The `antora` command will look for these packages there first before looking in the global installation folder.

== Next

Now that Antora is installed, you're ready to:

* Set up your own xref:playbook:index.adoc[playbook] or use the Demo playbook.
* Organize a xref:ROOT:component-structure.adoc[documentation component repository] or use Antora's Demo docs components.
* xref:ROOT:run-antora.adoc[Run Antora] and generate a documentation site.


//IMPORTANT: The `@` at the beginning of the package name is important.
//It tells `npm` that the `cli` package is located in the `antora` group.
//If you omit this character, `npm` will assume the package name is the name of a git repository on GitHub.
