= Linux Installation Requirements
:platform: Linux
:page-partial:
//tag::shared[]
:version-node-major: 12
:version-node: {version-node-major}.13.0
:url-node-releases: https://nodejs.org/en/about/releases/
:url-nvm: https://github.com/nvm-sh/nvm
:url-nvm-install: {url-nvm}#installation-and-update

On this page, you'll learn:

* [x] How to install Node.

Since Antora is built on Node.js, you'll need Node installed on your machine to install and run Antora.

== Node

We recommend using the latest long term support (LTS) release of Node.
While you can use other versions of Node, Antora is only tested against {url-node-releases}[active LTS releases^].

To see if you have Node installed, and which version, open a terminal and type:

 $ node --version

You should see a version string, such as:

[subs=attributes+]
....
v{version-node}
....

If *the command fails with an error*, it means you don't have Node installed.
The best way to install Node is to use nvm (Node Version Manager).
Skip to <<install-nvm>> to find instructions.

ifeval::["{platform}" == "Linux"]
NOTE: If your package manager provides Node and npm packages, _and you're familiar with using the tools installed system-wide_, you may choose to go that route.
However, we believe you'll be more successful if you choose <<install-nvm,nvm>>.
endif::[]

If *the command returns a version that isn't an active LTS version*, upgrade to the latest Node LTS version <<upgrade-node,using nvm>> (or your package manager).

If *the command returns an active Node LTS version*, make sure that version is set as your default version by typing the following command in your terminal:

[subs=attributes+]
 $ nvm alias default {version-node-major}

Now you're ready to xref:install-antora.adoc[install Antora].

[#install-nvm]
== Install nvm and Node

We recommend using the {url-nvm}[Node Version Manager (nvm)^] to manage your Node installations.
Follow these {url-nvm-install}[installation instructions^] to set up nvm on your machine.
Then, return here.

TIP: Many CI environments use nvm to manage the version of Node used in the build job.
By using nvm, you can align your setup with the environment used to generate and publish your production site.

Once you've installed nvm, open a new terminal and install the latest Node LTS release.

 $ nvm install --lts

The above command will install the latest LTS release of Node and automatically set it as your default alias.

Now that you have Node set up, you can xref:install-antora.adoc[install Antora].

[#upgrade-node]
== Upgrade Node using nvm

If you have nvm installed, but don't have the latest LTS version installed, type the following command in your terminal:

 $ nvm install --lts

To set the latest version of Node as the default for any new terminal, type:

[subs=attributes+]
 $ nvm alias default {version-node-major}

Now that you're on the latest LTS version of Node, you can xref:install-antora.adoc[install Antora].
//end::shared[]
