= Supported Platforms and System Requirements
:test-count: over 900
:test-coverage: 99%
// URLs
:url-repo: https://gitlab.com/antora/antora
:url-issues: {url-repo}/issues
:url-chat-dev: https://gitter.im/antora/dev

Antora runs on Linux, macOS, and Windows.
Thanks to this broad platform support, Antora can also be used on all well-known cloud platforms and continuous integration and delivery servers.

This page provides an <<platforms,overview of the platforms>> Antora supports and directs you to the <<next,system requirements>> for each platform.
The Antora project also provides an official xref:ROOT:antora-container.adoc[Docker container] you can use to bypass the installation process.

== Platforms

Antora is actively tested on the platforms listed below.

// When we have specific notes about a platform (tweaks and/or links to bugs) add a 3rd column to this table labeled "Good to Know"
[cols="20,25a",width="45%"]
|===
|Supported Platform |Supported Version(s)

|Alpine Linux
|[%hardbreaks]
3.8
3.7
3.6

|Debian
|[%hardbreaks]
9.6

|Fedora
|[%hardbreaks]
29
28

|macOS
|High Sierra

|Microsoft
|[%hardbreaks]
Windows 10
Windows 8.1
Windows Server 2016
Windows Server 2012 R2

|Chrome
|Latest stable version

|Firefox
|Latest stable version

|Internet Explorer
|11

|MS Edge
|Latest stable version

|Node.js
|[%hardbreaks]
10 (latest patch release)
8 (latest patch release)
|===

Regarding Linux, while we only continuously test Antora on Fedora, Alpine Linux, and Ubuntu, we anticipate it should operate as expected on most well-known Linux distributions.

.About the Antora Test Suite
****
At last count, Antora had {test-count} tests that cover over {test-coverage} of the lines.
And we add more tests with every change.
You could say we're just a teeny bit obsessed with writing high quality tests and maintaining complete test coverage.
****

== Cloud platforms

Antora should operate as designed on common cloud platforms.
How you provision your cloud instance depends on your workload requirements and remote git repository sizes.
If you're running Antora on a cloud platform, we would love to hear about your experience (open a {url-issues}[new issue^] or join us in the {url-chat-dev}[development channel^]).

////
== Virtual Machine (VM) environments

Antora runs in VirtualBox and should operate as designed in common VM environments such as VMware.
If you're running Antora in a VM environment, we would love to hear about your experience (open a {url-issues}[new issue^] or join us in the {url-chat-dev}[development channel^]).
////

== Hardware recommendations

Your hardware requirements will depend primarily on the size of the remote git repositories your Antora pipeline fetches content from when it is generating your site.

The first time Antora runs, it fetches and clones all of the remote git repositories specified in a playbook.
The speed of this operation is dictated by the size of the remote repositories, environment input/output parameters, and network performance.
After the initial run, Antora caches the repositories locally.
On subsequent runs, Antora only reconnects to the remote repositories if the xref:playbook:configure-runtime.adoc#pull[pull option] is enabled or the xref:playbook:configure-runtime.adoc#cache[cache folder] is removed.

[cols="5s,70",width="75%"]
|===
|RAM
|Memory requirements depend on the size of your Git repositories.
3GB should provide sufficient headroom.

|I/O
|Maximum throughput and minimum latency always make things nicer but aren't required.
|===

== Next

Prep your system for installing Antora:

* xref:linux-requirements.adoc[Linux requirements]
* xref:macos-requirements.adoc[macOS requirements]
* xref:windows-requirements.adoc[Windows requirements]

Or try out the official xref:ROOT:antora-container.adoc[Antora Docker container].

////
OS Release schedule links

Alpine: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
- 3.7 ends 2019-11-01
- 3.6.2 ends 2019-05-01, gets security fixes only

Arch: https://www.archlinux.org/releng/releases/

Arch Linux releases once a month, with only the 3 most recent distros being officially available

Debian: https://www.debian.org/releases/stable/

Fedora: https://fedoraproject.org/wiki/Releases

Fedora 29 will be released approx Nov 2018
Fedora 27 EOL approx Dec 2018

Ubuntu Linux: https://wiki.ubuntu.com/Releases

16.04.3 LTS is the most recent LTS release.
17.10 is the most recent regular release, EOL July 2018
18.04 LTS is due to be released in April 2018

openSUSE: https://en.opensuse.org/Portal:42.3

Leap 42.3 is the current release
Checkout the Open Build Project: http://openbuildservice.org

Windows: https://en.wikipedia.org/wiki/Comparison_of_Microsoft_Windows_versions

Windows 8.1 is supported by MS until 2023-01-10
Windows Server 2012 R2 until 2023-10-10
Windows Server 2016 / Windows 10 don't have an EOL date (as of 2018-03-10)

Antora is tested on NTFS on Windows, we may want to checkout how it works on the ReFS on Windows Server 2016 in the future

MS Edge: replaces IE 11 which is not being developed further; it is the default browser for Windows 10/Server 2016
////
