= Supported Platforms and System Requirements
:test-count: over 900
:test-coverage: 99%
// URLs
:url-repo: https://gitlab.com/antora/antora
:url-issues: {url-repo}/issues
:url-chat-dev: https://gitter.im/antora/dev

Antora runs on Linux, macOS, and Windows.
Thanks to this broad platform support, Antora is also used on many cloud platforms and continuous integration and delivery servers.

== Platforms

Our general policy is to align Antora's support of a platform version with the upstream project's lifecycle schedule for that version.
When a platform version reaches its End of Life (EOL), Antora no longer supports it.

// When we have specific notes about a platform (tweaks and/or links to bugs) add a 3rd column to this table labeled "Good to Know"
[cols="20,25a",width="50%"]
|===
|Supported Platform |Supported Version(s)

|Alpine Linux
|&#8805; 3.6

|Debian
|&#8805; 9.6

|Fedora
|&#8805; 28

|Ubuntu
|[%hardbreaks]
16.04 LTS
18.04 LTS

|macOS
|[%hardbreaks]
High Sierra
Mojave

|Microsoft
|[%hardbreaks]
Windows 10
Windows Server 2016

|Chrome
|Latest stable version

|Firefox
|Latest stable version

|Internet Explorer
|11

|MS Edge
|Latest stable version

|Node.js
|[%hardbreaks]
10
8
|===

.About the Antora Test Suite
****
At last count, Antora had {test-count} tests that cover {test-coverage} of the lines.
You could say we're just a teeny-tiny bit obsessed with writing high quality tests and improving test coverage.
****

=== Cloud platforms

Antora should operate as designed on common cloud platforms.
How you provision your cloud instance depends on your workload requirements and remote git repository sizes.
If you're running Antora on a cloud platform, we would love to hear about your experience (open a {url-issues}[new issue^] or join us in the {url-chat-dev}[development channel^]).

== Hardware recommendations

Your hardware requirements will depend primarily on the size of the remote git repositories your Antora pipeline fetches content from when it is generating your site.

The first time Antora runs, it fetches and clones all of the remote git repositories specified in a playbook.
The speed of this operation is dictated by the size of the remote repositories, environment input/output parameters, and network performance.
After the initial run, Antora caches the repositories locally.
On subsequent runs, Antora only reconnects to the remote repositories if the xref:playbook:configure-runtime.adoc#pull[pull option] is enabled or the xref:playbook:configure-runtime.adoc#cache[cache folder] is removed.

[cols="5s,70",width="75%"]
|===
|RAM
|Memory requirements depend on the size of your Git repositories.
3GB should provide sufficient headroom.

|I/O
|Maximum throughput and minimum latency always make things nicer but aren't required.
|===

== Next

* xref:upgrade-antora.adoc[Upgrade to the latest Antora release].

* Install Antora for the first time on:

** xref:linux-requirements.adoc[Linux]
** xref:macos-requirements.adoc[macOS]
** xref:windows-requirements.adoc[Windows]

* Try the official xref:ROOT:antora-container.adoc[Antora Docker container].

////
OS Release schedule links

Alpine: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
- 3.7 ends 2019-11-01
- 3.6.2 ends 2019-05-01, gets security fixes only

Arch: https://www.archlinux.org/releng/releases/

Arch Linux releases once a month, with only the 3 most recent distros being officially available

Debian: https://www.debian.org/releases/stable/

Fedora: https://fedoraproject.org/wiki/Releases

Fedora 29 will be released approx Nov 2018

Ubuntu Linux: https://wiki.ubuntu.com/Releases


openSUSE: https://en.opensuse.org/Portal:42.3

Leap 42.3 is the current release
Checkout the Open Build Project: http://openbuildservice.org

Windows: https://en.wikipedia.org/wiki/Comparison_of_Microsoft_Windows_versions

Windows 8.1 is supported by MS until 2023-01-10
Windows Server 2012 R2 until 2023-10-10
Windows Server 2016 / Windows 10 don't have an EOL date (as of 2018-03-10)

Antora is tested on NTFS on Windows, we may want to checkout how it works on the ReFS on Windows Server 2016 in the future

MS Edge: replaces IE 11 which is not being developed further; it is the default browser for Windows 10/Server 2016
////
