= Document Converter Guidebook

== Context

In Antora, documentation pages are written in AsciiDoc.
Every AsciiDoc document under the [.path]_pages_ folder (excluding partials) gets implicitly mapped to a web page in the site.
The AsciiDoc must be converted to HTML so the contents of these documents can be displayed as a web page.

== Functional Overview

The files in the `page` family of the content catalog (i.e., text documents taken from the [.path]_pages_ directory, excluding partials or underscore files) are written in AsciiDoc format.
These AsciiDoc documents are used to populate the main area of the web page.
The document converter should use an AsciiDoc processor (Asciidoctor.js) to convert these files to HTML by way of the AsciiDoc loader component.

At this stage, the AsciiDoc only needs to be converted to embeddable HTML.
That embeddable HTML is later enclosed in a web page template by the page generator component to produce the complete page.
Page metadata in the document header may be used by the template to control the presentation of auxiliary elements in the web page.
Therefore, that page metadata should be accessible to the template via the file object.

The document converter should delegate to the AsciiDoc loader to load the AsciiDoc into a document object.
It should then convert that document object to embeddable HTML.

When document conversion is complete, the `contents` property on the file object should be replaced with the embeddable HTML generated from the AsciiDoc, and the `asciidoc` property should store the attributes from the document header (including those passed to the processor).

== Software Architecture

The document converter component functionality is provided by the document-converter module.

At a high level, this component is an AsciiDoc to HTML converter that operates on the files in the `page` family of the content catalog.
All the details of loading the AsciiDoc should be handled by the AsciiDoc loader component.

For each publishable file in the `page` family (files which have an `out` property), this component should:

* Use the `loadAsciiDoc()` function of the AsciiDoc loader component to transform the virtual AsciiDoc file into a document object.
* Invoke the `getAttributes()` method on the document object to retrieve the attributes.
 ** Assign the result to the `asciidoc.attributes` property on the file.
* If the `page-partial` attribute is set on the document, back up the AsciiDoc contents to the `src.contents` of the input file.
 ** Backing up the AsciiDoc contents ensures that the AsciiDoc source of this file can still be included in another page, even if this page gets converted first.
* Invoke the `convert()` method on that object to generate the HTML.
 ** Assign the result to the `contents` property on the file.
 ** Set the `mediaType` property to `text/html` (to reflect the current format of `contents`)

=== Inputs and outputs

.Inputs
* `page` family from the content catalog
* Playbook (`asciidoc.attributes`)
* Content catalog (`catalog`)

.Output
* _none_ (mutates the files in the `page` family of the content catalog)

== Code

The document converter is implemented as a dedicated node package (i.e., module).
The document converter API exports the `convertDocuments()` function, which takes a playbook and a content catalog and converts all publishable documents in the `page` family (documents which have an `out` property defined).
It then returns the files which should be published as pages (even those which are not AsciiDoc documents).
It also exports the `convertDocument()` function, which can be used to operate on a single file.

The API for the document converter should be used as follows:

// Q: should the convertDocuments return a collection of files which were converted?
[source,js]
----
const convertDocuments = require('@antora/document-converter')

//...

const pages = convertDocuments(playbook, catalog)
----

Alternately, the pipeline can handle the conversion itself:

// TODO check this code
[source,js]
----
const convertDocument = require('@antora/document-converter/lib/convert-document')

//...

catalog.getPages().filter((file) => 'out' in file).forEach((file) => {
  await convertDocument(file, playbook, catalog)
})
----

== Data

The document converter mutates the files in the `page` family of the content catalog, which can be retrieved by invoking `getPages()` on the content catalog then selecting files that have an `out` property.
Specifically, this component updates the value of the `contents` property by replacing the AsciiDoc with embeddable HTML.
The previous value is still accessible via the `history` property on the file.
It also assigns a hash of header attributes to the `asciidoc.attributes` property on the file object.

// Q: should it also incorporate attributes from antora.yml?
When converting each AsciiDoc document, this component incorporates global AsciiDoc attributes defined in the playbook (at the path `asciidoc.attributes`).
These attributes are passed to the AsciiDoc loader.

== Consequences

The document converter component allows text documents to be written in AsciiDoc.
Each non-partial, AsciiDoc document becomes a web page in the generated site.
This component converts the AsciiDoc to embeddable HTML, which is used as the contents of the main area of the web page.

As a result of invoking the main function for this component, the file contents of the files in the `page` family of the content catalog has been converted from AsciiDoc to embeddable HTML.
The contents of these files are now ready to be wrapped in a web page template and written to the generated site.

This component hands off processing to the page generator component, which wraps the embeddable HTML created by this component in a web page template to produce a complete web page.
